// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, _a1, password, workspace
func (_m *Service) SendEmail(ctx context.Context, _a1 string, password string, workspace string) error {
	ret := _m.Called(ctx, _a1, password, workspace)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, _a1, password, workspace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
