package configs

var TablesToResourceTypes = map[string]string{
	"azuread_group":                        "Microsoft.Entra/groups",
	"azuread_group_membership":             "Microsoft.Entra/groupMemberships",
	"azuread_device":                       "Microsoft.Entra/devices",
	"azuread_sign_in_report":               "Microsoft.Entra/signInReports",
	"azuread_application":                  "Microsoft.Entra/applications",
	"azuread_app_registration":             "Microsoft.Entra/appRegistrations",
	"azuread_enterprise_application":       "Microsoft.Entra/enterpriseApplication",
	"azuread_managed_identity":             "Microsoft.Entra/managedIdentity",
	"azuread_microsoft_application":        "Microsoft.Entra/microsoftApplication",
	"azuread_domain":                       "Microsoft.Entra/domains",
	"azuread_tenant":                       "Microsoft.Entra/tenant",
	"azuread_identity_provider":            "Microsoft.Entra/identityproviders",
	"azuread_security_defaults_policy":     "Microsoft.Entra/securitydefaultspolicy",
	"azuread_authorization_policy":         "Microsoft.Entra/authorizationpolicy",
	"azuread_conditional_access_policy":    "Microsoft.Entra/conditionalaccesspolicy",
	"azuread_admin_consent_request_policy": "Microsoft.Entra/adminconsentrequestpolicy",
	"azuread_user_registration_details":    "Microsoft.Entra/userregistrationdetails",
	"azuread_service_principal":            "Microsoft.Entra/serviceprincipals",
	"azuread_user":                         "Microsoft.Entra/users",
	"azuread_directory_role":               "Microsoft.Entra/directoryroles",
	"azuread_directory_setting":            "Microsoft.Entra/directorysettings",
	"azuread_directory_audit_report":       "Microsoft.Entra/directoryauditreport",
}

var ResourceTypesList = []string{
	"Microsoft.Entra/groups",
	"Microsoft.Entra/groupMemberships",
	"Microsoft.Entra/devices",
	"Microsoft.Entra/signInReports",
	"Microsoft.Entra/applications",
	"Microsoft.Entra/appRegistrations",
	"Microsoft.Entra/enterpriseApplication",
	"Microsoft.Entra/managedIdentity",
	"Microsoft.Entra/microsoftApplication",
	"Microsoft.Entra/domains",
	"Microsoft.Entra/tenant",
	"Microsoft.Entra/identityproviders",
	"Microsoft.Entra/securitydefaultspolicy",
	"Microsoft.Entra/authorizationpolicy",
	"Microsoft.Entra/conditionalaccesspolicy",
	"Microsoft.Entra/adminconsentrequestpolicy",
	"Microsoft.Entra/userregistrationdetails",
	"Microsoft.Entra/serviceprincipals",
	"Microsoft.Entra/users",
	"Microsoft.Entra/directoryroles",
	"Microsoft.Entra/directorysettings",
	"Microsoft.Entra/directoryauditreport",
}
