package steampipe

import (
	"strings"

	"github.com/kaytu-io/kaytu-util/pkg/keibi-es-sdk"
)

var azureMap = map[string]string{
	"Microsoft.Compute/disks":                                  "azure_compute_disk",
	"Microsoft.DBforMySQL/servers":                             "azure_mysql_server",
	"Microsoft.Network/networkWatchers":                        "azure_network_watcher",
	"Microsoft.Resources/links":                                "azure_resource_link",
	"Microsoft.Network/virtualNetworks/subnets":                "azure_subnet",
	"Microsoft.ContainerRegistry/registries":                   "azure_container_registry",
	"Microsoft.ContainerService/managedClusters":               "azure_kubernetes_cluster",
	"Microsoft.HDInsight/clusters":                             "azure_hdinsight_cluster",
	"Microsoft.KeyVault/vaults/keys":                           "azure_key_vault_key",
	"Microsoft.Kusto/clusters":                                 "azure_kusto_cluster",
	"Microsoft.DataFactory/factories":                          "azure_data_factory",
	"Microsoft.DataFactory/factoriesDatasets":                  "azure_data_factory_dataset",
	"Microsoft.DataFactory/factoriesPipelines":                 "azure_data_factory_pipeline",
	"Microsoft.Search/searchServices":                          "azure_search_service",
	"Microsoft.SignalRService/signalR":                         "azure_signalr_service",
	"Microsoft.ApiManagement/service":                          "azure_api_management",
	"Microsoft.Authorization/elevateAccessRoleAssignment":      "azure_role_assignment",
	"Microsoft.DocumentDB/databaseAccounts":                    "azure_cosmosdb_account",
	"Microsoft.DocumentDB/databaseAccountsSqlDatabases":        "azure_cosmosdb_sql_database",
	"Microsoft.DocumentDB/databaseAccountsMongoDatabases":      "azure_cosmosdb_mongo_database",
	"Microsoft.DBforMariaDB/servers":                           "azure_mariadb_server",
	"Microsoft.Authorization/roleDefinitions":                  "azure_role_definition",
	"Microsoft.Network/applicationGateways":                    "azure_application_gateway",
	"Microsoft.KeyVault/vaults/secrets":                        "azure_key_vault_secret",
	"Microsoft.Web/hostingEnvironments":                        "azure_app_service_environment",
	"Microsoft.Compute/virtualMachineScaleSets":                "azure_compute_virtual_machine_scale_set",
	"Microsoft.EventGrid/domains":                              "azure_eventgrid_domain",
	"Microsoft.EventGrid/domains/topics":                       "azure_eventgrid_topic",
	"Microsoft.DataBoxEdge/dataBoxEdgeDevices":                 "azure_databox_edge_device",
	"Microsoft.StorageSync/storageSyncServices":                "azure_storage_sync",
	"Microsoft.Insights/logProfiles":                           "azure_log_profile",
	"Microsoft.Resources/users":                                "azuread_user",
	"Microsoft.Network/networkWatchers/flowLogs":               "azure_network_watcher_flow_log",
	"Microsoft.Sql/servers":                                    "azure_sql_server",
	"Microsoft.Storage/storageAccounts":                        "azure_storage_account",
	"Microsoft.StorageCache/caches":                            "azure_hpc_cache",
	"Microsoft.KeyVault/managedHsms":                           "azure_key_vault_managed_hardware_security_module",
	"Microsoft.Devices/iotHubs":                                "azure_iothub",
	"Microsoft.Devices/iotHubDpses":                            "azure_iothub_dps",
	"Microsoft.Sql/managedInstances":                           "azure_mssql_managed_instance",
	"Microsoft.AppPlatform/Spring":                             "azure_spring_cloud_service",
	"Microsoft.Security/autoProvisioningSettings":              "azure_security_center_auto_provisioning",
	"Microsoft.Security/securityContacts":                      "azure_security_center_contact",
	"Microsoft.Security/locations/jitNetworkAccessPolicies":    "azure_security_center_jit_network_access_policy",
	"Microsoft.CognitiveServices/accounts":                     "azure_cognitive_account",
	"Microsoft.HybridCompute/machines":                         "azure_hybrid_compute_machine",
	"Microsoft.ServiceBus/namespaces":                          "azure_servicebus_namespace",
	"Microsoft.Resources/tenants":                              "azure_tenant",
	"Microsoft.Sql/servers/databases":                          "azure_sql_database",
	"Microsoft.Network/networkInterfaces":                      "azure_network_interface",
	"Microsoft.Web/sites":                                      "azure_app_service_function_app",
	"Microsoft.Authorization/policyAssignments":                "azure_policy_assignment",
	"Microsoft.Resources/subscriptions":                        "azure_subscription",
	"Microsoft.DataLakeAnalytics/accounts":                     "azure_data_lake_analytics_account",
	"Microsoft.Network/frontDoors":                             "azure_frontdoor",
	"Microsoft.KeyVault/vaults":                                "azure_key_vault",
	"Microsoft.Network/virtualNetworks":                        "azure_virtual_network",
	"Microsoft.ServiceFabric/clusters":                         "azure_service_fabric_cluster",
	"Microsoft.Web/staticSites":                                "azure_app_service_web_app",
	"Microsoft.Insights/activityLogAlerts":                     "azure_log_alert",
	"Microsoft.Resources/subscriptions/locations":              "azure_location",
	"Microsoft.Resources/subscriptions/resourceGroups":         "azure_resource_group",
	"Microsoft.Compute/virtualMachines":                        "azure_compute_virtual_machine",
	"Microsoft.DBforPostgreSQL/servers":                        "azure_postgresql_server",
	"Microsoft.EventGrid/topics":                               "azure_eventgrid_topic",
	"Microsoft.MachineLearningServices/workspaces":             "azure_machine_learning_workspace",
	"Microsoft.Insights/guestDiagnosticSettings":               "azure_diagnostic_setting",
	"Microsoft.Cache/redis":                                    "azure_redis_cache",
	"Microsoft.Compute/diskAccesses":                           "azure_compute_disk_access",
	"Microsoft.DataLakeStore/accounts":                         "azure_data_lake_store",
	"Microsoft.Synapse/workspaces":                             "azure_synapse_workspace",
	"Microsoft.HealthcareApis/services":                        "azure_healthcare_service",
	"Microsoft.Security/pricings":                              "azure_security_center_subscription_pricing",
	"Microsoft.Logic/workflows":                                "azure_logic_app_workflow",
	"Microsoft.Batch/batchAccounts":                            "azure_batch_account",
	"Microsoft.ClassicNetwork/networkSecurityGroups":           "azure_network_security_group",
	"Microsoft.StreamAnalytics/streamingJobs":                  "azure_stream_analytics_job",
	"Microsoft.Security/settings":                              "azure_security_center_setting",
	"Microsoft.AppConfiguration/configurationStores":           "azure_app_configuration",
	"Microsoft.EventHub/namespaces":                            "azure_eventhub_namespace",
	"Microsoft.Storage/storageAccounts/containers":             "azure_storage_container",
	"Microsoft.Network/applicationSecurityGroups":              "azure_network_applicationsecuritygroups",
	"Microsoft.RecoveryServices/vaults":                        "azure_recoveryservices_vault",
	"Microsoft.Network/azureFirewalls":                         "azure_network_azurefirewall",
	"Microsoft.Network/expressRouteCircuits":                   "azure_network_expressroutecircuit",
	"Microsoft.Network/loadBalancers":                          "azure_lb",
	"Microsoft.Network/routeTables":                            "azure_network_routetables",
	"Microsoft.Compute/snapshots":                              "azure_compute_snapshots",
	"Microsoft.Network/virtualNetworkGateways":                 "azure_network_virtualnetworkgateway",
	"Microsoft.Compute/availabilitySets":                       "azure_compute_availabilityset",
	"Microsoft.Compute/diskEncryptionSets":                     "azure_compute_diskencryptionset",
	"Microsoft.Kubernetes/connectedClusters":                   "azure_hybridkubernetes_connectedcluster",
	"Microsoft.Authorization/policyDefinitions":                "azure_authorization_policydefinition",
	"Microsoft.CostManagement/CostByResourceType":              "azure_costmanagement_costbyresourcetype",
	"Microsoft.CostManagement/CostBySubscription":              "azure_costmanagement_costbysubscription",
	"Microsoft.Compute/image":                                  "azure_compute_image",
	"Microsoft.Resources/groups":                               "azuread_group",
	"Microsoft.Resources/serviceprincipals":                    "azuread_service_principal",
	"Microsoft.Web/plan":                                       "azure_app_service_plan",
	"Microsoft.Compute/disksreadops":                           "azure_compute_disk_metric_read_ops",
	"Microsoft.Compute/disksreadopsdaily":                      "azure_compute_disk_metric_read_ops_daily",
	"Microsoft.Compute/disksreadopshourly":                     "azure_compute_disk_metric_read_ops_hourly",
	"Microsoft.Compute/diskswriteops":                          "azure_compute_disk_metric_write_ops",
	"Microsoft.Compute/diskswriteopsdaily":                     "azure_compute_disk_metric_write_ops_daily",
	"Microsoft.Compute/diskswriteopshourly":                    "azure_compute_disk_metric_write_ops_hourly",
	"Microsoft.Compute/resourceSku":                            "azure_compute_resource_sku",
	"Microsoft.Compute/virtualMachineCpuUtilization":           "azure_compute_virtual_machine_metric_cpu_utilization",
	"Microsoft.Compute/virtualMachineCpuUtilizationDaily":      "azure_compute_virtual_machine_metric_cpu_utilization_daily",
	"Microsoft.Compute/virtualMachineCpuUtilizationHourly":     "azure_compute_virtual_machine_metric_cpu_utilization_hourly",
	"Microsoft.Compute/virtualMachineScaleSetNetworkInterface": "azure_compute_virtual_machine_scale_set_network_interface",
	"Microsoft.Compute/virtualMachineScaleSetsVm":              "azure_compute_virtual_machine_scale_set_vm",
	"Microsoft.KeyVault/deletedVaults":                         "azure_key_vault_deleted_vault",
	"Microsoft.LoadBalancer/backendAddressPools":               "azure_lb_backend_address_pool",
	"Microsoft.LoadBalancer/natRules":                          "azure_lb_nat_rule",
	"Microsoft.LoadBalancer/outboundRules":                     "azure_lb_outbound_rule",
	"Microsoft.LoadBalancer/probes":                            "azure_lb_probe",
	"Microsoft.LoadBalancer/rules":                             "azure_lb_rule",
	"Microsoft.Management/groups":                              "azure_management_group",
	"Microsoft.Management/locks":                               "azure_management_lock",
	"Microsoft.Sql/elasticPools":                               "azure_mssql_elasticpool",
	"Microsoft.Sql/virtualMachines":                            "azure_mssql_virtual_machine",
	"Microsoft.Sql/flexibleServers":                            "azure_mysql_flexible_server",
	"Microsoft.Network/natGateways":                            "azure_nat_gateway",
	"Microsoft.Resources/providers":                            "azure_provider",
	"Microsoft.Network/publicIPAddresses":                      "azure_public_ip",
	"Microsoft.Resources/resourceGroups":                       "azure_resource_group",
	"Microsoft.Security/automations":                           "azure_security_center_automation",
	"Microsoft.Security/subAssessments":                        "azure_security_center_sub_assessment",
	"Microsoft.Storage/blobs":                                  "azure_storage_blob",
	"Microsoft.Storage/blobServives":                           "azure_storage_blob_service",
	"Microsoft.Storage/queues":                                 "azure_storage_queue",
	"Microsoft.Storage/fileShares":                             "azure_storage_share_file",
	"Microsoft.Storage/tables":                                 "azure_storage_table",
	"Microsoft.Storage/tableServices":                          "azure_storage_table_service",
}

var AzureDescriptionMap = map[string]interface{}{
	"Microsoft.CognitiveServices/accounts":                     &keibi.CognitiveAccount{},
	"Microsoft.DataLakeStore/accounts":                         &keibi.DataLakeStore{},
	"Microsoft.Web/sites":                                      &keibi.AppServiceFunctionApp{},
	"Microsoft.Security/securityContacts":                      &keibi.SecurityCenterContact{},
	"Microsoft.Security/settings":                              &keibi.SecurityCenterSetting{},
	"Microsoft.AppConfiguration/configurationStores":           &keibi.AppConfiguration{},
	"Microsoft.Network/virtualNetworks":                        &keibi.VirtualNetwork{},
	"Microsoft.Web/staticSites":                                &keibi.AppServiceWebApp{},
	"Microsoft.Storage/storageAccounts/containers":             &keibi.StorageContainer{},
	"Microsoft.Network/virtualNetworks/subnets":                &keibi.Subnet{},
	"Microsoft.Devices/iotHubs":                                &keibi.IOTHub{},
	"Microsoft.Devices/iotHubDpses":                            &keibi.IOTHubDps{},
	"Microsoft.SignalRService/signalR":                         &keibi.SignalrService{},
	"Microsoft.Storage/storageAccounts":                        &keibi.StorageAccount{},
	"Microsoft.HealthcareApis/services":                        &keibi.HealthcareService{},
	"Microsoft.DataFactory/factories":                          &keibi.DataFactory{},
	"Microsoft.DataFactory/factoriesDatasets":                  &keibi.DataFactoryDataset{},
	"Microsoft.DataFactory/factoriesPipelines":                 &keibi.DataFactoryPipeline{},
	"Microsoft.EventGrid/domains":                              &keibi.EventGridDomain{},
	"Microsoft.EventGrid/domains/topics":                       &keibi.EventGridTopic{},
	"Microsoft.HybridCompute/machines":                         &keibi.HybridComputeMachine{},
	"Microsoft.ServiceBus/namespaces":                          &keibi.ServicebusNamespace{},
	"Microsoft.ServiceFabric/clusters":                         &keibi.ServiceFabricCluster{},
	"Microsoft.Sql/managedInstances":                           &keibi.MssqlManagedInstance{},
	"Microsoft.KeyVault/managedHsms":                           &keibi.KeyVaultManagedHardwareSecurityModule{},
	"Microsoft.StorageSync/storageSyncServices":                &keibi.StorageSync{},
	"Microsoft.DocumentDB/databaseAccounts":                    &keibi.CosmosdbAccount{},
	"Microsoft.DocumentDB/databaseAccountsSqlDatabases":        &keibi.CosmosdbSqlDatabase{},
	"Microsoft.DocumentDB/databaseAccountsMongoDatabases":      &keibi.CosmosdbMongoDatabase{},
	"Microsoft.Network/frontDoors":                             &keibi.Frontdoor{},
	"Microsoft.Kusto/clusters":                                 &keibi.KustoCluster{},
	"Microsoft.Resources/subscriptions/locations":              &keibi.Location{},
	"Microsoft.Web/hostingEnvironments":                        &keibi.AppServiceEnvironment{},
	"Microsoft.DataBoxEdge/dataBoxEdgeDevices":                 &keibi.DataboxEdgeDevice{},
	"Microsoft.Batch/batchAccounts":                            &keibi.BatchAccount{},
	"Microsoft.Insights/activityLogAlerts":                     &keibi.LogAlert{},
	"Microsoft.Compute/virtualMachines":                        &keibi.ComputeVirtualMachine{},
	"Microsoft.Search/searchServices":                          &keibi.SearchService{},
	"Microsoft.AppPlatform/Spring":                             &keibi.SpringCloudService{},
	"Microsoft.Resources/subscriptions":                        &keibi.Subscription{},
	"Microsoft.Compute/diskAccesses":                           &keibi.ComputeDiskAccess{},
	"Microsoft.ContainerRegistry/registries":                   &keibi.ContainerRegistry{},
	"Microsoft.DBforPostgreSQL/servers":                        &keibi.PostgresqlServer{},
	"Microsoft.DataLakeAnalytics/accounts":                     &keibi.DataLakeAnalyticsAccount{},
	"Microsoft.KeyVault/vaults/keys":                           &keibi.KeyVaultKey{},
	"Microsoft.Logic/workflows":                                &keibi.LogicAppWorkflow{},
	"Microsoft.Synapse/workspaces":                             &keibi.SynapseWorkspace{},
	"Microsoft.Authorization/roleDefinitions":                  &keibi.RoleDefinition{},
	"Microsoft.DBforMariaDB/servers":                           &keibi.MariadbServer{},
	"Microsoft.ApiManagement/service":                          &keibi.APIManagement{},
	"Microsoft.ContainerService/managedClusters":               &keibi.KubernetesCluster{},
	"Microsoft.EventHub/namespaces":                            &keibi.EventhubNamespace{},
	"Microsoft.Network/networkInterfaces":                      &keibi.NetworkInterface{},
	"Microsoft.MachineLearningServices/workspaces":             &keibi.MachineLearningWorkspace{},
	"Microsoft.Sql/servers":                                    &keibi.SqlServer{},
	"Microsoft.StorageCache/caches":                            &keibi.HpcCache{},
	"Microsoft.Network/networkWatchers":                        &keibi.NetworkWatcher{},
	"Microsoft.Insights/logProfiles":                           &keibi.LogProfile{},
	"Microsoft.EventGrid/topics":                               &keibi.EventGridTopic{},
	"Microsoft.Insights/guestDiagnosticSettings":               &keibi.DiagnosticSetting{},
	"Microsoft.KeyVault/vaults/secrets":                        &keibi.KeyVaultSecret{},
	"Microsoft.DBforMySQL/servers":                             &keibi.MysqlServer{},
	"Microsoft.Security/pricings":                              &keibi.SecurityCenterSubscriptionPricing{},
	"Microsoft.ClassicNetwork/networkSecurityGroups":           &keibi.NetworkSecurityGroup{},
	"Microsoft.Security/autoProvisioningSettings":              &keibi.SecurityCenterAutoProvisioning{},
	"Microsoft.Network/networkWatchers/flowLogs":               &keibi.NetworkWatcherFlowLog{},
	"Microsoft.Sql/servers/databases":                          &keibi.SqlDatabase{},
	"Microsoft.Cache/redis":                                    &keibi.RedisCache{},
	"Microsoft.HDInsight/clusters":                             &keibi.HdinsightCluster{},
	"Microsoft.KeyVault/vaults":                                &keibi.KeyVault{},
	"Microsoft.StreamAnalytics/streamingJobs":                  &keibi.StreamAnalyticsJob{},
	"Microsoft.Resources/links":                                &keibi.ResourceLink{},
	"Microsoft.Compute/virtualMachineScaleSets":                &keibi.ComputeVirtualMachineScaleSet{},
	"Microsoft.Network/applicationGateways":                    &keibi.ApplicationGateway{},
	"Microsoft.Authorization/policyAssignments":                &keibi.PolicyAssignment{},
	"Microsoft.Resources/tenants":                              &keibi.Tenant{},
	"Microsoft.Resources/users":                                &keibi.AdUsers{},
	"Microsoft.Authorization/elevateAccessRoleAssignment":      &keibi.RoleAssignment{},
	"Microsoft.Compute/disks":                                  &keibi.ComputeDisk{},
	"Microsoft.Security/locations/jitNetworkAccessPolicies":    &keibi.SecurityCenterJitNetworkAccessPolicy{},
	"Microsoft.Network/applicationSecurityGroups":              &keibi.NetworkApplicationSecurityGroups{},
	"Microsoft.RecoveryServices/vaults":                        &keibi.RecoveryServicesVault{},
	"Microsoft.Network/azureFirewalls":                         &keibi.NetworkAzureFirewall{},
	"Microsoft.Network/expressRouteCircuits":                   &keibi.ExpressRouteCircuit{},
	"Microsoft.Network/loadBalancers":                          &keibi.LoadBalancer{},
	"Microsoft.Network/routeTables":                            &keibi.RouteTables{},
	"Microsoft.Compute/snapshots":                              &keibi.ComputeSnapshots{},
	"Microsoft.Network/virtualNetworkGateways":                 &keibi.VirtualNetworkGateway{},
	"Microsoft.Compute/availabilitySets":                       &keibi.ComputeAvailabilitySet{},
	"Microsoft.Compute/diskEncryptionSets":                     &keibi.ComputeDiskEncryptionSet{},
	"Microsoft.Kubernetes/connectedClusters":                   &keibi.HybridKubernetesConnectedCluster{},
	"Microsoft.Authorization/policyDefinitions":                &keibi.PolicyDefinition{},
	"Microsoft.CostManagement/CostByResourceType":              &keibi.CostManagementCostByResourceType{},
	"Microsoft.CostManagement/CostBySubscription":              &keibi.CostManagementCostBySubscription{},
	"Microsoft.Compute/image":                                  &keibi.ComputeImage{},
	"Microsoft.Resources/groups":                               &keibi.AdGroup{},
	"Microsoft.Resources/serviceprincipals":                    &keibi.AdServicePrincipal{},
	"Microsoft.Web/plan":                                       &keibi.AppServicePlan{},
	"Microsoft.Compute/disksreadops":                           &keibi.ComputeDiskReadOps{},
	"Microsoft.Compute/disksreadopsdaily":                      &keibi.ComputeDiskReadOpsDaily{},
	"Microsoft.Compute/disksreadopshourly":                     &keibi.ComputeDiskReadOpsHourly{},
	"Microsoft.Compute/diskswriteops":                          &keibi.ComputeDiskWriteOps{},
	"Microsoft.Compute/diskswriteopsdaily":                     &keibi.ComputeDiskWriteOpsDaily{},
	"Microsoft.Compute/diskswriteopshourly":                    &keibi.ComputeDiskWriteOpsHourly{},
	"Microsoft.Compute/resourceSku":                            &keibi.ComputeResourceSKU{},
	"Microsoft.Compute/virtualMachineCpuUtilization":           &keibi.ComputeVirtualMachineCpuUtilization{},
	"Microsoft.Compute/virtualMachineCpuUtilizationDaily":      &keibi.ComputeVirtualMachineCpuUtilizationDaily{},
	"Microsoft.Compute/virtualMachineCpuUtilizationHourly":     &keibi.ComputeVirtualMachineCpuUtilizationHourly{},
	"Microsoft.Compute/virtualMachineScaleSetNetworkInterface": &keibi.ComputeVirtualMachineScaleSetNetworkInterface{},
	"Microsoft.Compute/virtualMachineScaleSetsVm":              &keibi.ComputeVirtualMachineScaleSetVm{},
	"Microsoft.KeyVault/deletedVaults":                         &keibi.KeyVaultDeletedVault{},
	"Microsoft.LoadBalancer/backendAddressPools":               &keibi.LoadBalancerBackendAddressPool{},
	"Microsoft.LoadBalancer/natRules":                          &keibi.LoadBalancerNatRule{},
	"Microsoft.LoadBalancer/outboundRules":                     &keibi.LoadBalancerOutboundRule{},
	"Microsoft.LoadBalancer/probes":                            &keibi.LoadBalancerProbe{},
	"Microsoft.LoadBalancer/rules":                             &keibi.LoadBalancerRule{},
	"Microsoft.Management/groups":                              &keibi.ManagementGroup{},
	"Microsoft.Management/locks":                               &keibi.ManagementLock{},
	"Microsoft.Sql/elasticPools":                               &keibi.SqlServerElasticPool{},
	"Microsoft.Sql/virtualMachines":                            &keibi.SqlServerVirtualMachine{},
	"Microsoft.Sql/flexibleServers":                            &keibi.SqlServerFlexibleServer{},
	"Microsoft.Network/natGateways":                            &keibi.NatGateway{},
	"Microsoft.Resources/providers":                            &keibi.ResourceProvider{},
	"Microsoft.Network/publicIPAddresses":                      &keibi.PublicIPAddress{},
	"Microsoft.Resources/resourceGroups":                       &keibi.ResourceGroup{},
	"Microsoft.Security/automations":                           &keibi.SecurityCenterAutomation{},
	"Microsoft.Security/subAssessments":                        &keibi.SecurityCenterSubAssessment{},
	"Microsoft.Storage/blobs":                                  &keibi.StorageBlob{},
	"Microsoft.Storage/blobServives":                           &keibi.StorageBlobService{},
	"Microsoft.Storage/queues":                                 &keibi.StorageQueue{},
	"Microsoft.Storage/fileShares":                             &keibi.StorageFileShare{},
	"Microsoft.Storage/tables":                                 &keibi.StorageTable{},
	"Microsoft.Storage/tableServices":                          &keibi.StorageTableService{},
}

var AzureADKeys = map[string]struct{}{
	strings.ToLower("Microsoft.Resources/users"):             {},
	strings.ToLower("Microsoft.Resources/groups"):            {},
	strings.ToLower("Microsoft.Resources/serviceprincipals"): {},
}

type SteampipePlugin string

const (
	SteampipePluginAWS     = "aws"
	SteampipePluginAzure   = "azure"
	SteampipePluginAzureAD = "azuread"
	SteampipePluginUnknown = ""
)

func ExtractPlugin(resourceType string) SteampipePlugin {
	resourceType = strings.ToLower(resourceType)
	if strings.HasPrefix(resourceType, "aws::") {
		return SteampipePluginAWS
	} else if strings.HasPrefix(resourceType, "microsoft") {
		if _, ok := AzureADKeys[strings.ToLower(resourceType)]; ok {
			return SteampipePluginAzureAD
		}
		return SteampipePluginAzure
	}
	return SteampipePluginUnknown
}

func ExtractTableName(resourceType string) string {
	resourceType = strings.ToLower(resourceType)
	if strings.HasPrefix(resourceType, "microsoft.") {
		for k, v := range azureMap {
			if resourceType == strings.ToLower(k) {
				return v
			}
		}
	}
	return ""
}

func GetResourceTypeByTableName(tableName string) string {
	tableName = strings.ToLower(tableName)
	for k, v := range azureMap {
		if tableName == strings.ToLower(v) {
			return k
		}
	}
	return ""
}
