package configs

var TablesToResourceTypes = map[string]string{
	"github_actions_artifact":                "Github/Actions/Artifact",
	"github_actions_repository_runner":       "Github/Actions/Repository/Runner",
	"github_actions_repository_secret":       "Github/Actions/Repository/Secret",
	"github_actions_repository_workflow_run": "Github/Actions/Repository/Workflow_run",
	"github_blob":                            "Github/Blob",
	"github_branch":                          "Github/Branch",
	"github_branch_protection":               "Github/Branch/Protection",
	"github_commit":                          "Github/Commit",
	"github_community_profile":               "Github/CommunityProfile",
	"github_gitignore":                       "Github/Gitignore",
	"github_issue_comment":                   "Github/Issue/Comment",
	"github_license":                         "Github/License",
	"github_organization_collaborators":      "Github/Organization/Collaborator",
	"github_organization_dependabot_alert":   "Github/Organization/DependabotAlert",
	"github_organization_external_identity":  "Github/Organization/ExternalIdentity",
	"github_organization_member":             "Github/Organization/Member",
	"github_pull_request":                    "Github/PullRequest",
	"github_repository_collaborator":         "Github/Repository/Collaborator",
	"github_repository_dependabot_alert":     "Github/Repository/DependabotAlert",
	"github_repository_deployment":           "Github/Repository/Deployment",
	"github_repository_environment":          "Github/Repository/Environment",
	"github_repository_ruleset":              "Github/Repository/Ruleset",
	"github_repository_sbom":                 "Github/Repository/SBOM",
	"github_repository_vulnerability_alert":  "Github/Repository/VulnerabilityAlert",
	"github_stargazer":                       "Github/Stargazer",
	"github_tag":                             "Github/Tag",
	"github_team_member":                     "Github/Team/Member",
	"github_team_repository":                 "Github/Team/Repository",
	"github_traffic_view_daily":              "Github/Traffic/View/Daily",
	"github_traffic_view_weekly":             "Github/Traffic/View/Weekly",
	"github_tree":                            "Github/Tree",
	"github_user":                            "GithubUser",
	"github_workflow":                        "GithubWorkflow",
}

var ResourceTypesList = []string{
	"Github/Actions/Artifact",
	"Github/Actions/Repository/Runner",
	"Github/Actions/Repository/Secret",
	"Github/Actions/Repository/Workflow_run",
	"Github/Blob",
	"Github/Branch",
	"Github/Branch/Protection",
	"Github/Commit",
	"Github/CommunityProfile",
	"Github/Gitignore",
	"Github/Issue/Comment",
	"Github/License",
	"Github/Organization/Collaborator",
	"Github/Organization/DependabotAlert",
	"Github/Organization/ExternalIdentity",
	"Github/Organization/Member",
	"Github/PullRequest",
	"Github/Repository/Collaborator",
	"Github/Repository/DependabotAlert",
	"Github/Repository/Deployment",
	"Github/Repository/Environment",
	"Github/Repository/Ruleset",
	"Github/Repository/SBOM",
	"Github/Repository/VulnerabilityAlert",
	"Github/Stargazer",
	"Github/Tag",
	"Github/Team/Member",
	"Github/Team/Repository",
	"Github/Traffic/View/Daily",
	"Github/Traffic/View/Weekly",
	"Github/Tree",
	"GithubUser",
	"GithubWorkflow",
}
