export const REGIONS = {
    global: {
        country: 'Global',
        regionName: 'Global',
        countryCode: 'US',
        id: 23,
    },
    'us-east-2': {
        country: 'United States',
        regionName: 'US East 2 (Ohio)',
        countryCode: 'US',
        id: 23,
        x: '190',
        y: '130',
    },
    'us-east-1': {
        country: 'United States',
        regionName: 'US East 1 (N. Virginia)',
        countryCode: 'US',
        id: 23,
        x: '200',
        y: '140',
    },
    'us-west-1': {
        country: 'United States',
        regionName: 'US West 1 (N. California)',
        countryCode: 'US',
        id: 23,
        x: '88',
        y: '160',
    },
    'us-west-2': {
        country: 'United States',
        regionName: 'US West 2 (Oregon)',
        countryCode: 'US',
        id: 23,
        x: '88',
        y: '155',
    },
    'ap-south-1': {
        country: 'India',
        regionName: 'Asia Pacific (Mumbai)',
        countryCode: 'IN',
        x: '490',
        y: '220',
        id: 104,
    },
    'ap-northeast-3': {
        country: 'Japan',
        regionName: 'Asia Pacific (Osaka)',
        countryCode: 'JP',
        x: '625',
        y: '155',
        id: 107,
    },
    'ap-northeast-2': {
        country: 'South Korea',
        regionName: 'Asia Pacific (Seoul)',
        countryCode: 'KR',
        x: '600',
        y: '155',
        id: 110,
    },
    'ap-southeast-1': {
        country: 'Singapore',
        regionName: 'Asia Pacific (Singapore)',
        countryCode: 'SG',
        x: '555',
        y: '260',
        id: 119,
    },
    'ap-southeast-2': {
        country: 'Australia',
        regionName: 'Asia Pacific (Sydney)',
        countryCode: 'AU',
        x: '660',
        y: '320',
        id: 175,
    },
    'ap-northeast-1': {
        country: 'Japan',
        regionName: 'Asia Pacific (Tokyo)',
        countryCode: 'JP',
        x: '630',
        y: '155',
        id: 107,
    },
    'ca-central-1': {
        country: 'Canada',
        regionName: 'Canada (Central)',
        countryCode: 'CA',
        x: '120',
        y: '100',
        id: '05',
    },
    'eu-central-1': {
        country: 'Germany',
        regionName: 'Europe (Frankfurt)',
        countryCode: 'DE',
        x: '350',
        y: '130',
        id: 142,
    },
    'eu-west-1': {
        country: 'Ireland',
        regionName: 'EU West 1 (Ireland)',
        countryCode: 'IE',
        x: '332',
        y: '125',
        id: 146,
    },
    'eu-west-2': {
        country: 'United Kingdom',
        regionName: 'EU West 2 (London)',
        countryCode: 'GB',
        x: '340.23',
        y: '125.9',
        id: 170,
    },
    'eu-west-3': {
        country: 'France',
        regionName: 'EU West 3 (Paris)',
        countryCode: 'FR',
        x: '350',
        y: '140',
        id: 141,
    },
    'eu-north-1': {
        country: 'Sweden',
        regionName: 'EU North 1 (Stockholm)',
        countryCode: 'SE',
        x: '370',
        y: '100',
        id: 167,
    },
    'sa-east-1': {
        country: 'Brazil',
        regionName: 'SA East 1 (São Paulo)',
        countryCode: 'BR',
        x: '220',
        y: '300',
        id: 27,
    },
    'af-south-1': {
        country: 'South Africa',
        regionName: 'Africa South 1 (Cape Town)',
        countryCode: 'ZA',
        x: '380',
        y: '340',
        id: 80,
    },
    'ap-east-1': {
        country: 'China',
        regionName: 'AP East 1 (Hong Kong)',
        countryCode: 'CH',
        id: 101,
    },
    'ap-southeast-3': {
        country: 'Indonesia',
        regionName: 'AP Southeast 3 (Jakarta)',
        countryCode: 'ID',
        id: 105,
    },
    'eu-south-1': {
        country: 'Italy',
        regionName: 'EU South 1 (Milan)',
        countryCode: 'IT',
        id: 147,
    },
    'me-south-1': {
        country: 'Bahrain',
        regionName: 'Middle East South 1 (Bahrain)',
        countryCode: 'BH',
        id: 190,
    },
    southafricawest: {
        country: 'South Africa',
        regionName: 'South Africa West',
        countryCode: 'ZA',
        id: null,
    },
    australiacentral2: {
        country: 'Australia',
        regionName: 'Australia Central 2',
        countryCode: 'AU',
        id: null,
    },
    koreasouth: {
        country: 'South Korea',
        regionName: 'Korea South',
        countryCode: 'KR',
        id: null,
    },
    francesouth: {
        country: 'France',
        regionName: 'France South',
        countryCode: 'FR',
        id: null,
    },
    germanynorth: {
        country: 'Germany',
        regionName: 'Germany North',
        countryCode: 'DE',
        id: null,
    },
    norwaywest: {
        country: 'Norway',
        regionName: 'Norway West',
        countryCode: 'NO',
        id: null,
    },
    switzerlandwest: {
        country: 'Switzerland',
        regionName: 'Switzerland West',
        countryCode: 'CH',
        id: null,
    },
    uaecentral: {
        country: 'United Arab Emirates',
        regionName: 'UAE Central',
        countryCode: 'UAE',
        id: null,
    },
    brazilsoutheast: {
        country: 'Brazil',
        regionName: 'Brazil Southeast',
        countryCode: 'BR',
        id: null,
    },
    southafricanorth: {
        country: 'South Africa',
        regionName: 'South Africa North',
        countryCode: 'ZA',
        id: null,
    },
    australiacentral: {
        country: 'Australia',
        regionName: 'Australia Central',
        countryCode: 'AU',
        id: null,
    },
    australiaeast: {
        country: 'Australia',
        regionName: 'Australia East',
        countryCode: 'AU',
        id: null,
    },
    australiasoutheast: {
        country: 'Australia',
        regionName: 'Australia Southeast',
        countryCode: 'AU',
        id: null,
    },
    centralindia: {
        country: 'India',
        regionName: 'Central India',
        countryCode: 'IN',
        id: null,
    },
    eastasia: {
        country: 'China',
        regionName: 'East Asia',
        countryCode: 'CH',
        id: null,
    },
    japaneast: {
        country: 'Japan',
        regionName: 'Japan East',
        countryCode: 'JP',
        id: null,
    },
    japanwest: {
        country: 'Japan',
        regionName: 'Japan West',
        countryCode: 'JP',
        id: null,
    },
    koreacentral: {
        country: 'South Korea',
        regionName: 'Korea Central',
        countryCode: 'KR',
        id: null,
    },
    southeastasia: {
        country: 'Singapore',
        regionName: 'Southeast Asia',
        countryCode: 'SG',
        id: null,
    },
    southindia: {
        country: 'India',
        regionName: 'South India',
        countryCode: 'IN',
        id: null,
    },
    westindia: {
        country: 'India',
        regionName: 'West India',
        countryCode: 'IN',
        id: null,
    },
    canadacentral: {
        country: 'Canada',
        regionName: 'Canada Central',
        countryCode: 'CA',
        id: null,
    },
    canadaeast: {
        country: 'Canada',
        regionName: 'Canada East',
        countryCode: 'CA',
        id: null,
    },
    francecentral: {
        country: 'France',
        regionName: 'France Central',
        countryCode: 'FR',
        id: null,
    },
    germanywestcentral: {
        country: 'Germany',
        regionName: 'Germany West Central',
        countryCode: 'DE',
        id: null,
    },
    northeurope: {
        country: 'Ireland',
        regionName: 'North Europe',
        countryCode: 'IE',
        id: null,
    },
    norwayeast: {
        country: 'Norway',
        regionName: 'Norway East',
        countryCode: 'NO',
        id: null,
    },
    swedencentral: {
        country: 'Sweden',
        regionName: 'Sweden Central',
        countryCode: 'SE',
        id: null,
    },
    switzerlandnorth: {
        country: 'Switzerland',
        regionName: 'Switzerland North',
        countryCode: 'CH',
        id: null,
    },
    uksouth: {
        country: 'United Kingdom',
        regionName: 'UK South',
        countryCode: 'GB',
        id: null,
    },
    ukwest: {
        country: 'United Kingdom',
        regionName: 'UK West',
        countryCode: 'GB',
        id: null,
    },
    westeurope: {
        country: 'Netherlands',
        regionName: 'West Europe',
        countryCode: 'NL',
        id: null,
    },
    uaenorth: {
        country: 'United Arab Emirates',
        regionName: 'UAE North',
        countryCode: 'UAE',
        id: null,
    },
    brazilsouth: {
        country: 'Brazil',
        regionName: 'Brazil South',
        countryCode: 'BR',
        id: null,
    },
    centralus: {
        country: 'United States',
        regionName: 'Central US',
        countryCode: 'US',
        id: null,
    },
    eastus: {
        country: 'United States',
        regionName: 'East US',
        countryCode: 'US',
        id: null,
    },
    eastus2: {
        country: 'United States',
        regionName: 'East US 2',
        countryCode: 'US',
        id: null,
    },
    northcentralus: {
        country: 'United States',
        regionName: 'North Central US',
        countryCode: 'US',
        id: null,
    },
    southcentralus: {
        country: 'United States',
        regionName: 'South Central US',
        countryCode: 'US',
        id: null,
    },
    westcentralus: {
        country: 'United States',
        regionName: 'West Central US',
        countryCode: 'US',
        id: null,
    },
    westus: {
        country: 'United States',
        regionName: 'West US',
        countryCode: 'US',
        id: null,
    },
    westus2: {
        country: 'United States',
        regionName: 'West US 2',
        countryCode: 'US',
        id: null,
    },
    westus3: {
        country: 'United States',
        regionName: 'West US 3',
        countryCode: 'US',
        id: null,
    },
}
