@startuml Kaytu_System
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "Web application user or CLI user")

System_Ext(auth0, "Auth0", "")
System(kaytuPlatform, "Kaytu Platform", "")
System(kaytuWorkspaces, "Kaytu Workspaces", "")
System(kaytuDiscovery, "Kaytu Discovery", "")
System_Ext(aws, "AWS", "")
System_Ext(azure, "Azure", "")

Rel(user, kaytuPlatform, "Authentication and authorization\nWorkspace management\nUser management", "")
Rel(user, kaytuWorkspaces, "Onboarding accounts & subscriptions\nViewing dashboards", "")
Rel(kaytuDiscovery, kaytuWorkspaces, "Sends resources", "")
Rel(aws, kaytuDiscovery, "account resources", "")
Rel(azure, kaytuDiscovery,  "subscription resources", "")
Rel(user, auth0, "Authentication", "")
Rel(auth0, kaytuPlatform, "Authentication", "")
@enduml
