// DO NOT EDIT THIS FILE
package terraform

type Mapping struct {
	Name      string
	Steampipe string
	DeepField string
}

var TerraformAttrMap = map[string][]Mapping{
	"AWS::Redshift::Snapshot":            awsRedshiftSnapshot,
	"AWS::AuditManager::Control":         awsAuditmanagerControl,
	"AWS::Glacier::Vault":                awsGlacierVault,
	"AWS::EC2::RouteTable":               awsEc2Routetable,
	"AWS::FMS::Policy":                   awsFmsPolicy,
	"AWS::Inspector::AssessmentTemplate": awsInspectorAssessmenttemplate,
}
