// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/inventory/api/v1/locations/{provider}": {
            "get": {
                "description": "Getting locations by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get locations",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inventory.LocationByProviderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/resource": {
            "post": {
                "description": "Getting resource details by id and resource type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "Get details of a Resource",
                "parameters": [
                    {
                        "description": "Id",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ResourceType",
                        "name": "resourceType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/inventory/api/v1/resources": {
            "post": {
                "description": "Getting all cloud providers resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    },
                    {
                        "description": "Query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetResourcesResponse"
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/resources/aws": {
            "post": {
                "description": "Getting AWS resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get AWS resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    },
                    {
                        "description": "Query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetAWSResourceResponse"
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/resources/aws/csv": {
            "post": {
                "description": "Getting AWS resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get AWS resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    },
                    {
                        "description": "Query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/inventory/api/v1/resources/azure": {
            "post": {
                "description": "Getting Azure resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get Azure resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    },
                    {
                        "description": "Query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetAzureResourceResponse"
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/resources/azure/csv": {
            "post": {
                "description": "Getting Azure resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get Azure resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    },
                    {
                        "description": "Query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/inventory/api/v1/resources/csv": {
            "post": {
                "description": "Getting all resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get all resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    },
                    {
                        "description": "Query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/onboard/api/v1/aws": {
            "post": {
                "description": "Creating AWS source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Create AWS source",
                "parameters": [
                    {
                        "description": "name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "description",
                        "name": "description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "config",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SourceConfigAWS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateSourceResponse"
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/aws/accounts": {
            "get": {
                "description": "If the account is part of an organization and the account has premission to list the accounts, it will return all the accounts in that organization. Otherwise, it will return the single account these credentials belong to.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns the list of available AWS accounts given the credentials.",
                "parameters": [
                    {
                        "description": "AccessKey",
                        "name": "accessKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "SecretKey",
                        "name": "secretKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DiscoverAWSAccountsResponse"
                            }
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/azure": {
            "post": {
                "description": "Creating Azure source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Create Azure source",
                "parameters": [
                    {
                        "description": "name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "description",
                        "name": "description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "config",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SourceConfigAzure"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateSourceResponse"
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/azure/subscriptions": {
            "get": {
                "description": "Returning the list of available Azure subscriptions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns the list of available Azure subscriptions.",
                "parameters": [
                    {
                        "description": "TenantId",
                        "name": "tenantId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ClientId",
                        "name": "clientId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ClientSecret",
                        "name": "clientSecret",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DiscoverAzureSubscriptionsResponse"
                            }
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/providers": {
            "get": {
                "description": "Getting cloud providers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Get providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Provider"
                            }
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/sources": {
            "get": {
                "description": "Returning a list of sources including both AWS and Azure unless filtered by Type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns a list of sources",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source"
                            }
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/{sourceId}": {
            "get": {
                "description": "Returning single source either AWS / Azure.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns a single source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleting a single source either AWS / Azure.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Delete a single source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/schedule/api/v1/resource_type/{provider}": {
            "get": {
                "description": "get resource type by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "get resource type by provider",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/sources": {
            "get": {
                "description": "Getting all of Keibi sources",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "List Sources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_describe_api.Source"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/sources/{source_id}/jobs/compliance": {
            "get": {
                "description": "List source compliance reports",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "List source compliance reports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ComplianceReport"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/sources/{source_id}/jobs/compliance/refresh": {
            "post": {
                "description": "Run compliance report jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Run compliance report jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/schedule/api/v1/sources/{source_id}/jobs/describe": {
            "get": {
                "description": "List source describe jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "List source describe jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DescribeSource"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/sources/{source_id}/jobs/describe/refresh": {
            "post": {
                "description": "Run describe jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Run describe jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/schedule/api/v1/sources/{source_id}/policy/{policy_id}": {
            "get": {
                "description": "Assign source to policy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Assign source to policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "api.ComplianceReport": {
            "type": "object",
            "properties": {
                "failureMessage": {
                    "type": "string"
                },
                "s3ResultUrl": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.CreateSourceResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "api.DescribeResource": {
            "type": "object",
            "properties": {
                "failureMessage": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DescribeSource": {
            "type": "object",
            "properties": {
                "describeResourceJobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.DescribeResource"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DiscoverAWSAccountsResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "description": "Nil if not part of an AWS organization",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DiscoverAzureSubscriptionsResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subscriptionId": {
                    "type": "string"
                }
            }
        },
        "api.Provider": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.SourceConfigAWS": {
            "type": "object",
            "required": [
                "accessKey",
                "accountId",
                "secretKey"
            ],
            "properties": {
                "accessKey": {
                    "type": "string"
                },
                "accountId": {
                    "type": "string"
                },
                "regions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "secretKey": {
                    "type": "string"
                }
            }
        },
        "api.SourceConfigAzure": {
            "type": "object",
            "required": [
                "clientId",
                "clientSecret",
                "subscriptionId",
                "tenantId"
            ],
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "clientSecret": {
                    "type": "string"
                },
                "subscriptionId": {
                    "type": "string"
                },
                "tenantId": {
                    "type": "string"
                }
            }
        },
        "gitlab.com_keibiengine_keibi-engine_pkg_describe_api.Source": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "lastComplianceReportAt": {
                    "type": "string"
                },
                "lastDescribedAt": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sourceId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "inventory.AWSResource": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                }
            }
        },
        "inventory.AllResource": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "sourceID": {
                    "type": "string"
                }
            }
        },
        "inventory.AzureResource": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceGroup": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "subscriptionID": {
                    "type": "string"
                }
            }
        },
        "inventory.Filters": {
            "type": "object",
            "properties": {
                "keibiSource": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resourceType": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "inventory.GetAWSResourceResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AWSResource"
                    }
                }
            }
        },
        "inventory.GetAzureResourceResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AzureResource"
                    }
                }
            }
        },
        "inventory.GetResourcesResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AllResource"
                    }
                }
            }
        },
        "inventory.LocationByProviderResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "inventory.Page": {
            "type": "object",
            "properties": {
                "nextMarker": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "inventory.Sort": {
            "type": "object",
            "properties": {
                "sortBy": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.SortItem"
                    }
                }
            }
        },
        "inventory.SortItem": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string",
                    "enum": [
                        "asc",
                        "desc"
                    ]
                },
                "field": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "dev-cluster.keibi.io",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "Keibi Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
