// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aws": {
            "post": {
                "description": "Creating AWS source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Create AWS source",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateSourceResponse"
                        }
                    }
                }
            }
        },
        "/aws/accounts": {
            "get": {
                "description": "If the account is part of an organization and the account has premission to list the accounts, it will return all the accounts in that organization. Otherwise, it will return the single account these credentials belong to.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns the list of available AWS accounts given the credentials.",
                "parameters": [
                    {
                        "description": "AccessKey",
                        "name": "accessKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "SecretKey",
                        "name": "secretKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DiscoverAWSAccountsResponse"
                            }
                        }
                    }
                }
            }
        },
        "/azure": {
            "post": {
                "description": "Creating Azure source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Create Azure source",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateSourceResponse"
                        }
                    }
                }
            }
        },
        "/azure/subscriptions": {
            "get": {
                "description": "Returning the list of available Azure subscriptions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns the list of available Azure subscriptions.",
                "parameters": [
                    {
                        "description": "TenantId",
                        "name": "tenantId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ClientId",
                        "name": "clientId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ClientSecret",
                        "name": "clientSecret",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DiscoverAzureSubscriptionsResponse"
                            }
                        }
                    }
                }
            }
        },
        "/locations/{provider}": {
            "get": {
                "description": "Getting locations by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get locations",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inventory.LocationByProviderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/providers": {
            "get": {
                "description": "Getting cloud providers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Get providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Provider"
                            }
                        }
                    }
                }
            }
        },
        "/resource": {
            "post": {
                "description": "Getting resource details by id and resource type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "Get details of a Resource",
                "parameters": [
                    {
                        "description": "Id",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ResourceType",
                        "name": "resourceType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/resource_type/{provider}": {
            "get": {
                "description": "get resource type by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "get resource type by provider",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/resources": {
            "post": {
                "description": "Getting all cloud providers resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetResourcesResponse"
                        }
                    }
                }
            }
        },
        "/resources/aws": {
            "post": {
                "description": "Getting AWS resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get AWS resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetAWSResourceResponse"
                        }
                    }
                }
            }
        },
        "/resources/aws/csv": {
            "post": {
                "description": "Getting AWS resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get AWS resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/resources/azure": {
            "post": {
                "description": "Getting Azure resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get Azure resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetAzureResourceResponse"
                        }
                    }
                }
            }
        },
        "/resources/azure/csv": {
            "post": {
                "description": "Getting Azure resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get Azure resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/resources/csv": {
            "post": {
                "description": "Getting all resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get all resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/sources": {
            "get": {
                "description": "Returning a list of sources including both AWS and Azure unless filtered by Type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns a list of sources",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Source"
                            }
                        }
                    }
                }
            }
        },
        "/sources/{source_id}/jobs/compliance": {
            "get": {
                "description": "List source compliance reports",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "List source compliance reports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/describe.ApiComplianceReport"
                            }
                        }
                    }
                }
            }
        },
        "/sources/{source_id}/jobs/compliance/refresh": {
            "get": {
                "description": "Run compliance report jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "Run compliance report jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/sources/{source_id}/jobs/describe": {
            "get": {
                "description": "List source describe jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "List source describe jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/describe.ApiDescribeSource"
                            }
                        }
                    }
                }
            }
        },
        "/sources/{source_id}/jobs/describe/refresh": {
            "get": {
                "description": "Run describe jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "Run describe jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/sources/{source_id}/policy/{policy_id}": {
            "get": {
                "description": "Assign source to policy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "source"
                ],
                "summary": "Assign source to policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/{sourceId}": {
            "get": {
                "description": "Returning single source either AWS / Azure.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns a single source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Source"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleting a single source either AWS / Azure.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Delete a single source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateSourceResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "api.DiscoverAWSAccountsResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "description": "Nil if not part of an AWS organization",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DiscoverAzureSubscriptionsResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subscriptionId": {
                    "type": "string"
                }
            }
        },
        "api.Provider": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.Source": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sourceId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "describe.ApiComplianceReport": {
            "type": "object",
            "properties": {
                "failure_message": {
                    "type": "string"
                },
                "s3_result_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "describe.ApiDescribeResource": {
            "type": "object",
            "properties": {
                "failure_message": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "describe.ApiDescribeSource": {
            "type": "object",
            "properties": {
                "describe_resource_jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/describe.ApiDescribeResource"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "describe.ApiSource": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "last_compliance_report_at": {
                    "type": "string"
                },
                "last_described_at": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "inventory.AWSResource": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                }
            }
        },
        "inventory.AllResource": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "sourceID": {
                    "type": "string"
                }
            }
        },
        "inventory.AzureResource": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceGroup": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "subscriptionID": {
                    "type": "string"
                }
            }
        },
        "inventory.Filters": {
            "type": "object",
            "properties": {
                "keibiSource": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resourceType": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "inventory.GetAWSResourceResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AWSResource"
                    }
                }
            }
        },
        "inventory.GetAzureResourceResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AzureResource"
                    }
                }
            }
        },
        "inventory.GetResourcesResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AllResource"
                    }
                }
            }
        },
        "inventory.LocationByProviderResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "inventory.Page": {
            "type": "object",
            "properties": {
                "nextMarker": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "inventory.Sort": {
            "type": "object",
            "properties": {
                "sortBy": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.SortItem"
                    }
                }
            }
        },
        "inventory.SortItem": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string",
                    "enum": [
                        "asc",
                        "desc"
                    ]
                },
                "field": {
                    "type": "string"
                }
            }
        }
    }
}`
