// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/api/v1/role/binding": {
            "get": {
                "description": "RoleBinding defines the roles and actions a user can perform. There are currently three roles (ADMIN, EDITOR, VIEWER).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get RoleBinding for a single user.",
                "parameters": [
                    {
                        "description": "userId",
                        "name": "userId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetRoleBindingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/api/v1/role/bindings": {
            "get": {
                "description": "RoleBinding defines the roles and actions a user can perform. There are currently three roles (ADMIN, EDITOR, VIEWER).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get RoleBinding for all users.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.RoleBinding"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "RoleBinding defines the roles and actions a user can perform. There are currently three roles (ADMIN, EDITOR, VIEWER). User must exist before you can update its RoleBinding",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Update RoleBinding for a user.",
                "parameters": [
                    {
                        "description": "userId",
                        "name": "userId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "role",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/benchmarks": {
            "get": {
                "description": "In order to filter benchmarks by tags provide the tag key-value as query param",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns list of benchmarks",
                "parameters": [
                    {
                        "enum": [
                            "AWS",
                            "Azure"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tags in key-value query param",
                        "name": "tags",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Benchmark"
                            }
                        }
                    }
                }
            }
        },
        "/benchmarks/history/list/{provider}/{createdAt}": {
            "get": {
                "description": "You should fetch the benchmark report times from /benchmarks/history/:year/:month/:day",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns all benchmark existed at the specified time",
                "parameters": [
                    {
                        "enum": [
                            "AWS",
                            "Azure",
                            "All"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CreatedAt",
                        "name": "createdAt",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Benchmark"
                            }
                        }
                    }
                }
            }
        },
        "/benchmarks/tags": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns list of benchmark tags",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.GetBenchmarkTag"
                            }
                        }
                    }
                }
            }
        },
        "/benchmarks/{benchmarkId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns details of a given benchmark",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BenchmarkID",
                        "name": "benchmarkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetBenchmarkDetailsResponse"
                        }
                    }
                }
            }
        },
        "/benchmarks/{benchmarkId}/policies": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns list of policies of a given benchmark",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BenchmarkID",
                        "name": "benchmarkId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category Filter",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Subcategory Filter",
                        "name": "subcategory",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Section Filter",
                        "name": "section",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Policy"
                            }
                        }
                    }
                }
            }
        },
        "/benchmarks/{benchmarkId}/{createdAt}/accounts": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns list of accounts compliance scores ordered by compliance ratio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BenchmarkID",
                        "name": "benchmarkId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CreatedAt",
                        "name": "createdAt",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Order",
                        "name": "order",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BenchmarkAccountComplianceResponse"
                        }
                    }
                }
            }
        },
        "/benchmarks/{benchmarkId}/{createdAt}/accounts/compliance": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns no of compliant \u0026 non-compliant accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BenchmarkID",
                        "name": "benchmarkId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CreatedAt",
                        "name": "createdAt",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BenchmarkAccountComplianceResponse"
                        }
                    }
                }
            }
        },
        "/benchmarks/{benchmarkId}/{sourceId}/compliance/trend": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns trend of a benchmark compliance for specific account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BenchmarkID",
                        "name": "benchmarkId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "24h",
                            "1w",
                            "3m",
                            "1y",
                            "max"
                        ],
                        "type": "string",
                        "description": "Time Window",
                        "name": "timeWindow",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.TrendDataPoint"
                            }
                        }
                    }
                }
            }
        },
        "/benchmarks/{benchmarkId}/{sourceId}/result": {
            "get": {
                "description": "Returns summary of benchmark, category, subcategory or section's result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns summary of benchmark result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of Benchmark/Category/Subcategory/Section",
                        "name": "benchmarkId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/compliance_report.ReportGroupObj"
                        }
                    }
                }
            }
        },
        "/benchmarks/{benchmarkId}/{sourceId}/result/policies": {
            "get": {
                "description": "Returns policy results of specific benchmark",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "benchmarks"
                ],
                "summary": "Returns policy results of specific benchmark",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of Benchmark/Category/Subcategory/Section",
                        "name": "benchmarkId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category Filter",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Subcategory Filter",
                        "name": "subcategory",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Section Filter",
                        "name": "section",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Severity Filter",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "passed",
                            "failed"
                        ],
                        "type": "string",
                        "description": "Status Filter",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.PolicyResult"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/locations/{provider}": {
            "get": {
                "description": "Getting locations by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get locations",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.LocationByProviderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/query": {
            "get": {
                "description": "Listing smart queries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "smart_query"
                ],
                "summary": "List smart queries",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ListQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.SmartQueryItem"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/query/count": {
            "get": {
                "description": "Counting smart queries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "smart_query"
                ],
                "summary": "Count smart queries",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ListQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/query/{queryId}": {
            "post": {
                "description": "Run a specific smart query.\nIn order to get the results in CSV format, Accepts header must be filled with ` + "`" + `text/csv` + "`" + ` value.\nNote that csv output doesn't process pagination and returns first 5000 records.",
                "produces": [
                    "application/json",
                    "text/csv"
                ],
                "tags": [
                    "smart_query"
                ],
                "summary": "Run a specific smart query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "QueryID",
                        "name": "queryId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RunQueryRequest"
                        }
                    },
                    {
                        "enum": [
                            "application/json",
                            "text/csv"
                        ],
                        "type": "string",
                        "description": "Accept header",
                        "name": "accept",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RunQueryResponse"
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/reports/compliance/{source_id}": {
            "get": {
                "description": "Returns list of compliance report groups of specified job id (if not specified, last one will be returned)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance_report"
                ],
                "summary": "Returns list of compliance report groups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Report Job ID",
                        "name": "report_id",
                        "in": "path"
                    },
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetComplianceReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/compliance_report.Report"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/reports/compliance/{source_id}/{report_id}": {
            "get": {
                "description": "Returns list of compliance report groups of specified job id (if not specified, last one will be returned)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance_report"
                ],
                "summary": "Returns list of compliance report groups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Report Job ID",
                        "name": "report_id",
                        "in": "path"
                    },
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetComplianceReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/compliance_report.Report"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/resource": {
            "post": {
                "description": "Getting resource details by id and resource type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "Get details of a Resource",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetResourceRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/inventory/api/v1/resources": {
            "post": {
                "description": "Getting all cloud providers resources by filters.\nIn order to get the results in CSV format, Accepts header must be filled with ` + "`" + `text/csv` + "`" + ` value.\nNote that csv output doesn't process pagination and returns first 5000 records.\nIf sort by is empty, result will be sorted by the first column in ascending order.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/csv"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get resources",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetResourcesRequest"
                        }
                    },
                    {
                        "enum": [
                            "application/json",
                            "text/csv"
                        ],
                        "type": "string",
                        "description": "Accept header",
                        "name": "accept",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetResourcesResponse"
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/resources/aws": {
            "post": {
                "description": "Getting AWS resources by filters.\nIn order to get the results in CSV format, Accepts header must be filled with ` + "`" + `text/csv` + "`" + ` value.\nNote that csv output doesn't process pagination and returns first 5000 records.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/csv"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get AWS resources",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetResourcesRequest"
                        }
                    },
                    {
                        "enum": [
                            "application/json",
                            "text/csv"
                        ],
                        "type": "string",
                        "description": "Accept header",
                        "name": "accept",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetAWSResourceResponse"
                        }
                    }
                }
            }
        },
        "/inventory/api/v1/resources/azure": {
            "post": {
                "description": "Getting Azure resources by filters.\nIn order to get the results in CSV format, Accepts header must be filled with ` + "`" + `text/csv` + "`" + ` value.\nNote that csv output doesn't process pagination and returns first 5000 records.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/csv"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get Azure resources",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetResourcesRequest"
                        }
                    },
                    {
                        "enum": [
                            "application/json",
                            "text/csv"
                        ],
                        "type": "string",
                        "description": "Accept header",
                        "name": "accept",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetAzureResourceResponse"
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/discover/aws/accounts": {
            "post": {
                "description": "If the account is part of an organization and the account has premission to list the accounts, it will return all the accounts in that organization. Otherwise, it will return the single account these credentials belong to.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns the list of available AWS accounts given the credentials.",
                "parameters": [
                    {
                        "description": "AccessKey",
                        "name": "accessKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "SecretKey",
                        "name": "secretKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DiscoverAWSAccountsResponse"
                            }
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/discover/azure/subscriptions": {
            "post": {
                "description": "Returning the list of available Azure subscriptions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns the list of available Azure subscriptions.",
                "parameters": [
                    {
                        "description": "TenantId",
                        "name": "tenantId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ClientId",
                        "name": "clientId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ClientSecret",
                        "name": "clientSecret",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DiscoverAzureSubscriptionsResponse"
                            }
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/providers": {
            "get": {
                "description": "Getting cloud providers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Get providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Provider"
                            }
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/providers/types": {
            "get": {
                "description": "Getting provider types",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Get provider types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ProviderType"
                            }
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/source/aws": {
            "post": {
                "description": "Creating AWS source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Create AWS source",
                "parameters": [
                    {
                        "description": "name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "description",
                        "name": "description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "config",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SourceConfigAWS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateSourceResponse"
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/source/azure": {
            "post": {
                "description": "Creating Azure source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Create Azure source",
                "parameters": [
                    {
                        "description": "name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "description",
                        "name": "description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "config",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SourceConfigAzure"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateSourceResponse"
                        }
                    }
                }
            }
        },
        "/onboard/api/v1/source/{sourceId}": {
            "get": {
                "description": "Returning single source either AWS / Azure.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns a single source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleting a single source either AWS / Azure.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Delete a single source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SourceID",
                        "name": "sourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/onboard/api/v1/sources": {
            "get": {
                "description": "Returning a list of sources including both AWS and Azure unless filtered by Type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboard"
                ],
                "summary": "Returns a list of sources",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/resource_type/{provider}": {
            "get": {
                "description": "get resource type by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "get resource type by provider",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/sources": {
            "get": {
                "description": "Getting all of Keibi sources",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "List Sources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_describe_api.Source"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/sources/{source_id}/jobs/compliance": {
            "get": {
                "description": "List source compliance reports",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "List source compliance reports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "From Time (TimeRange)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "To Time (TimeRange)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ComplianceReport"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/sources/{source_id}/jobs/compliance/refresh": {
            "post": {
                "description": "Run compliance report jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Run compliance report jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/schedule/api/v1/sources/{source_id}/jobs/describe": {
            "get": {
                "description": "List source describe jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "List source describe jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DescribeSource"
                            }
                        }
                    }
                }
            }
        },
        "/schedule/api/v1/sources/{source_id}/jobs/describe/refresh": {
            "post": {
                "description": "Run describe jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Run describe jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/schedule/api/v1/sources/{source_id}/policy/{policy_id}": {
            "get": {
                "description": "Assign source to policy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Assign source to policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourceID",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "api.AWSResource": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "string"
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                }
            }
        },
        "api.AllResource": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "sourceID": {
                    "type": "string"
                }
            }
        },
        "api.AzureResource": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceGroup": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "subscriptionID": {
                    "type": "string"
                }
            }
        },
        "api.Benchmark": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.BenchmarkAccountComplianceResponse": {
            "type": "object",
            "properties": {
                "totalCompliantAccounts": {
                    "type": "integer"
                },
                "totalNonCompliantAccounts": {
                    "type": "integer"
                }
            }
        },
        "api.ComplianceReport": {
            "type": "object",
            "properties": {
                "failureMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reportCreatedAt": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "api.ComplianceReportFilters": {
            "type": "object",
            "properties": {
                "groupID": {
                    "description": "benchmark id or control id",
                    "type": "string"
                },
                "timeRange": {
                    "$ref": "#/definitions/api.TimeRangeFilter"
                }
            }
        },
        "api.CreateSourceResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "api.DescribeResource": {
            "type": "object",
            "properties": {
                "failureMessage": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DescribeSource": {
            "type": "object",
            "properties": {
                "describeResourceJobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.DescribeResource"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DiscoverAWSAccountsResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "description": "Nil if not part of an AWS organization",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DiscoverAzureSubscriptionsResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subscriptionId": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "api.Filters": {
            "description": "if you provide two values for same filter OR operation would be used if you provide value for two filters AND operation would be used",
            "type": "object",
            "properties": {
                "location": {
                    "description": "if you dont need to use this filter, leave them empty. (e.g. [])",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resourceType": {
                    "description": "if you dont need to use this filter, leave them empty. (e.g. [])",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sourceID": {
                    "description": "if you dont need to use this filter, leave them empty. (e.g. [])",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.GetAWSResourceResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/api.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.AWSResource"
                    }
                }
            }
        },
        "api.GetAzureResourceResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/api.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.AzureResource"
                    }
                }
            }
        },
        "api.GetBenchmarkDetailsResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subcategories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.GetBenchmarkTag": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "api.GetComplianceReportRequest": {
            "type": "object",
            "required": [
                "page"
            ],
            "properties": {
                "filters": {
                    "$ref": "#/definitions/api.ComplianceReportFilters"
                },
                "page": {
                    "$ref": "#/definitions/api.Page"
                },
                "reportType": {
                    "type": "string",
                    "enum": [
                        "benchmark",
                        "control",
                        "result"
                    ]
                }
            }
        },
        "api.GetResourceRequest": {
            "type": "object",
            "required": [
                "ID",
                "resourceType"
            ],
            "properties": {
                "ID": {
                    "description": "Resource ID",
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                }
            }
        },
        "api.GetResourcesRequest": {
            "type": "object",
            "required": [
                "filters",
                "page"
            ],
            "properties": {
                "filters": {
                    "description": "search filters",
                    "$ref": "#/definitions/api.Filters"
                },
                "page": {
                    "$ref": "#/definitions/api.Page"
                },
                "query": {
                    "description": "search query",
                    "type": "string"
                },
                "sorts": {
                    "description": "NOTE: we don't support multi-field sort for now, if sort is empty, results would be sorted by first column",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ResourceSortItem"
                    }
                }
            }
        },
        "api.GetResourcesResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/api.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.AllResource"
                    }
                }
            }
        },
        "api.GetRoleBindingResponse": {
            "type": "object",
            "properties": {
                "assignedAt": {
                    "type": "string"
                },
                "emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "api.ListQueryRequest": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "providerFilter": {
                    "type": "string"
                },
                "titleFilter": {
                    "type": "string"
                }
            }
        },
        "api.LocationByProviderResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "api.Page": {
            "type": "object",
            "required": [
                "size"
            ],
            "properties": {
                "nextMarker": {
                    "description": "fill it with empty for the first request",
                    "type": "string"
                },
                "size": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "api.Policy": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "commandLineRemedation": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "manualRemedation": {
                    "type": "string"
                },
                "manualVerification": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "queryToRun": {
                    "type": "string"
                },
                "section": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "subcategory": {
                    "type": "string"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.PolicyResult": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "compliantResources": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "section": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "passed",
                        "failed"
                    ]
                },
                "subcategory": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalResources": {
                    "type": "integer"
                }
            }
        },
        "api.Provider": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.ProviderType": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "state": {
                    "type": "string",
                    "enum": [
                        "enabled",
                        "coming_soon",
                        "disabled"
                    ]
                },
                "typeName": {
                    "type": "string"
                }
            }
        },
        "api.ResourceSortItem": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string",
                    "enum": [
                        "asc",
                        "desc"
                    ]
                },
                "field": {
                    "type": "string",
                    "enum": [
                        "resource_id",
                        "name",
                        "source_type",
                        "resource_type",
                        "resource_group",
                        "location",
                        "source_id"
                    ]
                }
            }
        },
        "api.RoleBinding": {
            "type": "object",
            "properties": {
                "assignedAt": {
                    "type": "string"
                },
                "emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "api.RunQueryRequest": {
            "type": "object",
            "required": [
                "page"
            ],
            "properties": {
                "page": {
                    "$ref": "#/definitions/api.Page"
                },
                "sorts": {
                    "description": "NOTE: we don't support multi-field sort for now, if sort is empty, results would be sorted by first column",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SmartQuerySortItem"
                    }
                }
            }
        },
        "api.RunQueryResponse": {
            "type": "object",
            "properties": {
                "headers": {
                    "description": "column names",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "page": {
                    "$ref": "#/definitions/api.Page"
                },
                "result": {
                    "description": "result of query. in order to access a specific cell please use Result[Row][Column]",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {}
                    }
                }
            }
        },
        "api.SmartQueryItem": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "provider": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.SmartQuerySortItem": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string",
                    "enum": [
                        "asc",
                        "desc"
                    ]
                },
                "field": {
                    "description": "fill this with column name",
                    "type": "string"
                }
            }
        },
        "api.SourceConfigAWS": {
            "type": "object",
            "required": [
                "accessKey",
                "accountId",
                "secretKey"
            ],
            "properties": {
                "accessKey": {
                    "type": "string"
                },
                "accountId": {
                    "type": "string"
                },
                "regions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "secretKey": {
                    "type": "string"
                }
            }
        },
        "api.SourceConfigAzure": {
            "type": "object",
            "required": [
                "clientId",
                "clientSecret",
                "subscriptionId",
                "tenantId"
            ],
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "clientSecret": {
                    "type": "string"
                },
                "subscriptionId": {
                    "type": "string"
                },
                "tenantId": {
                    "type": "string"
                }
            }
        },
        "api.TimeRangeFilter": {
            "type": "object",
            "properties": {
                "from": {
                    "description": "from epoch millisecond",
                    "type": "integer"
                },
                "to": {
                    "description": "from epoch millisecond",
                    "type": "integer"
                }
            }
        },
        "api.TrendDataPoint": {
            "type": "object",
            "properties": {
                "compliant": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "integer"
                },
                "totalResources": {
                    "type": "integer"
                }
            }
        },
        "compliance_report.Dimension": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "compliance_report.Report": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "integer"
                },
                "group": {
                    "$ref": "#/definitions/compliance_report.ReportGroupObj"
                },
                "provider": {
                    "type": "string"
                },
                "reportJobID": {
                    "type": "integer"
                },
                "result": {
                    "$ref": "#/definitions/compliance_report.ReportResultObj"
                },
                "sourceID": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "compliance_report.ReportGroupObj": {
            "type": "object",
            "properties": {
                "controlIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "groupIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "benchmark id / control id",
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "parentGroupIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/compliance_report.Summary"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "compliance_report.ReportResultObj": {
            "type": "object",
            "properties": {
                "controlId": {
                    "type": "string"
                },
                "parentGroupIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "result": {
                    "$ref": "#/definitions/compliance_report.Result"
                }
            }
        },
        "compliance_report.Result": {
            "type": "object",
            "properties": {
                "dimensions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/compliance_report.Dimension"
                    }
                },
                "reason": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "info",
                        "skip",
                        "alarm",
                        "error"
                    ]
                }
            }
        },
        "compliance_report.Summary": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/compliance_report.SummaryStatus"
                }
            }
        },
        "compliance_report.SummaryStatus": {
            "type": "object",
            "properties": {
                "alarm": {
                    "type": "integer"
                },
                "error": {
                    "type": "integer"
                },
                "info": {
                    "type": "integer"
                },
                "ok": {
                    "type": "integer"
                },
                "skip": {
                    "type": "integer"
                }
            }
        },
        "gitlab.com_keibiengine_keibi-engine_pkg_describe_api.Source": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "lastComplianceReportAt": {
                    "type": "string"
                },
                "lastDescribedAt": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sourceId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "dev-cluster.keibi.io",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "Keibi Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
