export { default as AzureIcon } from './AzureIcon.png'
export { default as AWSIcon } from './AWSIcon.png'
export { default as AssistantImage } from './AssistantImage.png'
export { default as AWSAzureIcon } from './AWSAzureIcon.png'
export { default as EntraIDIcon } from './EntraIDIcon.png'

export { ReactComponent as CisIcon } from './cis.svg'
export { ReactComponent as HipaaIcon } from './hipaa.svg'

export { ReactComponent as OpenGovernance } from './OpenGovernanceSmall.svg'
export { ReactComponent as OpenGovernanceBig } from './OpenGovernance.svg'
export { ReactComponent as KaytuDarkIconBig } from './kaytu.svg'

export { ReactComponent as BarChartIcon } from './barChart.svg'
export { ReactComponent as AreaChartIcon } from './areaChart.svg'
export { ReactComponent as LineChartIcon } from './lineChart.svg'

export { ReactComponent as BulletList } from './Iconly/BulletList.svg'
export { ReactComponent as Clock } from './Iconly/Clock.svg'
export { ReactComponent as CloudConnect } from './Iconly/CloudConnect.svg'
export { ReactComponent as Compliance } from './Iconly/Compliance.svg'
export { ReactComponent as Control } from './Iconly/Control.svg'
export { ReactComponent as Id } from './Iconly/Id.svg'
export { ReactComponent as Lifecycle } from './Iconly/Lifecycle.svg'
export { ReactComponent as Refresh } from './Iconly/Refresh.svg'
export { ReactComponent as Resources } from './Iconly/Resources.svg'
export { ReactComponent as SeverityIcon } from './Iconly/Severity.svg'
export { ReactComponent as Sort } from './Iconly/Sort.svg'
export { ReactComponent as Speed } from './Iconly/Speed.svg'
export { ReactComponent as ArrowDownFill } from './Iconly/Arrow-Down-Fill.svg'
export { ReactComponent as ArrowUpFill } from './Iconly/Arrow-Up-Fill.svg'
export { ReactComponent as ArrowLeftFill } from './Iconly/Arrow-Left-Fill.svg'
export { ReactComponent as ArrowRightFill } from './Iconly/Arrow-Right-Fill.svg'
export { ReactComponent as AssistantProfileIcon } from './assistant-profile-icon.svg'
export { ReactComponent as TagIcon } from './Iconly/Tag.svg'
export { ReactComponent as DocumentBadge } from './Iconly/Document-Badge.svg'
