@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    ContainerDb(workspacePostgres, "Database", "PostgreSQL", "Holds workspaces and authorization information")
    Container(onboardService, "Onboard service", "Go", "")
    Container(complianceService, "Compliance service", "Go", "")

    Container(alertingService, "Alerting service", "Go", "")
    Rel(alertingService, workspacePostgres, "")
    Rel(alertingService, onboardService, "")
    Rel(alertingService, complianceService, "")
}

@enduml