@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    ContainerDb(workspacePostgres, "Database", "PostgreSQL", "Holds workspaces and authorization information")
    ContainerDb(elastic, "Database", "ElasticSearch", "Holds workspaces and authorization information")
    ContainerDb(kafka, "Database", "Kafka", "Holds workspaces and authorization information")
    ContainerDb(rabbitMQ, "Database", "RabbitMQ", "Holds workspaces and authorization information")
    Container(onboardService, "Onboard service", "Go", "")
    Container(inventoryService, "Inventory service", "Go", "")
    Container(schedulerService, "Scheduler service", "Go", "")
    
    Container(analyticsWorkers, "Analytics workers", "Go", "")
    Rel(analyticsWorkers, elastic, "")
    Rel(analyticsWorkers, workspacePostgres, "")
    Rel(rabbitMQ, analyticsWorkers, "")
    Rel(analyticsWorkers, kafka, "")
    Rel(analyticsWorkers, onboardService, "")
    Rel(analyticsWorkers, schedulerService, "")
    Rel(analyticsWorkers, inventoryService, "")
}

@enduml