@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    ContainerDb(rabbitMQ, "Database", "RabbitMQ", "Holds workspaces and authorization information")
    Container(onboardService, "Onboard service", "Go", "")

    Container(checkupWorkers, "Checkup workers", "Go", "")
    Rel(rabbitMQ, checkupWorkers, "")
    Rel(checkupWorkers, onboardService, "")
}

@enduml