@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    ContainerDb(workspacePostgres, "Database", "PostgreSQL", "Holds metadatas")

    Container(metadataService, "Metadata service", "Go", "")
    Rel(metadataService, workspacePostgres, "")
}

Rel(user, metadataService, "use API", "HTTPS")
@enduml