@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Ext(github, "Github")

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    ContainerDb(workspacePostgres, "Database", "PostgreSQL", "Holds workspaces and authorization information")
    ContainerDb(elastic, "Database", "ElasticSearch", "Holds workspaces and authorization information")

    Container(migratorWorkers, "Migrator workers", "Go", "")
    Rel(migratorWorkers, elastic, "")
    Rel(migratorWorkers, workspacePostgres, "")
    Rel(migratorWorkers, github, "")
}

@enduml