@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")

System_Ext(awsKMS, "AWS KMS")
System_Ext(awsSystem, "AWS", "")

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    ContainerDb(workspacePostgres, "Database", "PostgreSQL", "Holds workspaces information")
    ContainerQueue(rabbitMQ, "Database", "RabbitMQ", "queue for source deletion events")

    Container(schedulerService, "Scheduler service", "Go", "Handles scheduling of jobs and processing results of them")
    Container(inventoryService, "Inventory service", "Go", "Holds inventory data")

    ContainerDb(elastic, "Database", "ElasticSearch", "Holds inventory information")
    Container(steampipeService, "Steampipe service", "Go", "Runs queries on ElasticSearch")
    Rel(steampipeService, elastic, "")

    Container(onboardService, "Onboard service", "Go", "")
    Rel(onboardService, rabbitMQ, "")
    Rel(onboardService, workspacePostgres, "")
    Rel(onboardService, steampipeService, "")
    Rel(onboardService, awsSystem, "Checking account permissions and roles")
    Rel(onboardService, awsKMS, "Encrypt/Decrypt cloud credentials")
    Rel(onboardService, inventoryService, "retrieves summarized information on connections", "HTTP")
    Rel(onboardService, schedulerService, "retrieves information of pending tasks", "HTTP")
}

Rel(user, onboardService, "uses APIs", "HTTPS")

@enduml