@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    ContainerDb(workspacePostgres, "Database", "PostgreSQL", "Holds workspaces and authorization information")
    ContainerDb(rabbitMQ, "Database", "RabbitMQ", "Holds workspaces and authorization information")
    Container(steampipeService, "Steampipe service", "Go", "")
    Container(onboardService, "Onboard service", "Go", "")

    Container(reporterService, "Reporter service", "Go", "")
    Rel(rabbitMQ, reporterService, "")
    Rel(reporterService, steampipeService, "")
    Rel(reporterService, workspacePostgres, "")
    Rel(reporterService, onboardService, "")

    Container(reporterWorkers, "Reporter workers", "Go", "")
    Rel(rabbitMQ, reporterWorkers, "")
    Rel(reporterWorkers, steampipeService, "")
    Rel(reporterWorkers, workspacePostgres, "")
    Rel(reporterWorkers, onboardService, "")
}

@enduml