@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    ContainerDb(workspacePostgres, "Database", "PostgreSQL", "Holds workspaces and authorization information")
    ContainerDb(elastic, "Database", "ElasticSearch", "Holds workspaces and authorization information")
    ContainerDb(kafka, "Database", "Kafka", "Holds workspaces and authorization information")
    ContainerDb(rabbitMQ, "Database", "RabbitMQ", "Holds workspaces and authorization information")
    Container(complianceService, "Compliance service", "Go", "")

    Container(summarizerWorkers, "Summarizer workers", "Go", "")
    Rel(rabbitMQ, summarizerWorkers, "")
    Rel(summarizerWorkers, elastic, "")
    Rel(summarizerWorkers, kafka, "")
    Rel(summarizerWorkers, workspacePostgres, "")
    Rel(summarizerWorkers, complianceService, "")
}


@enduml