// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: pkg/describe/proto/describe.proto

package golang

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DescribeServiceClient is the client API for DescribeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DescribeServiceClient interface {
	DeliverResult(ctx context.Context, in *DeliverResultRequest, opts ...grpc.CallOption) (*ResponseOK, error)
	DeliverAWSResources(ctx context.Context, in *AWSResources, opts ...grpc.CallOption) (*ResponseOK, error)
	DeliverAzureResources(ctx context.Context, in *AzureResources, opts ...grpc.CallOption) (*ResponseOK, error)
}

type describeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDescribeServiceClient(cc grpc.ClientConnInterface) DescribeServiceClient {
	return &describeServiceClient{cc}
}

func (c *describeServiceClient) DeliverResult(ctx context.Context, in *DeliverResultRequest, opts ...grpc.CallOption) (*ResponseOK, error) {
	out := new(ResponseOK)
	err := c.cc.Invoke(ctx, "/kaytu.describe.v1.DescribeService/DeliverResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *describeServiceClient) DeliverAWSResources(ctx context.Context, in *AWSResources, opts ...grpc.CallOption) (*ResponseOK, error) {
	out := new(ResponseOK)
	err := c.cc.Invoke(ctx, "/kaytu.describe.v1.DescribeService/DeliverAWSResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *describeServiceClient) DeliverAzureResources(ctx context.Context, in *AzureResources, opts ...grpc.CallOption) (*ResponseOK, error) {
	out := new(ResponseOK)
	err := c.cc.Invoke(ctx, "/kaytu.describe.v1.DescribeService/DeliverAzureResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DescribeServiceServer is the server API for DescribeService service.
// All implementations must embed UnimplementedDescribeServiceServer
// for forward compatibility
type DescribeServiceServer interface {
	DeliverResult(context.Context, *DeliverResultRequest) (*ResponseOK, error)
	DeliverAWSResources(context.Context, *AWSResources) (*ResponseOK, error)
	DeliverAzureResources(context.Context, *AzureResources) (*ResponseOK, error)
	mustEmbedUnimplementedDescribeServiceServer()
}

// UnimplementedDescribeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDescribeServiceServer struct {
}

func (UnimplementedDescribeServiceServer) DeliverResult(context.Context, *DeliverResultRequest) (*ResponseOK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverResult not implemented")
}
func (UnimplementedDescribeServiceServer) DeliverAWSResources(context.Context, *AWSResources) (*ResponseOK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverAWSResources not implemented")
}
func (UnimplementedDescribeServiceServer) DeliverAzureResources(context.Context, *AzureResources) (*ResponseOK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverAzureResources not implemented")
}
func (UnimplementedDescribeServiceServer) mustEmbedUnimplementedDescribeServiceServer() {}

// UnsafeDescribeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DescribeServiceServer will
// result in compilation errors.
type UnsafeDescribeServiceServer interface {
	mustEmbedUnimplementedDescribeServiceServer()
}

func RegisterDescribeServiceServer(s grpc.ServiceRegistrar, srv DescribeServiceServer) {
	s.RegisterService(&DescribeService_ServiceDesc, srv)
}

func _DescribeService_DeliverResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescribeServiceServer).DeliverResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaytu.describe.v1.DescribeService/DeliverResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescribeServiceServer).DeliverResult(ctx, req.(*DeliverResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DescribeService_DeliverAWSResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AWSResources)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescribeServiceServer).DeliverAWSResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaytu.describe.v1.DescribeService/DeliverAWSResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescribeServiceServer).DeliverAWSResources(ctx, req.(*AWSResources))
	}
	return interceptor(ctx, in, info, handler)
}

func _DescribeService_DeliverAzureResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AzureResources)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescribeServiceServer).DeliverAzureResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaytu.describe.v1.DescribeService/DeliverAzureResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescribeServiceServer).DeliverAzureResources(ctx, req.(*AzureResources))
	}
	return interceptor(ctx, in, info, handler)
}

// DescribeService_ServiceDesc is the grpc.ServiceDesc for DescribeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DescribeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kaytu.describe.v1.DescribeService",
	HandlerType: (*DescribeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverResult",
			Handler:    _DescribeService_DeliverResult_Handler,
		},
		{
			MethodName: "DeliverAWSResources",
			Handler:    _DescribeService_DeliverAWSResources_Handler,
		},
		{
			MethodName: "DeliverAzureResources",
			Handler:    _DescribeService_DeliverAzureResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/describe/proto/describe.proto",
}
