// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/locations/{provider}": {
            "get": {
                "description": "Getting locations by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get locations",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure"
                        ],
                        "type": "string",
                        "description": "Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inventory.LocationByProviderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/resource": {
            "post": {
                "description": "Getting resource details by id and resource type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "Get details of a Resource",
                "parameters": [
                    {
                        "description": "Id",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ResourceType",
                        "name": "resourceType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/resources": {
            "post": {
                "description": "Getting all cloud providers resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetResourcesResponse"
                        }
                    }
                }
            }
        },
        "/resources/aws": {
            "post": {
                "description": "Getting AWS resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get AWS resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetAWSResourceResponse"
                        }
                    }
                }
            }
        },
        "/resources/aws/csv": {
            "post": {
                "description": "Getting AWS resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get AWS resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/resources/azure": {
            "post": {
                "description": "Getting Azure resources by filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get Azure resources",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Page",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Page"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.GetAzureResourceResponse"
                        }
                    }
                }
            }
        },
        "/resources/azure/csv": {
            "post": {
                "description": "Getting Azure resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get Azure resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/resources/csv": {
            "post": {
                "description": "Getting all resources by filters in csv file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get all resources in csv file",
                "parameters": [
                    {
                        "description": "Filters",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Filters"
                        }
                    },
                    {
                        "description": "Sort",
                        "name": "sort",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.Sort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "inventory.AWSResource": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                }
            }
        },
        "inventory.AllResource": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "sourceID": {
                    "type": "string"
                }
            }
        },
        "inventory.AzureResource": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceGroup": {
                    "type": "string"
                },
                "resourceID": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "subscriptionID": {
                    "type": "string"
                }
            }
        },
        "inventory.Filters": {
            "type": "object",
            "properties": {
                "keibiSource": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resourceType": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "inventory.GetAWSResourceResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AWSResource"
                    }
                }
            }
        },
        "inventory.GetAzureResourceResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AzureResource"
                    }
                }
            }
        },
        "inventory.GetResourcesResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "$ref": "#/definitions/inventory.Page"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.AllResource"
                    }
                }
            }
        },
        "inventory.LocationByProviderResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "inventory.Page": {
            "type": "object",
            "properties": {
                "nextMarker": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "inventory.Sort": {
            "type": "object",
            "properties": {
                "sortBy": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/inventory.SortItem"
                    }
                }
            }
        },
        "inventory.SortItem": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string",
                    "enum": [
                        "asc",
                        "desc"
                    ]
                },
                "field": {
                    "type": "string"
                }
            }
        }
    }
}`
