@baseUrl = http://127.0.0.1:6251/api/v1

### Create AWS Source
# @name create_source_aws
POST {{baseUrl}}/source/aws
Content-Type: application/json

{
	"name": "",
	"config": {
		"accountId": "XXX",
		"accessKey": "XXX",
		"secretKey": "XXX"
	}
}

### Create Azure Source
# @name create_source_azure
POST {{baseUrl}}/source/azure
Content-Type: application/json

{
	"name": "",
	"config": {
		"subscriptionId": "XXX",
		"tenantId": "XXX",
		"clientId": "XXX",
		"clientSecret": "XXX"
	}
}

### delete source
@sourceid = {{create_source_aws.response.body.$.id}}
DELETE {{baseUrl}}/source/{{sourceid}}



