// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SourceConfig is an autogenerated mock type for the SourceConfig type
type SourceConfig struct {
	mock.Mock
}

// Delete provides a mock function with given fields: pathRef
func (_m *SourceConfig) Delete(pathRef string) error {
	ret := _m.Called(pathRef)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pathRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: pathRef
func (_m *SourceConfig) Read(pathRef string) (map[string]interface{}, error) {
	ret := _m.Called(pathRef)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(pathRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pathRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: pathRef, config
func (_m *SourceConfig) Write(pathRef string, config map[string]interface{}) error {
	ret := _m.Called(pathRef, config)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(pathRef, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
