package configs

var ResourceTypesList = []string{
	"DigitalOcean::Account",
	"DigitalOcean::Action",
	"DigitalOcean::AlertPolicy",
	"DigitalOcean::App",
	"DigitalOcean::Balance",
	"DigitalOcean::Bill",
	"DigitalOcean::ContainerRegistry",
	"DigitalOcean::Database",
	"DigitalOcean::Domain",
	"DigitalOcean::Droplet",
	"DigitalOcean::Firewall",
	"DigitalOcean::FloatingIP",
	"DigitalOcean::Image",
	"DigitalOcean::Key",
	"DigitalOcean::KubernetesCluster",
	"DigitalOcean::KubernetesNodePool",
	"DigitalOcean::LoadBalancer",
	"DigitalOcean::Project",
	"DigitalOcean::Region",
	"DigitalOcean::Size",
	"DigitalOcean::Snapshot",
	"DigitalOcean::Tag",
	"DigitalOcean::Volume",
	"DigitalOcean::VPC",
}
