package configs

var ResourceTypesList = []string{
	"DigitalOcean::Account",
	"DigitalOcean::Action",
	"DigitalOcean::AlertPolicy",
	"DigitalOcean::App",
	"DigitalOcean::Balance",
	"DigitalOcean::Bill",
	"DigitalOcean::ContainerRegistry",
	"DigitalOcean::Database",
	"DigitalOcean::Domain",
	"DigitalOcean::Droplet",
	"DigitalOcean::Firewall",
	"DigitalOcean::FloatingIP",
	"DigitalOcean::Image",
	"DigitalOcean::Key",
	"DigitalOcean::KubernetesCluster",
	"DigitalOcean::KubernetesNodePool",
	"DigitalOcean::LoadBalancer",
	"DigitalOcean::Project",
	"DigitalOcean::Region",
	"DigitalOcean::Size",
	"DigitalOcean::Snapshot",
	"DigitalOcean::Tag",
	"DigitalOcean::Volume",
	"DigitalOcean::VPC",
}

var TablesToResourceTypes = map[string]string{
	"digitalocean_account":              "DigitalOcean::Account",
	"digitalocean_action":               "DigitalOcean::Action",
	"digitalocean_alert_policy":         "DigitalOcean::AlertPolicy",
	"digitalocean_app":                  "DigitalOcean::App",
	"digitalocean_balance":              "DigitalOcean::Balance",
	"digitalocean_bill":                 "DigitalOcean::Bill",
	"digitalocean_container_registry":   "DigitalOcean::ContainerRegistry",
	"digitalocean_database":             "DigitalOcean::Database",
	"digitalocean_domain":               "DigitalOcean::Domain",
	"digitalocean_droplet":              "DigitalOcean::Droplet",
	"digitalocean_firewall":             "DigitalOcean::Firewall",
	"digitalocean_floating_ip":          "DigitalOcean::FloatingIP",
	"digitalocean_image":                "DigitalOcean::Image",
	"digitalocean_key":                  "DigitalOcean::Key",
	"digitalocean_kubernetes_cluster":   "DigitalOcean::KubernetesCluster",
	"digitalocean_kubernetes_node_pool": "DigitalOcean::KubernetesNodePool",
	"digitalocean_load_balancer":        "DigitalOcean::LoadBalancer",
	"digitalocean_project":              "DigitalOcean::Project",
	"digitalocean_region":               "DigitalOcean::Region",
	"digitalocean_size":                 "DigitalOcean::Size",
	"digitalocean_snapshot":             "DigitalOcean::Snapshot",
	"digitalocean_tag":                  "DigitalOcean::Tag",
	"digitalocean_volume":               "DigitalOcean::Volume",
	"digitalocean_vpc":                  "DigitalOcean::VPC",
}
