@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Ext(awsSystem, "AWS", "")
System_Ext(azureSystem, "Azure", "")

System_Boundary(kaytuWorkspace, "Kaytu Workspace") {
    Container(schedulerService, "Scheduler service", "Go", "")
    Container(describeReceiverService, "Describe receiver service", "Go", "")
}

System_Boundary(kaytuDiscovery, "Kaytu Discovery") {
    Container(azureDescriber, "Kaytu Azure Describer", "Go", "Fetches metadata of variant resource types from Azure")
    Container(awsDescriber, "Kaytu AWS Describer", "Go", "Fetches metadata of variant resource types from AWS")

    Rel(azureDescriber, describeReceiverService, "Sends resources to", "GRPC")
    Rel(awsDescriber, describeReceiverService, "Sends resources to", "GRPC")
}

Rel(azureDescriber, azureSystem, "Gets resources from", "HTTPS")
Rel(awsDescriber, awsSystem, "Gets resources from", "HTTPS")

@enduml