package configs

var TablesToResourceTypes = map[string]string{
	"aws_redshift_snapshot":                           "AWS::Redshift::Snapshot",
	"aws_iam_account_summary":                         "AWS::IAM::AccountSummary",
	"aws_glacier_vault":                               "AWS::Glacier::Vault",
	"aws_organizations_organization":                  "AWS::Organizations::Organization",
	"aws_organizations_policy":                        "AWS::Organizations::Policy",
	"aws_organizations_policy_target":                 "AWS::Organizations::PolicyTarget",
	"aws_organizations_organizational_unit":           "AWS::Organizations::OrganizationalUnit",
	"aws_organizations_root":                          "AWS::Organizations::Root",
	"aws_cloudsearch_domain":                          "AWS::CloudSearch::Domain",
	"aws_dynamodb_global_secondary_index":             "AWS::DynamoDb::GlobalSecondaryIndex",
	"aws_vpc_route_table":                             "AWS::EC2::RouteTable",
	"aws_securityhub_hub":                             "AWS::SecurityHub::Hub",
	"aws_storagegateway_storage_gateway":              "AWS::StorageGateway::StorageGateway",
	"aws_inspector_assessment_template":               "AWS::Inspector::AssessmentTemplate",
	"aws_ec2_load_balancer_listener_rule":             "AWS::ElasticLoadBalancingV2::ListenerRule",
	"aws_iam_role":                                    "AWS::IAM::Role",
	"aws_backup_protected_resource":                   "AWS::Backup::ProtectedResource",
	"aws_codecommit_repository":                       "AWS::CodeCommit::Repository",
	"aws_vpc_endpoint":                                "AWS::EC2::VPCEndpoint",
	"aws_eventbridge_rule":                            "AWS::EventBridge::EventRule",
	"aws_cloudfront_origin_access_control":            "AWS::CloudFront::OriginAccessControl",
	"aws_codebuild_project":                           "AWS::CodeBuild::Project",
	"aws_codebuild_build":                             "AWS::CodeBuild::Build",
	"aws_elasticache_parameter_group":                 "AWS::ElastiCache::ParameterGroup",
	"aws_memorydb_cluster":                            "AWS::MemoryDb::Cluster",
	"aws_glue_crawler":                                "AWS::Glue::Crawler",
	"aws_directconnect_gateway":                       "AWS::DirectConnect::Gateway",
	"aws_dynamodb_backup":                             "AWS::DynamoDb::BackUp",
	"aws_vpc_eip":                                     "AWS::EC2::EIP",
	"aws_vpc_internet_gateway":                        "AWS::EC2::InternetGateway",
	"aws_guardduty_publishing_destination":            "AWS::GuardDuty::PublishingDestination",
	"aws_kinesisanalyticsv2_application":              "AWS::KinesisAnalyticsV2::Application",
	"aws_emr_instance":                                "AWS::EMR::Instance",
	"aws_emr_block_public_access_configuration":       "AWS::EMR::BlockPublicAccessConfiguration",
	"aws_api_gateway_rest_api":                        "AWS::ApiGateway::RestApi",
	"aws_api_gatewayv2_integration":                   "AWS::ApiGatewayV2::Integration",
	"aws_ec2_autoscaling_group":                       "AWS::AutoScaling::AutoScalingGroup",
	"aws_dynamodb_table_export":                       "AWS::DynamoDb::TableExport",
	"aws_ec2_key_pair":                                "AWS::EC2::KeyPair",
	"aws_efs_file_system":                             "AWS::EFS::FileSystem",
	"aws_kafka_cluster":                               "AWS::Kafka::Cluster",
	"aws_secretsmanager_secret":                       "AWS::SecretsManager::Secret",
	"aws_backup_legal_hold":                           "AWS::Backup::LegalHold",
	"aws_cloudfront_function":                         "AWS::CloudFront::Function",
	"aws_globalaccelerator_endpoint_group":            "AWS::GlobalAccelerator::EndpointGroup",
	"aws_dax_parameter_group":                         "AWS::DAX::ParameterGroup",
	"aws_sqs_queue":                                   "AWS::SQS::Queue",
	"aws_config_rule":                                 "AWS::Config::Rule",
	"aws_guardduty_member":                            "AWS::GuardDuty::Member",
	"aws_inspector_exclusion":                         "AWS::Inspector::Exclusion",
	"aws_directory_service_directory":                 "AWS::DirectoryService::Directory",
	"aws_directory_service_certificate":               "AWS::DirectoryService::Certificate",
	"aws_directory_service_log_subscription":          "AWS::DirectoryService::LogSubscription",
	"aws_efs_access_point":                            "AWS::EFS::AccessPoint",
	"aws_iam_policy_attachment":                       "AWS::IAM::PolicyAttachment",
	"aws_iam_credential_report":                       "AWS::IAM::CredentialReport",
	"aws_rds_global_cluster":                          "AWS::RDS::GlobalCluster",
	"aws_cost_forecast_daily":                         "AWS::CostExplorer::ForcastDaily",
	"aws_guardduty_detector":                          "AWS::GuardDuty::Detector",
	"aws_sns_topic":                                   "AWS::SNS::Topic",
	"aws_appconfig_application":                       "AWS::AppConfig::Application",
	"aws_batch_job":                                   "AWS::Batch::Job",
	"aws_batchjob_queue":                              "AWS::Batch::JobQueue",
	"aws_ecs_service":                                 "AWS::ECS::Service",
	"aws_fsx_task":                                    "AWS::FSX::Task",
	"aws_iam_virtual_mfa_device":                      "AWS::IAM::VirtualMFADevice",
	"aws_wafv2_web_acl":                               "AWS::WAFv2::WebACL",
	"aws_appautoscaling_target":                       "AWS::ApplicationAutoScaling::Target",
	"aws_appautoscaling_policy":                       "AWS::ApplicationAutoScaling::Policy",
	"aws_backup_vault":                                "AWS::Backup::Vault",
	"aws_elasticache_cluster":                         "AWS::ElastiCache::Cluster",
	"aws_cloudwatch_log_group":                        "AWS::Logs::LogGroup",
	"aws_s3_bucket":                                   "AWS::S3::Bucket",
	"aws_s3_object":                                   "AWS::S3::Object",
	"aws_s3_bucket_intelligent_tiering_configuration": "AWS::S3::BucketIntelligentTieringConfiguration",
	"aws_s3_multi_region_access_point":                "AWS::S3::MultiRegionAccessPoint",
	"aws_acm_certificate":                             "AWS::CertificateManager::Certificate",
	"aws_eks_addon_version":                           "AWS::EKS::AddonVersion",
	"aws_api_gatewayv2_api":                           "AWS::ApiGatewayV2::Api",
	"aws_ebs_volume":                                  "AWS::EC2::Volume",
	"aws_api_gateway_api_key":                         "AWS::ApiGateway::ApiKey",
	"aws_glue_connection":                             "AWS::Glue::Connection",
	"aws_ecs_task":                                    "AWS::ECS::Task",
	"aws_ssm_managed_instance":                        "AWS::SSM::ManagedInstance",
	"aws_ssm_inventory":                               "AWS::SSM::Inventory",
	"aws_ssm_inventory_entry":                         "AWS::SSM::InventoryEntry",
	"aws_ssm_maintenance_window":                      "AWS::SSM::MaintenanceWindow",
	"aws_ssm_patch_baseline":                          "AWS::SSM::PatchBaseline",
	"aws_ssm_parameter":                               "AWS::SSM::Parameter",
	"aws_lambda_function":                             "AWS::Lambda::Function",
	"aws_rds_db_snapshot":                             "AWS::RDS::DBSnapshot",
	"aws_codedeploy_app":                              "AWS::CodeDeploy::Application",
	"aws_codedeploy_deployment_config":                "AWS::CodeDeploy::DeploymentConfig",
	"aws_emr_cluster":                                 "AWS::EMR::Cluster",
	"aws_iam_access_key":                              "AWS::IAM::AccessKey",
	"aws_iam_ssh_public_key":                          "AWS::IAM::SSHPublicKey",
	"aws_glue_catalog_table":                          "AWS::Glue::CatalogTable",
	"aws_cloudtrail_channel":                          "AWS::CloudTrail::Channel",
	"aws_vpc_network_acl":                             "AWS::EC2::NetworkAcl",
	"aws_ecs_container_instance":                      "AWS::ECS::ContainerInstance",
	"aws_redshiftserverless_snapshot":                 "AWS::RedshiftServerless::Snapshot",
	"aws_workspaces_bundle":                           "AWS::Workspaces::Bundle",
	"aws_cloudtrail_trail":                            "AWS::CloudTrail::Trail",
	"aws_dax_parameter":                               "AWS::DAX::Parameter",
	"aws_ecr_image":                                   "AWS::ECR::Image",
	"aws_iam_server_certificate":                      "AWS::IAM::ServerCertificate",
	"aws_keyspaces_keyspace":                          "AWS::Keyspaces::Keyspace",
	"aws_s3_access_point":                             "AWS::S3::AccessPoint",
	"aws_sagemaker_endpoint_configuration":            "AWS::SageMaker::EndpointConfiguration",
	"aws_elasticache_reserved_cache_node":             "AWS::ElastiCache::ReservedCacheNode",
	"aws_emr_instance_fleet":                          "AWS::EMR::InstanceFleet",
	"aws_account":                                     "AWS::Account::Account",
	"aws_vpc_peering_connection":                      "AWS::EC2::VPCPeeringConnection",
	"aws_eks_fargate_profile":                         "AWS::EKS::FargateProfile",
	"aws_iam_account_password_policy":                 "AWS::IAM::AccountPasswordPolicy",
	"aws_codepipeline_pipeline":                       "AWS::CodePipeline::Pipeline",
	"aws_dax_cluster":                                 "AWS::DAX::Cluster",
	"aws_dlm_lifecycle_policy":                        "AWS::DLM::LifecyclePolicy",
	"aws_opsworkscm_server":                           "AWS::OpsWorksCM::Server",
	"aws_accessanalyzer_analyzer":                     "AWS::AccessAnalyzer::Analyzer",
	"aws_accessanalyzer_finding":                      "AWS::AccessAnalyzer::Finding",
	"aws_elasticache_subnet_group":                    "AWS::ElastiCache::SubnetGroup",
	"aws_fsx_volume":                                  "AWS::FSX::Volume",
	"aws_amplify_app":                                 "AWS::Amplify::App",
	"aws_cloudtrail_query":                            "AWS::CloudTrail::Query",
	"aws_cost_by_account_monthly":                     "AWS::CostExplorer::ByAccountMonthly",
	"aws_ecrpublic_registry":                          "AWS::ECR::PublicRegistry",
	"aws_ec2_network_interface":                       "AWS::EC2::NetworkInterface",
	"aws_vpc_vpn_connection":                          "AWS::EC2::VPNConnection",
	"aws_fsx_storage_virtual_machine":                 "AWS::FSX::StorageVirtualMachine",
	"aws_api_gateway_authorizer":                      "AWS::ApiGateway::Authorizer",
	"aws_appstream_stack":                             "AWS::AppStream::Stack",
	"aws_athena_workgroup":                            "AWS::Athena::WorkGroup",
	"aws_athena_query_execution":                      "AWS::Athena::QueryExecution",
	"aws_appstream_image":                             "AWS::AppStream::Image",
	"aws_cloudwatch_alarm":                            "AWS::CloudWatch::Alarm",
	"aws_cloudwatch_log_subscription_filter":          "AWS::CloudWatch::LogSubscriptionFilter",
	"aws_cost_by_record_type_monthly":                 "AWS::CostExplorer::ByRecordTypeMonthly",
	"aws_rds_db_cluster":                              "AWS::RDS::DBCluster",
	"aws_rds_db_cluster_snapshot":                     "AWS::RDS::DBClusterSnapshot",
	"aws_backup_framework":                            "AWS::Backup::Framework",
	"aws_codebuild_source_credential":                 "AWS::CodeBuild::SourceCredential",
	"aws_iam_service_specific_credential":             "AWS::IAM::ServiceSpecificCredential",
	"aws_ec2_capacity_reservation_fleet":              "AWS::EC2::CapacityReservationFleet",
	"aws_networkfirewall_firewall":                    "AWS::NetworkFirewall::Firewall",
	"aws_workspaces_workspace":                        "AWS::Workspaces::Workspace",
	"aws_elasticsearch_domain":                        "AWS::ElasticSearch::Domain",
	"aws_rds_db_instance":                             "AWS::RDS::DBInstance",
	"aws_rds_db_instance_automated_backup":            "AWS::RDS::DBInstanceAutomatedBackup",
	"aws_efs_mount_target":                            "AWS::EFS::MountTarget",
	"aws_globalaccelerator_listener":                  "AWS::GlobalAccelerator::Listener",
	"aws_cost_by_service_usage_type_daily":            "AWS::CostExplorer::ByUsageTypeDaily",
	"aws_eks_addon":                                   "AWS::EKS::Addon",
	"aws_cost_by_service_monthly":                     "AWS::CostExplorer::ByServiceMonthly",
	"aws_iam_policy":                                  "AWS::IAM::Policy",
	"aws_redshift_cluster":                            "AWS::Redshift::Cluster",
	"aws_wafregional_rule":                            "AWS::WAFRegional::Rule",
	"aws_wafregional_rule_group":                      "AWS::WAFRegional::RuleGroup",
	"aws_glue_data_catalog_encryption_settings":       "AWS::Glue::DataCatalogEncryptionSettings",
	"aws_vpc_flow_log":                                "AWS::EC2::FlowLog",
	"aws_ec2_ipam_pool":                               "AWS::EC2::IpamPool",
	"aws_iam_saml_provider":                           "AWS::IAM::SamlProvider",
	"aws_route53_zone":                                "AWS::Route53::HostedZone",
	"aws_route53_query_log":                           "AWS::Route53::QueryLog",
	"aws_ec2_placement_group":                         "AWS::EC2::PlacementGroup",
	"aws_fsx_snapshot":                                "AWS::FSX::Snapshot",
	"aws_kms_key":                                     "AWS::KMS::Key",
	"aws_kms_key_rotation":                            "AWS::KMS::KeyRotation",
	"aws_ec2_ipam":                                    "AWS::EC2::Ipam",
	"aws_elastic_beanstalk_environment":               "AWS::ElasticBeanstalk::Environment",
	"aws_elastic_beanstalk_application_version":       "AWS::ElasticBeanstalk::ApplicationVersion",
	"aws_lambda_version":                              "AWS::Lambda::FunctionVersion",
	"aws_glue_dev_endpoint":                           "AWS::Glue::DevEndpoint",
	"aws_backup_recovery_point":                       "AWS::Backup::RecoveryPoint",
	"aws_backup_report_plan":                          "AWS::Backup::ReportPlan",
	"aws_backup_region_settings":                      "AWS::Backup::RegionSetting",
	"aws_dynamodbstreams_stream":                      "AWS::DynamoDbStreams::Stream",
	"aws_vpc_egress_only_internet_gateway":            "AWS::EC2::EgressOnlyInternetGateway",
	"aws_cloudfront_distribution":                     "AWS::CloudFront::Distribution",
	"aws_cloudfront_streamingdistribution":            "AWS::CloudFront::StreamingDistribution",
	"aws_glue_job":                                    "AWS::Glue::Job",
	"aws_appstream_fleet":                             "AWS::AppStream::Fleet",
	"aws_ses_configuration_set":                       "AWS::SES::ConfigurationSet",
	"aws_iam_user":                                    "AWS::IAM::User",
	"aws_cloudfront_origin_request_policy":            "AWS::CloudFront::OriginRequestPolicy",
	"aws_vpc_security_group":                          "AWS::EC2::SecurityGroup",
	"aws_guardduty_ipset":                             "AWS::GuardDuty::IPSet",
	"aws_eks_cluster":                                 "AWS::EKS::Cluster",
	"aws_grafana_workspace":                           "AWS::Grafana::Workspace",
	"aws_glue_catalog_database":                       "AWS::Glue::CatalogDatabase",
	"aws_health_event":                                "AWS::Health::Event",
	"aws_health_affected_entity":                      "AWS::Health::AffectedEntity",
	"aws_cloudformation_stack_set":                    "AWS::CloudFormation::StackSet",
	"aws_availability_zone":                           "AWS::EC2::AvailabilityZone",
	"aws_ec2_transit_gateway":                         "AWS::EC2::TransitGateway",
	"aws_api_gateway_usage_plan":                      "AWS::ApiGateway::UsagePlan",
	"aws_inspector_finding":                           "AWS::Inspector::Finding",
	"aws_ec2_fleet":                                   "AWS::EC2::Fleet",
	"aws_elastic_beanstalk_application":               "AWS::ElasticBeanstalk::Application",
	"aws_ec2_application_load_balancer":               "AWS::ElasticLoadBalancingV2::LoadBalancer",
	"aws_opensearch_domain":                           "AWS::OpenSearch::Domain",
	"aws_rds_db_event_subscription":                   "AWS::RDS::DBEventSubscription",
	"aws_rds_db_engine_version":                       "AWS::RDS::DBEngineVersion",
	"aws_ec2_regional_settings":                       "AWS::EC2::RegionalSettings",
	"aws_vpc_security_group_rule":                     "AWS::EC2::SecurityGroupRule",
	"aws_ec2_transit_gateway_vpc_attachment":          "AWS::EC2::TransitGatewayAttachment",
	"aws_ses_identity":                                "AWS::SES::Identity",
	"aws_sesv2_emailidentity":                         "AWS::SESv2::EmailIdentities",
	"aws_waf_rule":                                    "AWS::WAF::Rule",
	"aws_waf_rule_group":                              "AWS::WAF::RuleGroup",
	"aws_waf_rate_based_rule":                         "AWS::WAF::RateBasedRule",
	"aws_waf_web_acl":                                 "AWS::WAF::WebACL",
	"aws_wafregional_web_acl":                         "AWS::WAFRegional::WebACL",
	"aws_wellarchitected_workload":                    "AWS::WellArchitected::Workload",
	"aws_wellarchitected_answer":                      "AWS::WellArchitected::Answer",
	"aws_wellarchitected_check_detail":                "AWS::WellArchitected::CheckDetail",
	"aws_wellarchitected_check_summary":               "AWS::WellArchitected::CheckSummary",
	"aws_wellarchitected_consolidated_report":         "AWS::WellArchitected::ConsolidatedReport",
	"aws_wellarchitected_lens":                        "AWS::WellArchitected::Lens",
	"aws_wellarchitected_lens_review":                 "AWS::WellArchitected::LensReview",
	"aws_wellarchitected_lens_review_improvement":     "AWS::WellArchitected::LensReviewImprovement",
	"aws_wellarchitected_lens_review_report":          "AWS::WellArchitected::LensReviewReport",
	"aws_wellarchitected_lens_share":                  "AWS::WellArchitected::LensShare",
	"aws_wellarchitected_milestone":                   "AWS::WellArchitected::Milestone",
	"aws_wellarchitected_notification":                "AWS::WellArchitected::Notification",
	"aws_wellarchitected_share_invitation":            "AWS::WellArchitected::ShareInvitation",
	"aws_wellarchitected_workload_share":              "AWS::WellArchitected::WorkloadShare",
	"aws_ec2_launch_configuration":                    "AWS::AutoScaling::LaunchConfiguration",
	"aws_cloudtrail_event_data_store":                 "AWS::CloudTrail::EventDataStore",
	"aws_codedeploy_deployment_group":                 "AWS::CodeDeploy::DeploymentGroup",
	"aws_imagebuilder_image":                          "AWS::ImageBuilder::Image",
	"aws_redshift_parameter_group":                    "AWS::Redshift::ClusterParameterGroup",
	"aws_account_alternate_contact":                   "AWS::Account::AlternateContact",
	"aws_inspector_assessment_target":                 "AWS::Inspector::AssessmentTarget",
	"aws_cloudfront_response_headers_policy":          "AWS::CloudFront::ResponseHeadersPolicy",
	"aws_ec2_instance":                                "AWS::EC2::Instance",
	"aws_ec2_instance_metric_cpu_utilization_hourly":  "AWS::EC2::InstanceMetricCpuUtilizationHourly",
	"aws_ec2_instance_availability":                   "AWS::EC2::InstanceAvailability",
	"aws_cost_by_record_type_daily":                   "AWS::CostExplorer::ByRecordTypeDaily",
	"aws_ec2_reserved_instance":                       "AWS::EC2::ReservedInstances",
	"aws_ecr_repository":                              "AWS::ECR::Repository",
	"aws_ecr_registry":                                "AWS::ECR::Registry",
	"aws_ecr_registry_scanning_configuration":         "AWS::ECR::RegistryScanningConfiguration",
	"aws_ec2_load_balancer_listener":                  "AWS::ElasticLoadBalancingV2::Listener",
	"aws_iam_group":                                   "AWS::IAM::Group",
	"aws_iam_open_id_connect_provider":                "AWS::IAM::OpenIdConnectProvider",
	"aws_backup_plan":                                 "AWS::Backup::Plan",
	"aws_config_conformance_pack":                     "AWS::Config::ConformancePack",
	"aws_config_retention_configuration":              "AWS::Config::RetentionConfiguration",
	"aws_cost_by_account_daily":                       "AWS::CostExplorer::ByAccountDaily",
	"aws_account_contact":                             "AWS::Account::Contact",
	"aws_glue_data_quality_ruleset":                   "AWS::Glue::DataQualityRuleset",
	"aws_eventbridge_bus":                             "AWS::EventBridge::EventBus",
	"aws_api_gateway_stage":                           "AWS::ApiGateway::Stage",
	"aws_api_gatewayv2_stage":                         "AWS::ApiGatewayV2::Stage",
	"aws_dynamodb_local_secondary_index":              "AWS::DynamoDb::LocalSecondaryIndex",
	"aws_resourcegroups_group":                        "AWS::ResourceGroups::Groups",
	"aws_timestream_database":                         "AWS::Timestream::Database",
	"aws_opensearchserverless_collection":             "AWS::OpenSearchServerless::Collection",
	"aws_ec2_elasticip":                               "AWS::EC2::ElasticIP",
	"aws_ec2_localgateway":                            "AWS::EC2::LocalGateway",
	"aws_ec2_ami":                                     "AWS::EC2::Image",
	"aws_vpc_subnet":                                  "AWS::EC2::Subnet",
	"aws_ecs_task_set":                                "AWS::ECS::TaskSet",
	"aws_kinesis_stream":                              "AWS::Kinesis::Stream",
	"aws_kinesis_consumer":                            "AWS::Kinesis::Consumer",
	"aws_docdb_cluster":                               "AWS::DocDB::Cluster",
	"aws_docdb_cluster_snapshot":                      "AWS::DocDB::ClusterSnapshot",
	"aws_docdb_cluster_instance":                      "AWS::DocDB::ClusterInstance",
	"aws_elasticache_replication_group":               "AWS::ElastiCache::ReplicationGroup",
	"aws_globalaccelerator_accelerator":               "AWS::GlobalAccelerator::Accelerator",
	"aws_cloudwatch_metric":                           "AWS::CloudWatch::Metric",
	"aws_cost_forecast_monthly":                       "AWS::CostExplorer::ForcastMonthly",
	"aws_emr_instance_group":                          "AWS::EMR::InstanceGroup",
	"aws_ec2_managed_prefix_list":                     "AWS::EC2::ManagedPrefixList",
	"aws_ec2_managed_prefix_list_entry":               "AWS::EC2::ManagedPrefixListEntry",
	"aws_ec2_client_vpn_endpoint":                     "AWS::EC2::ClientVpnEndpoint",
	"aws_mwaa_environment":                            "AWS::MWAA::Environment",
	"aws_cloudwatch_log_resource_policy":              "AWS::CloudWatch::LogResourcePolicy",
	"aws_codeartifact_domain":                         "AWS::CodeArtifact::Domain",
	"aws_codestar_project":                            "AWS::CodeStar::Project",
	"aws_neptune_database":                            "AWS::Neptune::Database",
	"aws_neptune_db_cluster":                          "AWS::Neptune::DBCluster",
	"aws_neptune_db_cluster_snapshot":                 "AWS::Neptune::DBClusterSnapshot",
	"aws_networkfirewall_firewall_policy":             "AWS::NetworkFirewall::FirewallPolicy",
	"aws_networkfirewall_rule_group":                  "AWS::NetworkFirewall::RuleGroup",
	"aws_oam_link":                                    "AWS::Oam::Link",
	"aws_oam_sink":                                    "AWS::Oam::Sink",
	"aws_organizations_account":                       "AWS::Organizations::Account",
	"aws_pinpoint_app":                                "AWS::Pinpoint::App",
	"aws_pipes_pipe":                                  "AWS::Pipes::Pipe",
	"aws_rds_db_cluster_parameter_group":              "AWS::RDS::DBClusterParameterGroup",
	"aws_rds_db_option_group":                         "AWS::RDS::OptionGroup",
	"aws_rds_db_parameter_group":                      "AWS::RDS::DBParameterGroup",
	"aws_rds_db_proxy":                                "AWS::RDS::DBProxy",
	"aws_rds_db_subnet_group":                         "AWS::RDS::DBSubnetGroup",
	"aws_rds_db_recommendation":                       "AWS::RDS::DBRecommendation",
	"aws_redshift_event_subscription":                 "AWS::Redshift::EventSubscription",
	"aws_redshiftserverless_workgroup":                "AWS::RedshiftServerless::Workgroup",
	"aws_resource_explorer_index":                     "AWS::ResourceExplorer2::Index",
	"aws_route53_health_check":                        "AWS::Route53::HealthCheck",
	"aws_route53_resolver_rule":                       "AWS::Route53Resolver::ResolverRule",
	"aws_route53_resolver_query_log_config":           "AWS::Route53Resolver::QueryLogConfig",
	"aws_sagemaker_app":                               "AWS::SageMaker::App",
	"aws_sagemaker_domain":                            "AWS::SageMaker::Domain",
	"aws_sfn_state_machine":                           "AWS::StepFunctions::StateMachine",
	"aws_sfn_state_machine_execution":                 "AWS::StepFunctions::StateMachineExecution",
	"aws_sfn_state_machine_execution_history":         "AWS::StepFunctions::StateMachineExecutionHistories",
	"aws_simspaceweaver_simulation":                   "AWS::SimSpaceWeaver::Simulation",
	"aws_ssm_association":                             "AWS::SSM::Association",
	"aws_ssm_document":                                "AWS::SSM::Document",
	"aws_ssm_document_permission":                     "AWS::SSM::DocumentPermission",
	"aws_vpc_customer_gateway":                        "AWS::EC2::CustomerGateway",
	"aws_vpc_verified_access_instance":                "AWS::EC2::VerifiedAccessInstance",
	"aws_vpc_verified_access_endpoint":                "AWS::EC2::VerifiedAccessEndpoint",
	"aws_vpc_verified_access_group":                   "AWS::EC2::VerifiedAccessGroup",
	"aws_vpc_verified_access_trust_provider":          "AWS::EC2::VerifiedAccessTrustProvider",
	"aws_vpc_vpn_gateway":                             "AWS::EC2::VPNGateway",
	"aws_wafv2_ip_set":                                "AWS::WAFv2::IPSet",
	"aws_wafv2_regex_pattern_set":                     "AWS::WAFv2::RegexPatternSet",
	"aws_wafv2_rule_group":                            "AWS::WAFv2::RuleGroup",
	"aws_ec2_transit_gateway_route":                   "AWS::EC2::TransitGatewayRoute",
	"aws_guardduty_filter":                            "AWS::GuardDuty::Filter",
	"aws_ecs_task_definition":                         "AWS::ECS::TaskDefinition",
	"aws_guardduty_threat_intel_set":                  "AWS::GuardDuty::ThreatIntelSet",
	"aws_api_gatewayv2_domain_name":                   "AWS::ApiGatewayV2::DomainName",
	"aws_api_gateway_domain_name":                     "AWS::ApiGateway::DomainName",
	"aws_api_gatewayv2_route":                         "AWS::ApiGatewayV2::Route",
	"aws_mq_broker":                                   "AWS::MQ::Broker",
	"aws_acmpca_certificate_authority":                "AWS::ACMPCA::CertificateAuthority",
	"aws_cloudformation_stack":                        "AWS::CloudFormation::Stack",
	"aws_cloudformation_stack_resource":               "AWS::CloudFormation::StackResource",
	"aws_directconnect_connection":                    "AWS::DirectConnect::Connection",
	"aws_fsx_file_system":                             "AWS::FSX::FileSystem",
	"aws_glue_security_configuration":                 "AWS::Glue::SecurityConfiguration",
	"aws_inspector_assessment_run":                    "AWS::Inspector::AssessmentRun",
	"aws_inspector2_coverage":                         "AWS::Inspector2::Coverage",
	"aws_inspector2_coverage_statistics":              "AWS::Inspector2::CoverageStatistics",
	"aws_inspector2_member":                           "AWS::Inspector2::Member",
	"aws_inspector2_finding":                          "AWS::Inspector2::Finding",
	"aws_config_configuration_recorder":               "AWS::Config::ConfigurationRecorder",
	"aws_vpc_nat_gateway":                             "AWS::EC2::NatGateway",
	"aws_ecrpublic_repository":                        "AWS::ECR::PublicRepository",
	"aws_ecs_cluster":                                 "AWS::ECS::Cluster",
	"aws_ec2_target_group":                            "AWS::ElasticLoadBalancingV2::TargetGroup",
	"aws_cloudfront_cache_policy":                     "AWS::CloudFront::CachePolicy",
	"aws_codeartifact_repository":                     "AWS::CodeArtifact::Repository",
	"aws_amp_workspace":                               "AWS::AMP::Workspace",
	"aws_ec2_capacity_reservation":                    "AWS::EC2::CapacityReservation",
	"aws_sagemaker_notebook_instance":                 "AWS::SageMaker::NotebookInstance",
	"aws_iam_access_advisor":                          "AWS::IAM::AccessAdvisor",
	"aws_ebs_snapshot":                                "AWS::EC2::VolumeSnapshot",
	"aws_region":                                      "AWS::EC2::Region",
	"aws_keyspaces_table":                             "AWS::Keyspaces::Table",
	"aws_config_aggregate_authorization":              "AWS::Config::AggregationAuthorization",
	"aws_dax_subnet_group":                            "AWS::DAX::SubnetGroup",
	"aws_dynamodb_global_table":                       "AWS::DynamoDb::GlobalTable",
	"aws_ec2_classic_load_balancer":                   "AWS::ElasticLoadBalancing::LoadBalancer",
	"aws_appstream_application":                       "AWS::AppStream::Application",
	"aws_redshiftserverless_namespace":                "AWS::RedshiftServerless::Namespace",
	"aws_cloudfront_origin_access_identity":           "AWS::CloudFront::OriginAccessIdentity",
	"aws_ec2_host":                                    "AWS::EC2::Host",
	"aws_vpc":                                         "AWS::EC2::VPC",
	"aws_ec2_transit_gateway_route_table":             "AWS::EC2::TransitGatewayRouteTable",
	"aws_eks_node_group":                              "AWS::EKS::Nodegroup",
	"aws_backup_selection":                            "AWS::Backup::Selection",
	"aws_cloudtrail_import":                           "AWS::CloudTrail::Import",
	"aws_cost_by_service_daily":                       "AWS::CostExplorer::ByServiceDaily",
	"aws_ec2_ssl_policy":                              "AWS::ElasticLoadBalancingV2::SslPolicy",
	"aws_guardduty_finding":                           "AWS::GuardDuty::Finding",
	"aws_vpc_dhcp_options":                            "AWS::EC2::DHCPOptions",
	"aws_ec2_instance_type":                           "AWS::EC2::InstanceType",
	"aws_batch_compute_environment":                   "AWS::Batch::ComputeEnvironment",
	"aws_dms_replication_instance":                    "AWS::DMS::ReplicationInstance",
	"aws_dms_endpoint":                                "AWS::DMS::Endpoint",
	"aws_dms_replication_task":                        "AWS::DMS::ReplicationTask",
	"aws_dynamodb_table":                              "AWS::DynamoDb::Table",
	"aws_shield_protection_group":                     "AWS::Shield::ProtectionGroup",
	"aws_kinesis_firehose_delivery_stream":            "AWS::Firehose::DeliveryStream",
	"aws_kinesis_video_stream":                        "AWS::KinesisVideo::Stream",
	"aws_kms_alias":                                   "AWS::KMS::Alias",
	"aws_lambda_alias":                                "AWS::Lambda::Alias",
	"aws_lambda_layer":                                "AWS::Lambda::LambdaLayer",
	"aws_lambda_layer_version":                        "AWS::Lambda::LayerVersion",
	"aws_lightsail_instance":                          "AWS::Lightsail::Instance",
	"aws_macie2_classification_job":                   "AWS::Macie2::ClassificationJob",
	"aws_media_store_container":                       "AWS::MediaStore::Container",
	"aws_mgn_application":                             "AWS::Mgn::Application",
	"aws_resource_explorer_supported_resource_type":   "AWS::ResourceExplorer2::SupportedResourceType",
	"aws_route53_resolver_endpoint":                   "AWS::Route53Resolver::ResolverEndpoint",
	"aws_route53_domain":                              "AWS::Route53Domains::Domain",
	"aws_route53_record":                              "AWS::Route53::Record",
	"aws_route53_traffic_policy":                      "AWS::Route53::TrafficPolicy",
	"aws_route53_traffic_policy_instance":             "AWS::Route53::TrafficPolicyInstance",
	"aws_sagemaker_model":                             "AWS::SageMaker::Model",
	"aws_sagemaker_training_job":                      "AWS::SageMaker::TrainingJob",
	"aws_securityhub_action_target":                   "AWS::SecurityHub::ActionTarget",
	"aws_securityhub_finding":                         "AWS::SecurityHub::Finding",
	"aws_securityhub_finding_aggregator":              "AWS::SecurityHub::FindingAggregator",
	"aws_securityhub_insight":                         "AWS::SecurityHub::Insight",
	"aws_securityhub_member":                          "AWS::SecurityHub::Member",
	"aws_securityhub_product":                         "AWS::SecurityHub::Product",
	"aws_securityhub_standards_control":               "AWS::SecurityHub::StandardsControl",
	"aws_securityhub_standards_subscription":          "AWS::SecurityHub::StandardsSubscription",
	"aws_securitylake_data_lake":                      "AWS::SecurityLake::DataLake",
	"aws_securitylake_subscriber":                     "AWS::SecurityLake::Subscriber",
	"aws_ram_principal_association":                   "AWS::Ram::PrincipalAssociation",
	"aws_ram_resource_association":                    "AWS::Ram::ResourceAssociation",
	"aws_rds_reserved_db_instance":                    "AWS::RDS::ReservedDBInstance",
	"aws_redshift_subnet_group":                       "AWS::Redshift::SubnetGroup",
	"aws_serverlessapplicationrepository_application": "AWS::SeverlessApplicationRepository::Application",
	"aws_auditmanager_framework":                      "AWS::AuditManager::Framework",
	"aws_auditmanager_evidence_folder":                "AWS::AuditManager::EvidenceFolder",
	"aws_auditmanager_evidence":                       "AWS::AuditManager::Evidence",
	"aws_auditmanager_control":                        "AWS::AuditManager::Control",
	"aws_auditmanager_assessment":                     "AWS::AuditManager::Assessment",
	"aws_cloudtrail_trail_event":                      "AWS::CloudTrail::TrailEvent",
	"aws_cloudwatch_log_event":                        "AWS::CloudWatch::LogEvent",
	"aws_cloudwatch_log_metric_filter":                "AWS::Logs::MetricFilter",
	"aws_cloudwatch_log_stream":                       "AWS::CloudWatch::LogStream",
	"aws_cost_by_service_usage_type_monthly":          "AWS::CostExplorer::ByUsageTypeMonthly",
	"aws_servicequotas_service_quota_change_request":  "AWS::ServiceQuotas::ServiceQuotaChangeRequest",
	"aws_servicequotas_service":                       "AWS::ServiceQuotas::Service",
	"aws_vpc_endpoint_service":                        "AWS::EC2::VPCEndpointService",
	"aws_ec2_launch_template":                         "AWS::EC2::LaunchTemplate",
	"aws_ec2_launch_template_version":                 "AWS::EC2::LaunchTemplateVersion",
	"aws_sns_topic_subscription":                      "AWS::SNS::Subscription",
	"aws_s3_account_settings":                         "AWS::S3::AccountSetting",
	"aws_ssm_managed_instance_compliance":             "AWS::SSM::ManagedInstanceCompliance",
	"aws_ssm_managed_instance_patch_state":            "AWS::SSM::ManagedInstancePatchState",
	"aws_ssoadmin_account_assignment":                 "AWS::SSOAdmin::AccountAssignment",
	"aws_user_effective_access":                       "AWS::SSOAdmin::UserEffectiveAccess",
	"aws_ssoadmin_instance":                           "AWS::SSOAdmin::Instance",
	"aws_ssoadmin_permission_set":                     "AWS::SSOAdmin::PermissionSet",
	"aws_ssoadmin_managed_policy_attachment":          "AWS::SSOAdmin::AttachedManagedPolicy",
	"aws_service_discovery_service":                   "AWS::ServiceDiscovery::Service",
	"aws_service_discovery_namespace":                 "AWS::ServiceDiscovery::Namespace",
	"aws_service_discovery_instance":                  "AWS::ServiceDiscovery::Instance",
	"aws_servicecatalog_portfolio":                    "AWS::ServiceCatalog::Portfolio",
	"aws_servicecatalog_product":                      "AWS::ServiceCatalog::Product",
	"aws_identitystore_user":                          "AWS::IdentityStore::User",
	"aws_identitystore_group":                         "AWS::IdentityStore::Group",
	"aws_identitystore_group_membership":              "AWS::IdentityStore::GroupMembership",
}

var ResourceTypesList = []string{
	"AWS::Redshift::Snapshot",
	"AWS::IAM::AccountSummary",
	"AWS::Glacier::Vault",
	"AWS::Organizations::Organization",
	"AWS::Organizations::Policy",
	"AWS::Organizations::PolicyTarget",
	"AWS::Organizations::OrganizationalUnit",
	"AWS::Organizations::Root",
	"AWS::CloudSearch::Domain",
	"AWS::DynamoDb::GlobalSecondaryIndex",
	"AWS::EC2::RouteTable",
	"AWS::SecurityHub::Hub",
	"AWS::StorageGateway::StorageGateway",
	"AWS::Inspector::AssessmentTemplate",
	"AWS::ElasticLoadBalancingV2::ListenerRule",
	"AWS::IAM::Role",
	"AWS::Backup::ProtectedResource",
	"AWS::CodeCommit::Repository",
	"AWS::EC2::VPCEndpoint",
	"AWS::EventBridge::EventRule",
	"AWS::CloudFront::OriginAccessControl",
	"AWS::CodeBuild::Project",
	"AWS::CodeBuild::Build",
	"AWS::ElastiCache::ParameterGroup",
	"AWS::MemoryDb::Cluster",
	"AWS::Glue::Crawler",
	"AWS::DirectConnect::Gateway",
	"AWS::DynamoDb::BackUp",
	"AWS::EC2::EIP",
	"AWS::EC2::InternetGateway",
	"AWS::GuardDuty::PublishingDestination",
	"AWS::KinesisAnalyticsV2::Application",
	"AWS::EMR::Instance",
	"AWS::EMR::BlockPublicAccessConfiguration",
	"AWS::ApiGateway::RestApi",
	"AWS::ApiGatewayV2::Integration",
	"AWS::AutoScaling::AutoScalingGroup",
	"AWS::DynamoDb::TableExport",
	"AWS::EC2::KeyPair",
	"AWS::EFS::FileSystem",
	"AWS::Kafka::Cluster",
	"AWS::SecretsManager::Secret",
	"AWS::Backup::LegalHold",
	"AWS::CloudFront::Function",
	"AWS::GlobalAccelerator::EndpointGroup",
	"AWS::DAX::ParameterGroup",
	"AWS::SQS::Queue",
	"AWS::Config::Rule",
	"AWS::GuardDuty::Member",
	"AWS::Inspector::Exclusion",
	"AWS::DirectoryService::Directory",
	"AWS::DirectoryService::Certificate",
	"AWS::DirectoryService::LogSubscription",
	"AWS::EFS::AccessPoint",
	"AWS::IAM::PolicyAttachment",
	"AWS::IAM::CredentialReport",
	"AWS::RDS::GlobalCluster",
	"AWS::CostExplorer::ForcastDaily",
	"AWS::GuardDuty::Detector",
	"AWS::SNS::Topic",
	"AWS::AppConfig::Application",
	"AWS::Batch::Job",
	"AWS::Batch::JobQueue",
	"AWS::ECS::Service",
	"AWS::FSX::Task",
	"AWS::IAM::VirtualMFADevice",
	"AWS::WAFv2::WebACL",
	"AWS::ApplicationAutoScaling::Target",
	"AWS::ApplicationAutoScaling::Policy",
	"AWS::Backup::Vault",
	"AWS::ElastiCache::Cluster",
	"AWS::Logs::LogGroup",
	"AWS::S3::Bucket",
	"AWS::S3::Object",
	"AWS::S3::BucketIntelligentTieringConfiguration",
	"AWS::S3::MultiRegionAccessPoint",
	"AWS::CertificateManager::Certificate",
	"AWS::EKS::AddonVersion",
	"AWS::ApiGatewayV2::Api",
	"AWS::EC2::Volume",
	"AWS::ApiGateway::ApiKey",
	"AWS::Glue::Connection",
	"AWS::ECS::Task",
	"AWS::SSM::ManagedInstance",
	"AWS::SSM::Inventory",
	"AWS::SSM::InventoryEntry",
	"AWS::SSM::MaintenanceWindow",
	"AWS::SSM::PatchBaseline",
	"AWS::SSM::Parameter",
	"AWS::Lambda::Function",
	"AWS::RDS::DBSnapshot",
	"AWS::CodeDeploy::Application",
	"AWS::CodeDeploy::DeploymentConfig",
	"AWS::EMR::Cluster",
	"AWS::IAM::AccessKey",
	"AWS::IAM::SSHPublicKey",
	"AWS::Glue::CatalogTable",
	"AWS::CloudTrail::Channel",
	"AWS::EC2::NetworkAcl",
	"AWS::ECS::ContainerInstance",
	"AWS::RedshiftServerless::Snapshot",
	"AWS::Workspaces::Bundle",
	"AWS::CloudTrail::Trail",
	"AWS::DAX::Parameter",
	"AWS::ECR::Image",
	"AWS::IAM::ServerCertificate",
	"AWS::Keyspaces::Keyspace",
	"AWS::S3::AccessPoint",
	"AWS::SageMaker::EndpointConfiguration",
	"AWS::ElastiCache::ReservedCacheNode",
	"AWS::EMR::InstanceFleet",
	"AWS::Account::Account",
	"AWS::EC2::VPCPeeringConnection",
	"AWS::EKS::FargateProfile",
	"AWS::IAM::AccountPasswordPolicy",
	"AWS::CodePipeline::Pipeline",
	"AWS::DAX::Cluster",
	"AWS::DLM::LifecyclePolicy",
	"AWS::OpsWorksCM::Server",
	"AWS::AccessAnalyzer::Analyzer",
	"AWS::AccessAnalyzer::Finding",
	"AWS::ElastiCache::SubnetGroup",
	"AWS::FSX::Volume",
	"AWS::Amplify::App",
	"AWS::CloudTrail::Query",
	"AWS::CostExplorer::ByAccountMonthly",
	"AWS::ECR::PublicRegistry",
	"AWS::EC2::NetworkInterface",
	"AWS::EC2::VPNConnection",
	"AWS::FSX::StorageVirtualMachine",
	"AWS::ApiGateway::Authorizer",
	"AWS::AppStream::Stack",
	"AWS::Athena::WorkGroup",
	"AWS::Athena::QueryExecution",
	"AWS::AppStream::Image",
	"AWS::CloudWatch::Alarm",
	"AWS::CloudWatch::LogSubscriptionFilter",
	"AWS::CostExplorer::ByRecordTypeMonthly",
	"AWS::RDS::DBCluster",
	"AWS::RDS::DBClusterSnapshot",
	"AWS::Backup::Framework",
	"AWS::CodeBuild::SourceCredential",
	"AWS::IAM::ServiceSpecificCredential",
	"AWS::EC2::CapacityReservationFleet",
	"AWS::NetworkFirewall::Firewall",
	"AWS::Workspaces::Workspace",
	"AWS::ElasticSearch::Domain",
	"AWS::RDS::DBInstance",
	"AWS::RDS::DBInstanceAutomatedBackup",
	"AWS::EFS::MountTarget",
	"AWS::GlobalAccelerator::Listener",
	"AWS::CostExplorer::ByUsageTypeDaily",
	"AWS::EKS::Addon",
	"AWS::CostExplorer::ByServiceMonthly",
	"AWS::IAM::Policy",
	"AWS::Redshift::Cluster",
	"AWS::WAFRegional::Rule",
	"AWS::WAFRegional::RuleGroup",
	"AWS::Glue::DataCatalogEncryptionSettings",
	"AWS::EC2::FlowLog",
	"AWS::EC2::IpamPool",
	"AWS::IAM::SamlProvider",
	"AWS::Route53::HostedZone",
	"AWS::Route53::QueryLog",
	"AWS::EC2::PlacementGroup",
	"AWS::FSX::Snapshot",
	"AWS::KMS::Key",
	"AWS::KMS::KeyRotation",
	"AWS::EC2::Ipam",
	"AWS::ElasticBeanstalk::Environment",
	"AWS::ElasticBeanstalk::ApplicationVersion",
	"AWS::Lambda::FunctionVersion",
	"AWS::Glue::DevEndpoint",
	"AWS::Backup::RecoveryPoint",
	"AWS::Backup::ReportPlan",
	"AWS::Backup::RegionSetting",
	"AWS::DynamoDbStreams::Stream",
	"AWS::EC2::EgressOnlyInternetGateway",
	"AWS::CloudFront::Distribution",
	"AWS::CloudFront::StreamingDistribution",
	"AWS::Glue::Job",
	"AWS::AppStream::Fleet",
	"AWS::SES::ConfigurationSet",
	"AWS::IAM::User",
	"AWS::CloudFront::OriginRequestPolicy",
	"AWS::EC2::SecurityGroup",
	"AWS::GuardDuty::IPSet",
	"AWS::EKS::Cluster",
	"AWS::Grafana::Workspace",
	"AWS::Glue::CatalogDatabase",
	"AWS::Health::Event",
	"AWS::Health::AffectedEntity",
	"AWS::CloudFormation::StackSet",
	"AWS::EC2::AvailabilityZone",
	"AWS::EC2::TransitGateway",
	"AWS::ApiGateway::UsagePlan",
	"AWS::Inspector::Finding",
	"AWS::EC2::Fleet",
	"AWS::ElasticBeanstalk::Application",
	"AWS::ElasticLoadBalancingV2::LoadBalancer",
	"AWS::OpenSearch::Domain",
	"AWS::RDS::DBEventSubscription",
	"AWS::RDS::DBEngineVersion",
	"AWS::EC2::RegionalSettings",
	"AWS::EC2::SecurityGroupRule",
	"AWS::EC2::TransitGatewayAttachment",
	"AWS::SES::Identity",
	"AWS::SESv2::EmailIdentities",
	"AWS::WAF::Rule",
	"AWS::WAF::RuleGroup",
	"AWS::WAF::RateBasedRule",
	"AWS::WAF::WebACL",
	"AWS::WAFRegional::WebACL",
	"AWS::WellArchitected::Workload",
	"AWS::WellArchitected::Answer",
	"AWS::WellArchitected::CheckDetail",
	"AWS::WellArchitected::CheckSummary",
	"AWS::WellArchitected::ConsolidatedReport",
	"AWS::WellArchitected::Lens",
	"AWS::WellArchitected::LensReview",
	"AWS::WellArchitected::LensReviewImprovement",
	"AWS::WellArchitected::LensReviewReport",
	"AWS::WellArchitected::LensShare",
	"AWS::WellArchitected::Milestone",
	"AWS::WellArchitected::Notification",
	"AWS::WellArchitected::ShareInvitation",
	"AWS::WellArchitected::WorkloadShare",
	"AWS::AutoScaling::LaunchConfiguration",
	"AWS::CloudTrail::EventDataStore",
	"AWS::CodeDeploy::DeploymentGroup",
	"AWS::ImageBuilder::Image",
	"AWS::Redshift::ClusterParameterGroup",
	"AWS::Account::AlternateContact",
	"AWS::Inspector::AssessmentTarget",
	"AWS::CloudFront::ResponseHeadersPolicy",
	"AWS::EC2::Instance",
	"AWS::EC2::InstanceMetricCpuUtilizationHourly",
	"AWS::EC2::InstanceAvailability",
	"AWS::CostExplorer::ByRecordTypeDaily",
	"AWS::EC2::ReservedInstances",
	"AWS::ECR::Repository",
	"AWS::ECR::Registry",
	"AWS::ECR::RegistryScanningConfiguration",
	"AWS::ElasticLoadBalancingV2::Listener",
	"AWS::IAM::Group",
	"AWS::IAM::OpenIdConnectProvider",
	"AWS::Backup::Plan",
	"AWS::Config::CompliancePack",
	"AWS::Config::RetentionConfiguration",
	"AWS::CostExplorer::ByAccountDaily",
	"AWS::Account::Contact",
	"AWS::Glue::DataQualityRuleset",
	"AWS::EventBridge::EventBus",
	"AWS::ApiGateway::Stage",
	"AWS::ApiGatewayV2::Stage",
	"AWS::DynamoDb::LocalSecondaryIndex",
	"AWS::ResourceGroups::Groups",
	"AWS::Timestream::Database",
	"AWS::OpenSearchServerless::Collection",
	"AWS::EC2::ElasticIP",
	"AWS::EC2::LocalGateway",
	"AWS::EC2::Image",
	"AWS::EC2::Subnet",
	"AWS::ECS::TaskSet",
	"AWS::Kinesis::Stream",
	"AWS::Kinesis::Consumer",
	"AWS::DocDB::Cluster",
	"AWS::DocDB::ClusterSnapshot",
	"AWS::DocDB::ClusterInstance",
	"AWS::ElastiCache::ReplicationGroup",
	"AWS::GlobalAccelerator::Accelerator",
	"AWS::CloudWatch::Metric",
	"AWS::CostExplorer::ForcastMonthly",
	"AWS::EMR::InstanceGroup",
	"AWS::EC2::ManagedPrefixList",
	"AWS::EC2::ManagedPrefixListEntry",
	"AWS::EC2::ClientVpnEndpoint",
	"AWS::MWAA::Environment",
	"AWS::CloudWatch::LogResourcePolicy",
	"AWS::CodeArtifact::Domain",
	"AWS::CodeStar::Project",
	"AWS::Neptune::Database",
	"AWS::Neptune::DBCluster",
	"AWS::Neptune::DBClusterSnapshot",
	"AWS::NetworkFirewall::FirewallPolicy",
	"AWS::NetworkFirewall::RuleGroup",
	"AWS::Oam::Link",
	"AWS::Oam::Sink",
	"AWS::Organizations::Account",
	"AWS::Pinpoint::App",
	"AWS::Pipes::Pipe",
	"AWS::RDS::DBClusterParameterGroup",
	"AWS::RDS::OptionGroup",
	"AWS::RDS::DBParameterGroup",
	"AWS::RDS::DBProxy",
	"AWS::RDS::DBSubnetGroup",
	"AWS::RDS::DBRecommendation",
	"AWS::Redshift::EventSubscription",
	"AWS::RedshiftServerless::Workgroup",
	"AWS::ResourceExplorer2::Index",
	"AWS::Route53::HealthCheck",
	"AWS::Route53Resolver::ResolverRule",
	"AWS::Route53Resolver::QueryLogConfig",
	"AWS::SageMaker::App",
	"AWS::SageMaker::Domain",
	"AWS::StepFunctions::StateMachine",
	"AWS::StepFunctions::StateMachineExecution",
	"AWS::StepFunctions::StateMachineExecutionHistories",
	"AWS::SimSpaceWeaver::Simulation",
	"AWS::SSM::Association",
	"AWS::SSM::Document",
	"AWS::SSM::DocumentPermission",
	"AWS::EC2::CustomerGateway",
	"AWS::EC2::VerifiedAccessInstance",
	"AWS::EC2::VerifiedAccessEndpoint",
	"AWS::EC2::VerifiedAccessGroup",
	"AWS::EC2::VerifiedAccessTrustProvider",
	"AWS::EC2::VPNGateway",
	"AWS::WAFv2::IPSet",
	"AWS::WAFv2::RegexPatternSet",
	"AWS::WAFv2::RuleGroup",
	"AWS::EC2::TransitGatewayRoute",
	"AWS::GuardDuty::Filter",
	"AWS::ECS::TaskDefinition",
	"AWS::GuardDuty::ThreatIntelSet",
	"AWS::ApiGatewayV2::DomainName",
	"AWS::ApiGateway::DomainName",
	"AWS::ApiGatewayV2::Route",
	"AWS::MQ::Broker",
	"AWS::ACMPCA::CertificateAuthority",
	"AWS::CloudFormation::Stack",
	"AWS::CloudFormation::StackResource",
	"AWS::DirectConnect::Connection",
	"AWS::FSX::FileSystem",
	"AWS::Glue::SecurityConfiguration",
	"AWS::Inspector::AssessmentRun",
	"AWS::Inspector2::Coverage",
	"AWS::Inspector2::CoverageStatistics",
	"AWS::Inspector2::Member",
	"AWS::Inspector2::Finding",
	"AWS::Config::ConfigurationRecorder",
	"AWS::EC2::NatGateway",
	"AWS::ECR::PublicRepository",
	"AWS::ECS::Cluster",
	"AWS::ElasticLoadBalancingV2::TargetGroup",
	"AWS::CloudFront::CachePolicy",
	"AWS::CodeArtifact::Repository",
	"AWS::AMP::Workspace",
	"AWS::EC2::CapacityReservation",
	"AWS::SageMaker::NotebookInstance",
	"AWS::IAM::AccessAdvisor",
	"AWS::EC2::VolumeSnapshot",
	"AWS::EC2::Region",
	"AWS::Keyspaces::Table",
	"AWS::Config::AggregationAuthorization",
	"AWS::DAX::SubnetGroup",
	"AWS::DynamoDb::GlobalTable",
	"AWS::ElasticLoadBalancing::LoadBalancer",
	"AWS::AppStream::Application",
	"AWS::RedshiftServerless::Namespace",
	"AWS::CloudFront::OriginAccessIdentity",
	"AWS::EC2::Host",
	"AWS::EC2::VPC",
	"AWS::EC2::TransitGatewayRouteTable",
	"AWS::EKS::Nodegroup",
	"AWS::Backup::Selection",
	"AWS::CloudTrail::Import",
	"AWS::CostExplorer::ByServiceDaily",
	"AWS::ElasticLoadBalancingV2::SslPolicy",
	"AWS::GuardDuty::Finding",
	"AWS::EC2::DHCPOptions",
	"AWS::EC2::InstanceType",
	"AWS::Batch::ComputeEnvironment",
	"AWS::DMS::ReplicationInstance",
	"AWS::DMS::Endpoint",
	"AWS::DMS::ReplicationTask",
	"AWS::DynamoDb::Table",
	"AWS::Shield::ProtectionGroup",
	"AWS::Firehose::DeliveryStream",
	"AWS::KinesisVideo::Stream",
	"AWS::KMS::Alias",
	"AWS::Lambda::Alias",
	"AWS::Lambda::LambdaLayer",
	"AWS::Lambda::LayerVersion",
	"AWS::Lightsail::Instance",
	"AWS::Macie2::ClassificationJob",
	"AWS::MediaStore::Container",
	"AWS::Mgn::Application",
	"AWS::ResourceExplorer2::SupportedResourceType",
	"AWS::Route53Resolver::ResolverEndpoint",
	"AWS::Route53Domains::Domain",
	"AWS::Route53::Record",
	"AWS::Route53::TrafficPolicy",
	"AWS::Route53::TrafficPolicyInstance",
	"AWS::SageMaker::Model",
	"AWS::SageMaker::TrainingJob",
	"AWS::SecurityHub::ActionTarget",
	"AWS::SecurityHub::Finding",
	"AWS::SecurityHub::FindingAggregator",
	"AWS::SecurityHub::Insight",
	"AWS::SecurityHub::Member",
	"AWS::SecurityHub::Product",
	"AWS::SecurityHub::StandardsControl",
	"AWS::SecurityHub::StandardsSubscription",
	"AWS::SecurityLake::DataLake",
	"AWS::SecurityLake::Subscriber",
	"AWS::Ram::PrincipalAssociation",
	"AWS::Ram::ResourceAssociation",
	"AWS::RDS::ReservedDBInstance",
	"AWS::Redshift::SubnetGroup",
	"AWS::SeverlessApplicationRepository::Application",
	"AWS::AuditManager::Framework",
	"AWS::AuditManager::EvidenceFolder",
	"AWS::AuditManager::Evidence",
	"AWS::AuditManager::Control",
	"AWS::AuditManager::Assessment",
	"AWS::CloudTrail::TrailEvent",
	"AWS::CloudWatch::LogEvent",
	"AWS::Logs::MetricFilter",
	"AWS::CloudWatch::LogStream",
	"AWS::CostExplorer::ByUsageTypeMonthly",
	"AWS::ServiceQuotas::ServiceQuotaChangeRequest",
	"AWS::ServiceQuotas::Service",
	"AWS::EC2::VPCEndpointService",
	"AWS::EC2::LaunchTemplate",
	"AWS::EC2::LaunchTemplateVersion",
	"AWS::SNS::Subscription",
	"AWS::S3::AccountSetting",
	"AWS::SSM::ManagedInstanceCompliance",
	"AWS::SSM::ManagedInstancePatchState",
	"AWS::SSOAdmin::AccountAssignment",
	"AWS::SSOAdmin::UserEffectiveAccess",
	"AWS::SSOAdmin::Instance",
	"AWS::SSOAdmin::PermissionSet",
	"AWS::SSOAdmin::AttachedManagedPolicy",
	"AWS::ServiceDiscovery::Service",
	"AWS::ServiceDiscovery::Namespace",
	"AWS::ServiceDiscovery::Instance",
	"AWS::ServiceCatalog::Portfolio",
	"AWS::ServiceCatalog::Product",
	"AWS::IdentityStore::User",
	"AWS::IdentityStore::Group",
	"AWS::IdentityStore::GroupMembership",
}
