package cloudservice

import (
	"strings"

	"gitlab.com/keibiengine/keibi-engine/pkg/source"
)

type ResourceType struct {
	Provider           source.Type
	ResourceTypePrefix string
	Service            string
	Category           string
	Common             bool
}

var mapping = []ResourceType{
	{"Azure", "Microsoft.AAD", "Azure Active Directory", "Identity", true},
	{"Azure", "Microsoft.Addons", "Azure Core", "Other", false},
	{"Azure", "Microsoft.App", "Azure Container Apps", "Container", true},
	{"Azure", "Microsoft.ADHybridHealthService - registered", "Azure Active Directory", "Identity", false},
	{"Azure", "Microsoft.Advisor", "Azure Advisor", "Security", false},
	{"Azure", "Microsoft.AlertsManagement", "Azure Monitor", "Monitoring", false},
	{"Azure", "Microsoft.AnalysisServices", "Azure Analysis Services", "Governance", false},
	{"Azure", "Microsoft.ApiManagement", "API Management", "Cloud App", true},
	{"Azure", "Microsoft.AppConfiguration", "Azure App Configuration", "Cloud App", false},
	{"Azure", "Microsoft.AppPlatform", "Azure Spring Cloud", "Cloud App", false},
	{"Azure", "Microsoft.Attestation", "Azure Attestation Service", "Governance", false},
	{"Azure", "Microsoft.Authorization - registered", "Azure Resource Manager", "Management", false},
	{"Azure", "Microsoft.Automation", "Automation", "Serverless", false},
	{"Azure", "Microsoft.AutonomousSystems", "Autonomous Systems", "Serverless", false},
	{"Azure", "Microsoft.AVS", "Azure VMware Solution", "Hybrid Cloud", false},
	{"Azure", "Microsoft.AzureActiveDirectory", "Azure Active Directory B2C", "Identity", true},
	{"Azure", "Microsoft.AzureArcData", "Azure Arc-enabled data services", "Database", false},
	{"Azure", "Microsoft.AzureData", "SQL Server registry", "Database", false},
	{"Azure", "Microsoft.AzureStack", "Azure Core", "Other", false},
	{"Azure", "Microsoft.AzureStackHCI", "Azure Stack HCI", "Other", false},
	{"Azure", "Microsoft.Batch", "Batch", "Serverless", true},
	{"Azure", "Microsoft.Billing - registered", "Cost Management and Billing", "Governance", false},
	{"Azure", "Microsoft.BingMaps", "Bing Maps", "Other", false},
	{"Azure", "Microsoft.Blockchain", "Azure Blockchain Service", "Other", false},
	{"Azure", "Microsoft.BlockchainTokens", "Azure Blockchain Tokens", "Other", false},
	{"Azure", "Microsoft.Blueprint", "Azure Blueprints", "Governance", false},
	{"Azure", "Microsoft.BotService", "Azure Bot Service", "Governance", false},
	{"Azure", "Microsoft.Cache", "Azure Cache for Redis", "Data Services", true},
	{"Azure", "Microsoft.Capacity", "Azure Core", "Other", false},
	{"Azure", "Microsoft.Cdn", "Content Delivery Network", "Networking", false},
	{"Azure", "Microsoft.CertificateRegistration", "App Service Certificates", "Cloud App", false},
	{"Azure", "Microsoft.ChangeAnalysis", "Azure Monitor", "Monitoring", false},
	{"Azure", "Microsoft.ClassicCompute", "Classic deployment model virtual machine", "Classic", true},
	{"Azure", "Microsoft.ClassicInfrastructureMigrate", "Classic deployment model migration", "Classic", false},
	{"Azure", "Microsoft.ClassicNetwork", "Classic deployment model virtual network", "Classic", true},
	{"Azure", "Microsoft.ClassicStorage", "Classic deployment model storage", "Classic", false},
	{"Azure", "Microsoft.ClassicSubscription - registered", "Classic deployment model", "Classic", false},
	{"Azure", "Microsoft.CognitiveServices", "Cognitive Services", "AI + ML", false},
	{"Azure", "Microsoft.Commerce - registered", "Azure Core", "Other", false},
	{"Azure", "Microsoft.Compute", "Virtual Machines", "Infrastructure", true},
	{"Azure", "Microsoft.Compute", "Virtual Machine Scale Sets", "Elastic Workload", true},
	{"Azure", "Microsoft.Consumption - registered", "Cost Management", "Governance", false},
	{"Azure", "Microsoft.ContainerInstance", "Container Instances", "Container", false},
	{"Azure", "Microsoft.ContainerRegistry", "Container Registry", "Container", true},
	{"Azure", "Microsoft.ContainerService", "Azure Kubernetes Service (AKS)", "Container", true},
	{"Azure", "Microsoft.CostManagement - registered", "Cost Management", "Governance", false},
	{"Azure", "Microsoft.CostManagementExports", "Cost Management", "Governance", false},
	{"Azure", "Microsoft.CustomerLockbox", "Customer Lockbox for Microsoft Azure", "Security", false},
	{"Azure", "Microsoft.CustomProviders", "Azure Custom Providers", "Governance", false},
	{"Azure", "Microsoft.DataBox", "Azure Data Box", "Data Services", false},
	{"Azure", "Microsoft.DataBoxEdge", "Azure Stack Edge", "Data Services", true},
	{"Azure", "Microsoft.Databricks", "Azure Databricks", "Data Services", false},
	{"Azure", "Microsoft.DataCatalog", "Data Catalog", "Data Services", false},
	{"Azure", "Microsoft.DataFactory", "Data Factory", "Data Services", false},
	{"Azure", "Microsoft.DataLakeAnalytics", "Data Lake Analytics", "Data Services", false},
	{"Azure", "Microsoft.DataLakeStore", "Azure Data Lake Storage Gen2", "Data Services", false},
	{"Azure", "Microsoft.DataMigration", "Azure Database Migration Service", "Data Services", false},
	{"Azure", "Microsoft.DataProtection", "Data Protection", "Security", false},
	{"Azure", "Microsoft.DataShare", "Azure Data Share", "Data Services", false},
	{"Azure", "Microsoft.DBforMariaDB", "Azure Database for MariaDB", "Database", true},
	{"Azure", "Microsoft.DBforMySQL", "Azure Database for MySQL", "Database", true},
	{"Azure", "Microsoft.DBforPostgreSQL", "Azure Database for PostgreSQL", "Database", true},
	{"Azure", "Microsoft.DesktopVirtualization", "Azure Virtual Desktop", "EUC", false},
	{"Azure", "Microsoft.Devices", "Azure IoT Hub", "IoT", false},
	{"Azure", "Microsoft.Devices", "Azure IoT Hub Device Provisioning Service", "IoT", false},
	{"Azure", "Microsoft.DeviceUpdate", "Device Update for IoT Hub", "IoT", false},
	{"Azure", "Microsoft.DevOps", "Azure DevOps", "DevOps", true},
	{"Azure", "Microsoft.DevSpaces", "Azure Dev Spaces", "DevOps", false},
	{"Azure", "Microsoft.DevTestLab", "Azure Lab Services", "DevOps", false},
	{"Azure", "Microsoft.DigitalTwins", "Azure Digital Twins", "Other", false},
	{"Azure", "Microsoft.DocumentDB", "Azure Cosmos DB", "Database", false},
	{"Azure", "Microsoft.DomainRegistration", "App Service", "Cloud App", true},
	{"Azure", "Microsoft.DynamicsLcs", "Lifecycle Services", "Database", false},
	{"Azure", "Microsoft.EnterpriseKnowledgeGraph", "Enterprise Knowledge Graph", "Database", false},
	{"Azure", "Microsoft.EventGrid", "Event Grid", "Messaging", true},
	{"Azure", "Microsoft.EventHub", "Event Hubs", "Messaging", true},
	{"Azure", "Microsoft.Features - registered", "Azure Resource Manager", "Governance", false},
	{"Azure", "Microsoft.GuestConfiguration", "Azure Policy", "Security", false},
	{"Azure", "Microsoft.HanaOnAzure", "SAP HANA on Azure Large Instances", "Other", false},
	{"Azure", "Microsoft.HardwareSecurityModules", "Azure Dedicated HSM", "Other", false},
	{"Azure", "Microsoft.HDInsight", "HDInsight", "Big Data", true},
	{"Azure", "Microsoft.HealthcareApis (Azure API for FHIR)", "Azure API for FHIR", "Governance", false},
	{"Azure", "Microsoft.HealthcareApis (Healthcare APIs)", "Healthcare APIs", "Governance", false},
	{"Azure", "Microsoft.HybridCompute", "Azure Arc-enabled servers", "Hybrid Cloud", false},
	{"Azure", "Microsoft.HybridData", "StorSimple", "Storage", false},
	{"Azure", "Microsoft.HybridNetwork", "Network Function Manager", "Networking", false},
	{"Azure", "Microsoft.ImportExport", "Azure Import/Export", "Hybrid Cloud", false},
	{"Azure", "Microsoft.Insights", "Azure Monitor", "Monitoring", false},
	{"Azure", "Microsoft.IoTCentral", "Azure IoT Central", "IoT", false},
	{"Azure", "Microsoft.IoTSpaces", "Azure Digital Twins", "IoT", false},
	{"Azure", "Microsoft.Intune", "Azure Monitor", "Monitoring", false},
	{"Azure", "Microsoft.KeyVault", "Key Vault", "Security", false},
	{"Azure", "Microsoft.Kubernetes", "Azure Arc-enabled Kubernetes", "Container", true},
	{"Azure", "Microsoft.KubernetesConfiguration", "Azure Arc-enabled Kubernetes", "Container", false},
	{"Azure", "Microsoft.Kusto", "Azure Data Explorer", "Data Services", false},
	{"Azure", "Microsoft.LabServices", "Azure Lab Services", "DevOps", false},
	{"Azure", "Microsoft.Logic", "Logic Apps", "Cloud App", true},
	{"Azure", "Microsoft.MachineLearning", "Machine Learning Studio", "AI + ML", false},
	{"Azure", "Microsoft.MachineLearningServices", "Azure Machine Learning", "AI + ML", false},
	{"Azure", "Microsoft.Maintenance", "Azure Maintenance", "Management", false},
	{"Azure", "Microsoft.ManagedIdentity", "Managed identities for Azure resources", "Identity", false},
	{"Azure", "Microsoft.ManagedNetwork", "Virtual networks managed by PaaS services", "Networking", false},
	{"Azure", "Microsoft.ManagedServices", "Azure Lighthouse", "Management", false},
	{"Azure", "Microsoft.Management", "Management Groups", "Management", true},
	{"Azure", "Microsoft.Maps", "Azure Maps", "SaaS", false},
	{"Azure", "Microsoft.Marketplace", "Azure Core", "Other", false},
	{"Azure", "Microsoft.MarketplaceApps", "Azure Core", "Other", false},
	{"Azure", "Microsoft.MarketplaceOrdering - registered", "Azure Core", "Other", false},
	{"Azure", "Microsoft.Media", "Media Services", "Media", false},
	{"Azure", "Microsoft.Microservices4Spring", "Azure Spring Cloud", "Cloud App", false},
	{"Azure", "Microsoft.Migrate", "Azure Migrate", "Migration", false},
	{"Azure", "Microsoft.MixedReality", "Azure Spatial Anchors", "AI + ML", false},
	{"Azure", "Microsoft.NetApp", "Azure NetApp Files", "Network Storage", true},
	{"Azure", "Microsoft.Network", "Application Gateway", "Networking", true},
	{"Azure", "Microsoft.Network", "Azure Bastion", "Networking", false},
	{"Azure", "Microsoft.Network", "Azure DDoS Protection", "Networking", false},
	{"Azure", "Microsoft.Network", "Azure DNS", "Networking", true},
	{"Azure", "Microsoft.Network", "Azure ExpressRoute", "Networking", true},
	{"Azure", "Microsoft.Network", "Azure Firewall", "Networking", true},
	{"Azure", "Microsoft.Network", "Azure Front Door Service", "Networking", true},
	{"Azure", "Microsoft.Network", "Azure Private Link", "Networking", true},
	{"Azure", "Microsoft.Network", "Azure Route Server", "Networking", true},
	{"Azure", "Microsoft.Network", "Load Balancer", "Networking", true},
	{"Azure", "Microsoft.Network", "Network Watcher", "Networking", true},
	{"Azure", "Microsoft.Network", "Traffic Manager", "Networking", true},
	{"Azure", "Microsoft.Network", "Virtual Network", "Networking", true},
	{"Azure", "Microsoft.Network", "Virtual Network NAT", "Networking", true},
	{"Azure", "Microsoft.Network", "Virtual WAN", "Networking", true},
	{"Azure", "Microsoft.Network", "VPN Gateway", "Networking", true},
	{"Azure", "Microsoft.Notebooks", "Azure Notebooks", "Other", false},
	{"Azure", "Microsoft.NotificationHubs", "Notification Hubs", "Monitoring", false},
	{"Azure", "Microsoft.ObjectStore", "Object Store", "Storage", false},
	{"Azure", "Microsoft.OffAzure", "Azure Migrate", "Migration", false},
	{"Azure", "Microsoft.OperationalInsights", "Azure Monitor", "Monitoring", true},
	{"Azure", "Microsoft.OperationsManagement", "Azure Monitor", "Monitoring", false},
	{"Azure", "Microsoft.Peering", "Azure Peering Service", "Networking", false},
	{"Azure", "Microsoft.PolicyInsights", "Azure Policy", "Governance", false},
	{"Azure", "Microsoft.Portal - registered", "Azure portal", "Other", false},
	{"Azure", "Microsoft.PowerBI", "Power BI", "Analytics", true},
	{"Azure", "Microsoft.PowerBIDedicated", "Power BI Embedded", "Analytics", false},
	{"Azure", "Microsoft.PowerPlatform", "Power Platform", "Analytics", false},
	{"Azure", "Microsoft.ProjectBabylon", "Azure Data Catalog", "Data Services", false},
	{"Azure", "Microsoft.Quantum", "Azure Quantum", "Data Services", false},
	{"Azure", "Microsoft.RecoveryServices", "Azure Site Recovery", "Resiliency", false},
	{"Azure", "Microsoft.RedHatOpenShift", "Azure Red Hat OpenShift", "Other", false},
	{"Azure", "Microsoft.Relay", "Azure Relay", "Other", false},
	{"Azure", "Microsoft.ResourceGraph - registered", "Azure Resource Graph", "Governance", false},
	{"Azure", "Microsoft.ResourceHealth", "Azure Service Health", "Monitoring", false},
	{"Azure", "Microsoft.Resources - registered", "Azure Resource Manager", "Other", false},
	{"Azure", "Microsoft.SaaS", "Azure Core", "Other", false},
	{"Azure", "Microsoft.Scheduler", "Scheduler", "Automation", false},
	{"Azure", "Microsoft.Search", "Azure Cognitive Search", "AI + ML", false},
	{"Azure", "Microsoft.Security", "Security Center", "Security", true},
	{"Azure", "Microsoft.SecurityInsights", "Microsoft Sentinel", "Security", true},
	{"Azure", "Microsoft.SerialConsole - registered", "Azure Serial Console for Windows", "Other", false},
	{"Azure", "Microsoft.ServiceBus", "Service Bus", "Messaging", true},
	{"Azure", "Microsoft.ServiceFabric", "Service Fabric", "Cloud App", true},
	{"Azure", "Microsoft.Services", "Azure Core", "Other", false},
	{"Azure", "Microsoft.SignalRService", "Azure SignalR Service", "AI + ML", false},
	{"Azure", "Microsoft.SoftwarePlan", "License", "Other", false},
	{"Azure", "Microsoft.Solutions", "Azure Managed Applications", "Other", true},
	{"Azure", "Microsoft.Sql", "Azure SQL Database", "Database", true},
	{"Azure", "Microsoft.Sql", "Azure SQL Managed Instance", "Database", true},
	{"Azure", "Microsoft.Sql", "Azure Synapse Analytics", "Database", false},
	{"Azure", "Microsoft.SqlVirtualMachine", "SQL Server on Azure Virtual Machines", "Database", true},
	{"Azure", "Microsoft.Storage", "Storage", "Storage", true},
	{"Azure", "Microsoft.StorageCache", "Azure HPC Cache", "Other", false},
	{"Azure", "Microsoft.StorageSync", "Storage", "Storage", false},
	{"Azure", "Microsoft.StorSimple", "StorSimple", "Storage", false},
	{"Azure", "Microsoft.StreamAnalytics", "Azure Stream Analytics", "Analytics", false},
	{"Azure", "Microsoft.Subscription", "Azure Core", "Subscription", false},
	{"Azure", "microsoft.support - registered", "Azure Core", "Other", false},
	{"Azure", "Microsoft.Synapse", "Azure Synapse Analytics", "Analytics", false},
	{"Azure", "Microsoft.TimeSeriesInsights", "Azure Time Series Insights", "Database", false},
	{"Azure", "Microsoft.Token", "Token", "Security", true},
	{"Azure", "Microsoft.VirtualMachineImages", "Azure Image Builder", "Infrastructure", false},
	{"Azure", "microsoft.visualstudio", "Azure DevOps", "DevOps", true},
	{"Azure", "Microsoft.VMware", "Azure VMware Solution", "Hybrid Cloud", false},
	{"Azure", "Microsoft.VMwareCloudSimple", "Azure VMware Solution by CloudSimple", "Hybrid Cloud", false},
	{"Azure", "Microsoft.VSOnline", "Azure DevOps", "DevOps", true},
	{"Azure", "Microsoft.Web", "App Service", "Cloud App", true},
	{"Azure", "Microsoft.Web", "Azure Functions", "Serverless", true},
	{"Azure", "Microsoft.WindowsDefenderATP", "Microsoft Defender Advanced Threat Protection", "Security", false},
	{"Azure", "Microsoft.WindowsESU", "Extended Security Updates", "Other", false},
	{"Azure", "Microsoft.WindowsIoT", "Windows 10 IoT Azure Core Services", "IoT", false},
	{"Azure", "Microsoft.WorkloadMonitor", "Azure Monitor", "Monitoring", true},
	{"AWS", "AWS::CertificateManager::Account", "Certificate Manager Account", "Security", false},
	{"AWS", "AWS::CertificateManager::Certificate", "Certificate Manager Certificate", "Security", true},
	{"AWS", "AWS::ACMPCA::Certificate", "Private Certificate Authority Certificate", "Security", true},
	{"AWS", "AWS::ACMPCA::CertificateAuthority", "Private Certificate Authority CertificateAuthority", "Security", false},
	{"AWS", "AWS::ACMPCA::CertificateAuthorityActivation", "Private Certificate Authority CertificateAuthorityActivation", "Security", false},
	{"AWS", "AWS::ACMPCA::Permission", "Private Certificate Authority Permission", "Security", false},
	{"AWS", "AWS::Amplify::App", "Amplify App", "DevOps", true},
	{"AWS", "AWS::Amplify::Branch", "Amplify Branch", "DevOps", false},
	{"AWS", "AWS::Amplify::Domain", "Amplify Domain", "DevOps", false},
	{"AWS", "AWS::AmplifyUIBuilder::Component", "AmplifyUIBuilder Component", "DevOps", false},
	{"AWS", "AWS::AmplifyUIBuilder::Theme", "AmplifyUIBuilder Theme", "DevOps", false},
	{"AWS", "AWS::ApiGateway::Account", "API Gateway Account", "Networking", true},
	{"AWS", "AWS::ApiGateway::ApiKey", "API Gateway ApiKey", "Networking", false},
	{"AWS", "AWS::ApiGateway::Authorizer", "API Gateway Authorizer", "Networking", false},
	{"AWS", "AWS::ApiGateway::BasePathMapping", "API Gateway BasePathMapping", "Networking", false},
	{"AWS", "AWS::ApiGateway::ClientCertificate", "API Gateway ClientCertificate", "Networking", false},
	{"AWS", "AWS::ApiGateway::Deployment", "API Gateway Deployment", "Networking", false},
	{"AWS", "AWS::ApiGateway::DocumentationPart", "API Gateway DocumentationPart", "Networking", false},
	{"AWS", "AWS::ApiGateway::DocumentationVersion", "API Gateway DocumentationVersion", "Networking", false},
	{"AWS", "AWS::ApiGateway::DomainName", "API Gateway DomainName", "Networking", false},
	{"AWS", "AWS::ApiGateway::GatewayResponse", "API Gateway GatewayResponse", "Networking", false},
	{"AWS", "AWS::ApiGateway::Method", "API Gateway Method", "Networking", false},
	{"AWS", "AWS::ApiGateway::Model", "API Gateway Model", "Networking", false},
	{"AWS", "AWS::ApiGateway::RequestValidator", "API Gateway RequestValidator", "Networking", false},
	{"AWS", "AWS::ApiGateway::Resource", "API Gateway Resource", "Networking", false},
	{"AWS", "AWS::ApiGateway::RestApi", "API Gateway RestApi", "Networking", false},
	{"AWS", "AWS::ApiGateway::Stage", "API Gateway Stage", "Networking", false},
	{"AWS", "AWS::ApiGateway::UsagePlan", "API Gateway UsagePlan", "Networking", false},
	{"AWS", "AWS::ApiGateway::UsagePlanKey", "API Gateway UsagePlanKey", "Networking", false},
	{"AWS", "AWS::ApiGateway::VpcLink", "API Gateway VpcLink", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::Api", "API Gateway V2 Api", "Networking", true},
	{"AWS", "AWS::ApiGatewayV2::ApiGatewayManagedOverrides", "API Gateway V2 ApiGatewayManagedOverrides", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::ApiMapping", "API Gateway V2 ApiMapping", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::Authorizer", "API Gateway V2 Authorizer", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::Deployment", "API Gateway V2 Deployment", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::DomainName", "API Gateway V2 DomainName", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::Integration", "API Gateway V2 Integration", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::IntegrationResponse", "API Gateway V2 IntegrationResponse", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::Model", "API Gateway V2 Model", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::Route", "API Gateway V2 Route", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::RouteResponse", "API Gateway V2 RouteResponse", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::Stage", "API Gateway V2 Stage", "Networking", false},
	{"AWS", "AWS::ApiGatewayV2::VpcLink", "API Gateway V2 VpcLink", "Networking", false},
	{"AWS", "AWS::AppConfig::Application", "AppConfig Application", "Governance", true},
	{"AWS", "AWS::AppConfig::ConfigurationProfile", "AppConfig ConfigurationProfile", "Governance", false},
	{"AWS", "AWS::AppConfig::Deployment", "AppConfig Deployment", "Governance", false},
	{"AWS", "AWS::AppConfig::DeploymentStrategy", "AppConfig DeploymentStrategy", "Governance", false},
	{"AWS", "AWS::AppConfig::Environment", "AppConfig Environment", "Governance", false},
	{"AWS", "AWS::AppConfig::HostedConfigurationVersion", "AppConfig HostedConfigurationVersion", "Governance", false},
	{"AWS", "AWS::AppFlow::ConnectorProfile", "AppFlow ConnectorProfile", "Cloud App", false},
	{"AWS", "AWS::AppFlow::Flow", "AppFlow Flow", "Cloud App", false},
	{"AWS", "AWS::AppIntegrations::EventIntegration", "AppIntegrations EventIntegration", "Cloud App", true},
	{"AWS", "AWS::ApplicationAutoScaling::ScalableTarget", "Application Auto Scaling ScalableTarget", "Cloud App", false},
	{"AWS", "AWS::ApplicationAutoScaling::ScalingPolicy", "Application Auto Scaling ScalingPolicy", "Cloud App", false},
	{"AWS", "AWS::AppMesh::GatewayRoute", "App Mesh GatewayRoute", "Cloud App", false},
	{"AWS", "AWS::AppMesh::Mesh", "App Mesh Mesh", "Cloud App", true},
	{"AWS", "AWS::AppMesh::Route", "App Mesh Route", "Cloud App", false},
	{"AWS", "AWS::AppMesh::VirtualGateway", "App Mesh VirtualGateway", "Cloud App", false},
	{"AWS", "AWS::AppMesh::VirtualNode", "App Mesh VirtualNode", "Cloud App", false},
	{"AWS", "AWS::AppMesh::VirtualRouter", "App Mesh VirtualRouter", "Cloud App", false},
	{"AWS", "AWS::AppMesh::VirtualService", "App Mesh VirtualService", "Cloud App", false},
	{"AWS", "AWS::AppRunner::Connection", "App Runner Connection", "Cloud App", false},
	{"AWS", "AWS::AppRunner::autoscalingconfiguration", "App Runner Autoscaling Configuration", "Cloud App", false},
	{"AWS", "AWS::AppRunner::Service", "App Runner Service", "Cloud App", false},
	{"AWS", "AWS::AppSync::ApiCache", "AppSync ApiCache", "EUC", false},
	{"AWS", "AWS::AppSync::ApiKey", "AppSync ApiKey", "EUC", false},
	{"AWS", "AWS::AppSync::DataSource", "AppSync DataSource", "EUC", false},
	{"AWS", "AWS::AppSync::DomainName", "AppSync DomainName", "EUC", false},
	{"AWS", "AWS::AppSync::DomainNameApiAssociation", "AppSync DomainNameApiAssociation", "EUC", false},
	{"AWS", "AWS::AppSync::FunctionConfiguration", "AppSync FunctionConfiguration", "EUC", false},
	{"AWS", "AWS::AppSync::GraphQLApi", "AppSync GraphQLApi", "EUC", false},
	{"AWS", "AWS::AppSync::GraphQLSchema", "AppSync GraphQLSchema", "EUC", false},
	{"AWS", "AWS::AppSync::Resolver", "AppSync Resolver", "EUC", false},
	{"AWS", "AWS::APS::RuleGroupsNamespace", "Managed Prometheus RuleGroupsNamespace", "Monitoring", false},
	{"AWS", "AWS::APS::Workspace", "Managed Prometheus Workspace", "Monitoring", true},
	{"AWS", "AWS::SSO::Assignment", "AWS SSO Assignment", "Identity", false},
	{"AWS", "AWS::SSO::InstanceAccessControlAttributeConfiguration", "AWS SSO InstanceAccessControlAttributeConfiguration", "Identity", false},
	{"AWS", "AWS::SSO::PermissionSet", "AWS SSO PermissionSet", "Identity", false},
	{"AWS", "AWS::StepFunctions::Activity", "Step Functions Activity", "Automation", false},
	{"AWS", "AWS::StepFunctions::StateMachine", "Step Functions StateMachine", "Automation", false},
	{"AWS", "AWS::SSM::Association", "SSM Association", "Management", false},
	{"AWS", "AWS::SSM::Document", "SSM Document", "Management", true},
	{"AWS", "AWS::SSM::MaintenanceWindow", "SSM MaintenanceWindow", "Management", false},
	{"AWS", "AWS::SSM::MaintenanceWindowTarget", "SSM MaintenanceWindowTarget", "Management", false},
	{"AWS", "AWS::SSM::MaintenanceWindowTask", "SSM MaintenanceWindowTask", "Management", false},
	{"AWS", "AWS::SSM::Parameter", "SSM Parameter", "Management", false},
	{"AWS", "AWS::SSM::PatchBaseline", "SSM PatchBaseline", "Management", false},
	{"AWS", "AWS::SSM::ResourceDataSync", "SSM ResourceDataSync", "Management", false},
	{"AWS", "AWS::Timestream::Database", "Timestream Database", "Database", true},
	{"AWS", "AWS::Timestream::ScheduledQuery", "Timestream ScheduledQuery", "Database", false},
	{"AWS", "AWS::Timestream::Table", "Timestream Table", "Database", false},
	{"AWS", "AWS::Transfer::Server", "Transfer Server", "Migration", true},
	{"AWS", "AWS::Transfer::User", "Transfer User", "Migration", false},
	{"AWS", "AWS::Transfer::Workflow", "Transfer Workflow", "Migration", false},
	{"AWS", "AWS::WAF::ByteMatchSet", "WAF v1 ByteMatchSet", "Security", false},
	{"AWS", "AWS::WAF::IPSet", "WAF v1 IPSet", "Security", false},
	{"AWS", "AWS::WAF::Rule", "WAF v1 Rule", "Security", false},
	{"AWS", "AWS::WAF::SizeConstraintSet", "WAF v1 SizeConstraintSet", "Security", false},
	{"AWS", "AWS::WAF::SqlInjectionMatchSet", "WAF v1 SqlInjectionMatchSet", "Security", false},
	{"AWS", "AWS::WAF::WebACL", "WAF v1 WebACL", "Security", false},
	{"AWS", "AWS::WAF::XssMatchSet", "WAF v1 XssMatchSet", "Security", false},
	{"AWS", "AWS::WAFRegional::ByteMatchSet", "Regional WAF ByteMatchSet", "Security", false},
	{"AWS", "AWS::WAFRegional::GeoMatchSet", "Regional WAF GeoMatchSet", "Security", false},
	{"AWS", "AWS::WAFRegional::IPSet", "Regional WAF IPSet", "Security", false},
	{"AWS", "AWS::WAFRegional::RateBasedRule", "Regional WAF RateBasedRule", "Security", false},
	{"AWS", "AWS::WAFRegional::RegexPatternSet", "Regional WAF RegexPatternSet", "Security", false},
	{"AWS", "AWS::WAFRegional::Rule", "Regional WAF Rule", "Security", false},
	{"AWS", "AWS::WAFRegional::SizeConstraintSet", "Regional WAF SizeConstraintSet", "Security", false},
	{"AWS", "AWS::WAFRegional::SqlInjectionMatchSet", "Regional WAF SqlInjectionMatchSet", "Security", false},
	{"AWS", "AWS::WAFRegional::WebACL", "Regional WAF WebACL", "Security", false},
	{"AWS", "AWS::WAFRegional::WebACLAssociation", "Regional WAF WebACLAssociation", "Security", false},
	{"AWS", "AWS::WAFRegional::XssMatchSet", "Regional WAF XssMatchSet", "Security", false},
	{"AWS", "AWS::WAFv2::IPSet", "WAF v2 IPSet", "Security", false},
	{"AWS", "AWS::WAFv2::LoggingConfiguration", "WAF v2 LoggingConfiguration", "Security", false},
	{"AWS", "AWS::WAFv2::RegexPatternSet", "WAF v2 RegexPatternSet", "Security", false},
	{"AWS", "AWS::WAFv2::RuleGroup", "WAF v2 RuleGroup", "Security", false},
	{"AWS", "AWS::WAFv2::WebACL", "WAF v2 WebACL", "Security", false},
	{"AWS", "AWS::WAFv2::WebACLAssociation", "WAF v2 WebACLAssociation", "Security", false},
	{"AWS", "AWS::Wisdom::Assistant", "Wisdom Assistant", "Other", false},
	{"AWS", "AWS::Wisdom::AssistantAssociation", "Wisdom AssistantAssociation", "Other", false},
	{"AWS", "AWS::Wisdom::KnowledgeBase", "Wisdom KnowledgeBase", "Other", false},
	{"AWS", "AWS::WorkSpaces::ConnectionAlias", "WorkSpaces ConnectionAlias", "EUC", false},
	{"AWS", "AWS::WorkSpaces::Workspace", "WorkSpaces Workspace", "EUC", false},
	{"AWS", "AWS::XRay::Group", "XRay Group", "Monitoring", false},
	{"AWS", "AWS::XRay::SamplingRule", "XRay SamplingRule", "Monitoring", false},
	{"AWS", "AWS::EC2::CapacityReservation", "EC2 CapacityReservation", "Infrastructure", false},
	{"AWS", "AWS::EC2::CapacityReservationFleet", "EC2 CapacityReservationFleet", "Infrastructure", false},
	{"AWS", "AWS::EC2::CarrierGateway", "EC2 CarrierGateway", "Networking", false},
	{"AWS", "AWS::EC2::ClientVpnAuthorizationRule", "EC2 ClientVpnAuthorizationRule", "Networking", false},
	{"AWS", "AWS::EC2::ClientVpnEndpoint", "EC2 ClientVpnEndpoint", "Networking", false},
	{"AWS", "AWS::EC2::ClientVpnRoute", "EC2 ClientVpnRoute", "Networking", false},
	{"AWS", "AWS::EC2::ClientVpnTargetNetworkAssociation", "EC2 ClientVpnTargetNetworkAssociation", "Networking", false},
	{"AWS", "AWS::EC2::CustomerGateway", "EC2 CustomerGateway", "Networking", true},
	{"AWS", "AWS::EC2::DHCPOptions", "EC2 DHCPOptions", "Networking", true},
	{"AWS", "AWS::EC2::EC2Fleet", "EC2 Fleet", "Infrastructure", true},
	{"AWS", "AWS::EC2::EgressOnlyInternetGateway", "EC2 EgressOnlyInternetGateway", "Networking", true},
	{"AWS", "AWS::EC2::EIP", "EC2 EIP", "Networking", true},
	{"AWS", "AWS::EC2::EIPAssociation", "EC2 EIPAssociation", "Networking", false},
	{"AWS", "AWS::EC2::EnclaveCertificateIamRoleAssociation", "EC2 EnclaveCertificateIamRoleAssociation", "Networking", false},
	{"AWS", "AWS::EC2::FlowLog", "EC2 FlowLog", "Security", true},
	{"AWS", "AWS::EC2::GatewayRouteTableAssociation", "EC2 GatewayRouteTableAssociation", "Networking", false},
	{"AWS", "AWS::EC2::Host", "EC2 Host", "Infrastructure", true},
	{"AWS", "AWS::EC2::Instance", "EC2 Instance", "Infrastructure", true},
	{"AWS", "AWS::EC2::InternetGateway", "EC2 InternetGateway", "Networking", true},
	{"AWS", "AWS::EC2::IPAM", "EC2 IPAM", "Networking", true},
	{"AWS", "AWS::EC2::IPAMAllocation", "EC2 IPAMAllocation", "Networking", false},
	{"AWS", "AWS::EC2::IPAMPool", "EC2 IPAM Pool", "Networking", false},
	{"AWS", "AWS::EC2::IPAMScope", "EC2 IPAM Scope", "Networking", false},
	{"AWS", "AWS::EC2::LaunchTemplate", "EC2 LaunchTemplate", "Infrastructure", false},
	{"AWS", "AWS::EC2::LocalGatewayRoute", "EC2 LocalGatewayRoute", "Networking", false},
	{"AWS", "AWS::EC2::LocalGatewayRouteTableVPCAssociation", "EC2 LocalGatewayRouteTableVPCAssociation", "Networking", false},
	{"AWS", "AWS::EC2::NatGateway", "EC2 NatGateway", "Networking", true},
	{"AWS", "AWS::EC2::NetworkAcl", "EC2 NetworkAcl", "Networking", true},
	{"AWS", "AWS::EC2::NetworkAclEntry", "EC2 NetworkAclEntry", "Networking", false},
	{"AWS", "AWS::EC2::NetworkInsightsAccessScope", "EC2 NetworkInsightsAccessScope", "Networking", false},
	{"AWS", "AWS::EC2::NetworkInsightsAccessScopeAnalysis", "EC2 NetworkInsightsAccessScopeAnalysis", "Networking", false},
	{"AWS", "AWS::EC2::NetworkInsightsAnalysis", "EC2 NetworkInsightsAnalysis", "Networking", false},
	{"AWS", "AWS::EC2::NetworkInsightsPath", "EC2 NetworkInsightsPath", "Networking", false},
	{"AWS", "AWS::EC2::NetworkInterface", "EC2 NetworkInterface", "Networking", true},
	{"AWS", "AWS::EC2::NetworkInterfaceAttachment", "EC2 NetworkInterfaceAttachment", "Networking", false},
	{"AWS", "AWS::EC2::NetworkInterfacePermission", "EC2 NetworkInterfacePermission", "Networking", false},
	{"AWS", "AWS::EC2::PlacementGroup", "EC2 PlacementGroup", "Infrastructure", false},
	{"AWS", "AWS::EC2::PrefixList", "EC2 PrefixList", "Infrastructure", false},
	{"AWS", "AWS::EC2::Route", "EC2 Route", "Networking", false},
	{"AWS", "AWS::EC2::RouteTable", "EC2 RouteTable", "Networking", true},
	{"AWS", "AWS::EC2::SecurityGroup", "EC2 SecurityGroup", "Security", true},
	{"AWS", "AWS::EC2::SecurityGroupEgress", "EC2 SecurityGroupEgress", "Security", false},
	{"AWS", "AWS::EC2::SecurityGroupIngress", "EC2 SecurityGroupIngress", "Security", false},
	{"AWS", "AWS::EC2::SpotFleet", "EC2 SpotFleet", "Networking", false},
	{"AWS", "AWS::EC2::Subnet", "EC2 Subnet", "Networking", true},
	{"AWS", "AWS::EC2::SubnetCidrBlock", "EC2 SubnetCidrBlock", "Networking", false},
	{"AWS", "AWS::EC2::SubnetNetworkAclAssociation", "EC2 SubnetNetworkAclAssociation", "Networking", false},
	{"AWS", "AWS::EC2::SubnetRouteTableAssociation", "EC2 SubnetRouteTableAssociation", "Networking", false},
	{"AWS", "AWS::EC2::TrafficMirrorFilter", "EC2 TrafficMirrorFilter", "Networking", false},
	{"AWS", "AWS::EC2::TrafficMirrorFilterRule", "EC2 TrafficMirrorFilterRule", "Networking", false},
	{"AWS", "AWS::EC2::TrafficMirrorSession", "EC2 TrafficMirrorSession", "Networking", false},
	{"AWS", "AWS::EC2::TrafficMirrorTarget", "EC2 TrafficMirrorTarget", "Networking", false},
	{"AWS", "AWS::EC2::TransitGateway", "EC2 TransitGateway", "Networking", true},
	{"AWS", "AWS::EC2::TransitGatewayAttachment", "EC2 TransitGatewayAttachment", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayConnect", "EC2 TransitGatewayConnect", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayMulticastDomain", "EC2 TransitGatewayMulticastDomain", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayMulticastDomainAssociation", "EC2 TransitGatewayMulticastDomainAssociation", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayMulticastGroupMember", "EC2 TransitGatewayMulticastGroupMember", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayMulticastGroupSource", "EC2 TransitGatewayMulticastGroupSource", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayPeeringAttachment", "EC2 TransitGatewayPeeringAttachment", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayRoute", "EC2 TransitGatewayRoute", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayRouteTable", "EC2 TransitGatewayRouteTable", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayRouteTableAssociation", "EC2 TransitGatewayRouteTableAssociation", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayRouteTablePropagation", "EC2 TransitGatewayRouteTablePropagation", "Networking", false},
	{"AWS", "AWS::EC2::TransitGatewayVpcAttachment", "EC2 TransitGatewayVpcAttachment", "Networking", false},
	{"AWS", "AWS::EC2::Volume", "EC2 Volume", "Storage", true},
	{"AWS", "AWS::EC2::VolumeAttachment", "EC2 VolumeAttachment", "Storage", false},
	{"AWS", "AWS::EC2::VPC", "EC2 VPC", "Networking", true},
	{"AWS", "AWS::EC2::VPCCidrBlock", "EC2 VPCCidrBlock", "Networking", false},
	{"AWS", "AWS::EC2::VPCDHCPOptionsAssociation", "EC2 VPCDHCPOptionsAssociation", "Networking", false},
	{"AWS", "AWS::EC2::VPCEndpoint", "EC2 VPCEndpoint", "Networking", false},
	{"AWS", "AWS::EC2::VPCEndpointConnectionNotification", "EC2 VPCEndpointConnectionNotification", "Networking", false},
	{"AWS", "AWS::EC2::VPCEndpointService", "EC2 VPCEndpointService", "Networking", false},
	{"AWS", "AWS::EC2::VPCEndpointServicePermissions", "EC2 VPCEndpointServicePermissions", "Networking", false},
	{"AWS", "AWS::EC2::VPCGatewayAttachment", "EC2 VPCGatewayAttachment", "Networking", false},
	{"AWS", "AWS::EC2::VPCPeeringConnection", "EC2 VPCPeeringConnection", "Networking", false},
	{"AWS", "AWS::EC2::VPNConnection", "EC2 VPNConnection", "Networking", false},
	{"AWS", "AWS::EC2::VPNConnectionRoute", "EC2 VPNConnectionRoute", "Networking", false},
	{"AWS", "AWS::EC2::VPNGateway", "EC2 VPNGateway", "Networking", false},
	{"AWS", "AWS::EC2::VPNGatewayRoutePropagation", "EC2 VPNGatewayRoutePropagation", "Networking", false},
	{"AWS", "AWS::AutoScaling::AutoScalingGroup", "Auto Scaling Group", "Elastic Workload", true},
	{"AWS", "AWS::AutoScaling::LaunchConfiguration", "Auto Scaling LaunchConfiguration", "Elastic Workload", false},
	{"AWS", "AWS::AutoScaling::LifecycleHook", "Auto Scaling LifecycleHook", "Elastic Workload", false},
	{"AWS", "AWS::AutoScaling::ScalingPolicy", "Auto Scaling ScalingPolicy", "Elastic Workload", false},
	{"AWS", "AWS::AutoScaling::ScheduledAction", "Auto Scaling ScheduledAction", "Elastic Workload", false},
	{"AWS", "AWS::AutoScaling::WarmPool", "Auto Scaling WarmPool", "Elastic Workload", false},
	{"AWS", "AWS::ECR::PublicRepository", "ECR PublicRepository", "Container", true},
	{"AWS", "AWS::ECR::RegistryPolicy", "ECR RegistryPolicy", "Container", false},
	{"AWS", "AWS::ECR::ReplicationConfiguration", "ECR ReplicationConfiguration", "Container", false},
	{"AWS", "AWS::ECR::Repository", "ECR Repository", "Container", true},
	{"AWS", "AWS::ECS::CapacityProvider", "ECS CapacityProvider", "Container", false},
	{"AWS", "AWS::ECS::Cluster", "ECS Cluster", "Container", true},
	{"AWS", "AWS::ECS::ClusterCapacityProviderAssociations", "ECS ClusterCapacityProviderAssociations", "Container", false},
	{"AWS", "AWS::ECS::PrimaryTaskSet", "ECS PrimaryTaskSet", "Container", false},
	{"AWS", "AWS::ECS::Service", "ECS Service", "Container", true},
	{"AWS", "AWS::ECS::TaskDefinition", "ECS TaskDefinition", "Container", false},
	{"AWS", "AWS::ECS::TaskSet", "ECS TaskSet", "Container", false},
	{"AWS", "AWS::EFS::AccessPoint", "EFS AccessPoint", "Container", false},
	{"AWS", "AWS::EFS::FileSystem", "EFS FileSystem", "Container", false},
	{"AWS", "AWS::EFS::MountTarget", "EFS MountTarget", "Container", false},
	{"AWS", "AWS::EFS::AccessPoint", "EFS AccessPoint", "Container", false},
	{"AWS", "AWS::EFS::FileSystem", "EFS FileSystem", "Container", false},
	{"AWS", "AWS::EFS::MountTarget", "EFS MountTarget", "Container", false},
	{"AWS", "AWS::EKS::Addon", "EKS Addon", "Container", false},
	{"AWS", "AWS::EKS::Cluster", "EKS Cluster", "Container", true},
	{"AWS", "AWS::EKS::FargateProfile", "EKS FargateProfile", "Container", false},
	{"AWS", "AWS::EKS::Nodegroup", "EKS Nodegroup", "Container", false},
	{"AWS", "AWS::ElasticBeanstalk::Application", "Elastic Beanstalk Application", "Cloud App", true},
	{"AWS", "AWS::ElasticBeanstalk::ApplicationVersion", "Elastic Beanstalk ApplicationVersion", "Cloud App", false},
	{"AWS", "AWS::ElasticBeanstalk::ConfigurationTemplate", "Elastic Beanstalk ConfigurationTemplate", "Cloud App", false},
	{"AWS", "AWS::ElasticBeanstalk::Environment", "Elastic Beanstalk Environment", "Cloud App", false},
	{"AWS", "AWS::elasticfilesystem::", "Elastic Fileshare", "Managed Fileshare", true},
	{"AWS", "AWS::ElasticLoadBalancing::LoadBalancer", "ELB LoadBalancer", "Networking", true},
	{"AWS", "AWS::ElasticLoadBalancingV2::Listener", "ELB v2 Listener", "Networking", false},
	{"AWS", "AWS::ElasticLoadBalancingV2::ListenerCertificate", "ELB v2 ListenerCertificate", "Networking", false},
	{"AWS", "AWS::ElasticLoadBalancingV2::ListenerRule", "ELB v2 ListenerRule", "Networking", false},
	{"AWS", "AWS::ElasticLoadBalancingV2::LoadBalancer", "ELB v2 LoadBalancer", "Networking", true},
	{"AWS", "AWS::ElasticLoadBalancingV2::TargetGroup", "ELB v2 TargetGroup", "Networking", false},
	{"AWS", "AWS::EMR::Cluster", "EMR Cluster", "Big data", true},
	{"AWS", "AWS::EMR::InstanceFleetConfig", "EMR InstanceFleetConfig", "Big data", false},
	{"AWS", "AWS::EMR::InstanceGroupConfig", "EMR InstanceGroupConfig", "Big data", false},
	{"AWS", "AWS::EMR::SecurityConfiguration", "EMR SecurityConfiguration", "Big data", false},
	{"AWS", "AWS::EMR::Step", "EMR Step", "Big data", true},
	{"AWS", "AWS::EMR::Studio", "EMR Studio", "Big data", true},
	{"AWS", "AWS::EMR::StudioSessionMapping", "EMR StudioSessionMapping", "Big data", false},
	{"AWS", "AWS::EMRContainers::VirtualCluster", "EMR Containers VirtualCluster", "Big data", false},
	{"AWS", "AWS::ElastiCache::CacheCluster", "ElastiCache CacheCluster", "Data Service", true},
	{"AWS", "AWS::ElastiCache::GlobalReplicationGroup", "ElastiCache GlobalReplicationGroup", "Data Service", false},
	{"AWS", "AWS::ElastiCache::ParameterGroup", "ElastiCache ParameterGroup", "Data Service", false},
	{"AWS", "AWS::ElastiCache::ReplicationGroup", "ElastiCache ReplicationGroup", "Data Service", false},
	{"AWS", "AWS::ElastiCache::SecurityGroup", "ElastiCache SecurityGroup", "Data Service", true},
	{"AWS", "AWS::ElastiCache::SecurityGroupIngress", "ElastiCache SecurityGroupIngress", "Data Service", false},
	{"AWS", "AWS::ElastiCache::SubnetGroup", "ElastiCache SubnetGroup", "Data Service", true},
	{"AWS", "AWS::ElastiCache::User", "ElastiCache User", "Data Service", false},
	{"AWS", "AWS::ElastiCache::UserGroup", "ElastiCache UserGroup", "Data Service", false},
	{"AWS", "AWS::Events::ApiDestination", "Events ApiDestination", "Messaging", false},
	{"AWS", "AWS::Events::Archive", "Events Archive", "Messaging", false},
	{"AWS", "AWS::Events::Connection", "Events Connection", "Messaging", false},
	{"AWS", "AWS::Events::EventBus", "Events EventBus", "Messaging", true},
	{"AWS", "AWS::Events::EventBusPolicy", "Events EventBusPolicy", "Messaging", false},
	{"AWS", "AWS::Events::Rule", "Events Rule", "Messaging", false},
	{"AWS", "AWS::EventSchemas::Discoverer", "Event Schemas Discoverer", "Messaging", false},
	{"AWS", "AWS::EventSchemas::Registry", "Event Schemas Registry", "Messaging", true},
	{"AWS", "AWS::EventSchemas::RegistryPolicy", "Event Schemas RegistryPolicy", "Messaging", false},
	{"AWS", "AWS::EventSchemas::Schema", "Event Schemas Schema", "Messaging", false},
	{"AWS", "AWS::Evidently::Experiment", "Evidently Experiment", "Other", false},
	{"AWS", "AWS::Evidently::Feature", "Evidently Feature", "Other", false},
	{"AWS", "AWS::Evidently::Launch", "Evidently Launch", "Other", false},
	{"AWS", "AWS::Evidently::Project", "Evidently Project", "Other", true},
	{"AWS", "AWS::FinSpace::Environment", "FinSpace Environment", "Other", false},
	{"AWS", "AWS::FIS::ExperimentTemplate", "Fault Injection Simulator ExperimentTemplate", "Other", false},
	{"AWS", "AWS::FMS::NotificationChannelAWS::FMS::Policy", "Firewall Manager NotificationChannelAWS::FMS::Policy", "Other", false},
	{"AWS", "AWS::FraudDetector::Detector", "FraudDetector Detector", "Other", false},
	{"AWS", "AWS::FraudDetector::EntityType", "FraudDetector EntityType", "Other", false},
	{"AWS", "AWS::FraudDetector::EventType", "FraudDetector EventType", "Other", false},
	{"AWS", "AWS::FraudDetector::Label", "FraudDetector Label", "Other", false},
	{"AWS", "AWS::FraudDetector::Outcome", "FraudDetector Outcome", "Other", false},
	{"AWS", "AWS::FraudDetector::Variable", "FraudDetector Variable", "Other", false},
	{"AWS", "AWS::FSx::FileSystem", "FSx FileSystem", "Storage", true},
	{"AWS", "AWS::FSx::Snapshot", "FSx Snapshot", "Storage", false},
	{"AWS", "AWS::FSx::StorageVirtualMachine", "FSx StorageVirtualMachine", "Storage", false},
	{"AWS", "AWS::FSx::Volume", "FSx Volume", "Storage", true},
	{"AWS", "AWS::GameLift::Alias", "GameLift Alias", "Gaming", false},
	{"AWS", "AWS::GameLift::Build", "GameLift Build", "Gaming", false},
	{"AWS", "AWS::GameLift::Fleet", "GameLift Fleet", "Gaming", false},
	{"AWS", "AWS::GameLift::GameServerGroup", "GameLift GameServerGroup", "Gaming", false},
	{"AWS", "AWS::GameLift::GameSessionQueue", "GameLift GameSessionQueue", "Gaming", false},
	{"AWS", "AWS::GameLift::MatchmakingConfiguration", "GameLift MatchmakingConfiguration", "Gaming", false},
	{"AWS", "AWS::GameLift::MatchmakingRuleSet", "GameLift MatchmakingRuleSet", "Gaming", false},
	{"AWS", "AWS::GameLift::Script", "GameLift Script", "Gaming", false},
	{"AWS", "AWS::GlobalAccelerator::Accelerator", "Global Accelerator Accelerator", "Networking", true},
	{"AWS", "AWS::GlobalAccelerator::EndpointGroup", "Global Accelerator EndpointGroup", "Networking", false},
	{"AWS", "AWS::GlobalAccelerator::Listener", "Global Accelerator Listener", "Networking", false},
	{"AWS", "AWS::Glue::Classifier", "Glue Classifier", "Serverless", false},
	{"AWS", "AWS::Glue::Connection", "Glue Connection", "Serverless", false},
	{"AWS", "AWS::Glue::Crawler", "Glue Crawler", "Serverless", false},
	{"AWS", "AWS::Glue::Database", "Glue Database", "Serverless", true},
	{"AWS", "AWS::Glue::DataCatalogEncryptionSettings", "Glue DataCatalogEncryptionSettings", "Serverless", false},
	{"AWS", "AWS::Glue::DevEndpoint", "Glue DevEndpoint", "Serverless", false},
	{"AWS", "AWS::Glue::Job", "Glue Job", "Serverless", false},
	{"AWS", "AWS::Glue::MLTransform", "Glue MLTransform", "Serverless", false},
	{"AWS", "AWS::Glue::Partition", "Glue Partition", "Serverless", false},
	{"AWS", "AWS::Glue::Registry", "Glue Registry", "Serverless", false},
	{"AWS", "AWS::Glue::Schema", "Glue Schema", "Serverless", false},
	{"AWS", "AWS::Glue::SchemaVersion", "Glue SchemaVersion", "Serverless", false},
	{"AWS", "AWS::Glue::SchemaVersionMetadata", "Glue SchemaVersionMetadata", "Serverless", false},
	{"AWS", "AWS::Glue::SecurityConfiguration", "Glue SecurityConfiguration", "Serverless", false},
	{"AWS", "AWS::Glue::Table", "Glue Table", "Serverless", false},
	{"AWS", "AWS::Glue::Trigger", "Glue Trigger", "Serverless", false},
	{"AWS", "AWS::Glue::Workflow", "Glue Workflow", "Serverless", false},
	{"AWS", "AWS::GroundStation::Config", "GroundStation Config", "Other", false},
	{"AWS", "AWS::GroundStation::DataflowEndpointGroup", "GroundStation DataflowEndpointGroup", "Other", false},
	{"AWS", "AWS::GroundStation::MissionProfile", "GroundStation MissionProfile", "Other", false},
	{"AWS", "AWS::GuardDuty::Detector", "GuardDuty Detector", "Security", true},
	{"AWS", "AWS::GuardDuty::Filter", "GuardDuty Filter", "Security", false},
	{"AWS", "AWS::GuardDuty::IPSet", "GuardDuty IPSet", "Security", false},
	{"AWS", "AWS::GuardDuty::Master", "GuardDuty Master", "Security", true},
	{"AWS", "AWS::GuardDuty::Member", "GuardDuty Member", "Security", false},
	{"AWS", "AWS::GuardDuty::ThreatIntelSet", "GuardDuty ThreatIntelSet", "Security", false},
	{"AWS", "AWS::HealthLake::FHIRDatastore", "Health Lake FHIRDatastore", "Security", false},
	{"AWS", "AWS::IAM::AccessKey", "IAM AccessKey", "Identity", false},
	{"AWS", "AWS::IAM::Group", "IAM Group", "Identity", true},
	{"AWS", "AWS::IAM::InstanceProfile", "IAM InstanceProfile", "Identity", false},
	{"AWS", "AWS::IAM::ManagedPolicy", "IAM ManagedPolicy", "Identity", false},
	{"AWS", "AWS::IAM::OIDCProvider", "IAM OIDCProvider", "Identity", false},
	{"AWS", "AWS::IAM::Policy", "IAM Policy", "Identity", false},
	{"AWS", "AWS::IAM::Role", "IAM Role", "Identity", false},
	{"AWS", "AWS::IAM::SAMLProvider", "IAM SAMLProvider", "Identity", false},
	{"AWS", "AWS::IAM::ServerCertificate", "IAM ServerCertificate", "Identity", false},
	{"AWS", "AWS::IAM::ServiceLinkedRole", "IAM ServiceLinkedRole", "Identity", false},
	{"AWS", "AWS::IAM::User", "IAM User", "Identity", true},
	{"AWS", "AWS::IAM::UserToGroupAddition", "IAM UserToGroupAddition", "Identity", false},
	{"AWS", "AWS::IAM::VirtualMFADevice", "IAM VirtualMFADevice", "Identity", false},
	{"AWS", "AWS::AccessAnalyzer::Analyzer", "AccessAnalyzer Analyzer", "Security", false},
	{"AWS", "AWS::ImageBuilder::Component", "ImageBuilder Component", "Infrastructure", false},
	{"AWS", "AWS::ImageBuilder::ContainerRecipe", "ImageBuilder ContainerRecipe", "Infrastructure", false},
	{"AWS", "AWS::ImageBuilder::DistributionConfiguration", "ImageBuilder DistributionConfiguration", "Infrastructure", false},
	{"AWS", "AWS::ImageBuilder::Image", "ImageBuilder Image", "Infrastructure", true},
	{"AWS", "AWS::ImageBuilder::ImagePipeline", "ImageBuilder ImagePipeline", "Infrastructure", false},
	{"AWS", "AWS::ImageBuilder::ImageRecipe", "ImageBuilder ImageRecipe", "Infrastructure", false},
	{"AWS", "AWS::ImageBuilder::InfrastructureConfiguration", "ImageBuilder InfrastructureConfiguration", "Infrastructure", false},
	{"AWS", "AWS::SSMIncidents::ReplicationSet", "SSMIncidents ReplicationSet", "Governance", false},
	{"AWS", "AWS::SSMIncidents::ResponsePlan", "SSMIncidents ResponsePlan", "Governance", false},
	{"AWS", "AWS::SSMContacts::Contact", "SSMContacts Contact", "Governance", false},
	{"AWS", "AWS::SSMContacts::ContactChannel", "SSMContacts ContactChannel", "Governance", false},
	{"AWS", "AWS::Inspector::AssessmentTarget", "Inspector AssessmentTarget", "Governance", false},
	{"AWS", "AWS::Inspector::AssessmentTemplate", "Inspector AssessmentTemplate", "Governance", false},
	{"AWS", "AWS::Inspector::ResourceGroup", "Inspector ResourceGroup", "Governance", false},
	{"AWS", "AWS::InspectorV2::Filter", "InspectorV2 Filter", "Governance", false},
	{"AWS", "AWS::IoT::AccountAuditConfiguration", "IoT AccountAuditConfiguration", "IoT", false},
	{"AWS", "AWS::IoT::Authorizer", "IoT Authorizer", "IoT", false},
	{"AWS", "AWS::IoT::Certificate", "IoT Certificate", "IoT", false},
	{"AWS", "AWS::IoT::CustomMetric", "IoT CustomMetric", "IoT", false},
	{"AWS", "AWS::IoT::Dimension", "IoT Dimension", "IoT", false},
	{"AWS", "AWS::IoT::DomainConfiguration", "IoT DomainConfiguration", "IoT", false},
	{"AWS", "AWS::IoT::FleetMetric", "IoT FleetMetric", "IoT", false},
	{"AWS", "AWS::IoT::JobTemplate", "IoT JobTemplate", "IoT", false},
	{"AWS", "AWS::IoT::Logging", "IoT Logging", "IoT", false},
	{"AWS", "AWS::IoT::MitigationAction", "IoT MitigationAction", "IoT", false},
	{"AWS", "AWS::IoT::Policy", "IoT Policy", "IoT", false},
	{"AWS", "AWS::IoT::PolicyPrincipalAttachment", "IoT PolicyPrincipalAttachment", "IoT", false},
	{"AWS", "AWS::IoT::ProvisioningTemplate", "IoT ProvisioningTemplate", "IoT", false},
	{"AWS", "AWS::IoT::ResourceSpecificLogging", "IoT ResourceSpecificLogging", "IoT", false},
	{"AWS", "AWS::IoT::ScheduledAudit", "IoT ScheduledAudit", "IoT", false},
	{"AWS", "AWS::IoT::SecurityProfile", "IoT SecurityProfile", "IoT", false},
	{"AWS", "AWS::IoT::Thing", "IoT Thing", "IoT", false},
	{"AWS", "AWS::IoT::ThingPrincipalAttachment", "IoT ThingPrincipalAttachment", "IoT", false},
	{"AWS", "AWS::IoT::TopicRule", "IoT TopicRule", "IoT", false},
	{"AWS", "AWS::IoT::TopicRuleDestination", "IoT TopicRuleDestination", "IoT", false},
	{"AWS", "AWS::IoT1Click::Device", "IoT1Click Device", "IoT", false},
	{"AWS", "AWS::IoT1Click::Placement", "IoT1Click Placement", "IoT", false},
	{"AWS", "AWS::IoT1Click::Project", "IoT1Click Project", "IoT", false},
	{"AWS", "AWS::IoTAnalytics::Channel", "IoTAnalytics Channel", "IoT", false},
	{"AWS", "AWS::IoTAnalytics::Dataset", "IoTAnalytics Dataset", "IoT", false},
	{"AWS", "AWS::IoTAnalytics::Datastore", "IoTAnalytics Datastore", "IoT", false},
	{"AWS", "AWS::IoTAnalytics::Pipeline", "IoTAnalytics Pipeline", "IoT", false},
	{"AWS", "AWS::IoTAzure CoreDeviceAdvisor::SuiteDefinition", "IoTAzure CoreDeviceAdvisor SuiteDefinition", "IoT", false},
	{"AWS", "AWS::IoTEvents::DetectorModel", "IoTEvents DetectorModel", "IoT", false},
	{"AWS", "AWS::IoTEvents::Input", "IoTEvents Input", "IoT", false},
	{"AWS", "AWS::IoTFleetHub::Application", "IoTFleetHub Application", "IoT", false},
	{"AWS", "AWS::Greengrass::ConnectorDefinition", "Greengrass ConnectorDefinition", "IoT", false},
	{"AWS", "AWS::Greengrass::ConnectorDefinitionVersion", "Greengrass ConnectorDefinitionVersion", "IoT", false},
	{"AWS", "AWS::Greengrass::Azure CoreDefinition", "Greengrass Azure CoreDefinition", "IoT", false},
	{"AWS", "AWS::Greengrass::Azure CoreDefinitionVersion", "Greengrass Azure CoreDefinitionVersion", "IoT", false},
	{"AWS", "AWS::Greengrass::DeviceDefinition", "Greengrass DeviceDefinition", "IoT", false},
	{"AWS", "AWS::Greengrass::DeviceDefinitionVersion", "Greengrass DeviceDefinitionVersion", "IoT", false},
	{"AWS", "AWS::Greengrass::FunctionDefinition", "Greengrass FunctionDefinition", "IoT", false},
	{"AWS", "AWS::Greengrass::FunctionDefinitionVersion", "Greengrass FunctionDefinitionVersion", "IoT", false},
	{"AWS", "AWS::Greengrass::Group", "Greengrass Group", "IoT", false},
	{"AWS", "AWS::Greengrass::GroupVersion", "Greengrass GroupVersion", "IoT", false},
	{"AWS", "AWS::Greengrass::LoggerDefinition", "Greengrass LoggerDefinition", "IoT", false},
	{"AWS", "AWS::Greengrass::LoggerDefinitionVersion", "Greengrass LoggerDefinitionVersion", "IoT", false},
	{"AWS", "AWS::Greengrass::ResourceDefinition", "Greengrass ResourceDefinition", "IoT", false},
	{"AWS", "AWS::Greengrass::ResourceDefinitionVersion", "Greengrass ResourceDefinitionVersion", "IoT", false},
	{"AWS", "AWS::Greengrass::SubscriptionDefinition", "Greengrass SubscriptionDefinition", "IoT", false},
	{"AWS", "AWS::Greengrass::SubscriptionDefinitionVersion", "Greengrass SubscriptionDefinitionVersion", "IoT", false},
	{"AWS", "AWS::GreengrassV2::ComponentVersion", "GreengrassV2 ComponentVersion", "IoT", false},
	{"AWS", "AWS::IoTSiteWise::AccessPolicy", "IoTSiteWise AccessPolicy", "IoT", false},
	{"AWS", "AWS::IoTSiteWise::Asset", "IoTSiteWise Asset", "IoT", false},
	{"AWS", "AWS::IoTSiteWise::AssetModel", "IoTSiteWise AssetModel", "IoT", false},
	{"AWS", "AWS::IoTSiteWise::Dashboard", "IoTSiteWise Dashboard", "IoT", false},
	{"AWS", "AWS::IoTSiteWise::Gateway", "IoTSiteWise Gateway", "IoT", false},
	{"AWS", "AWS::IoTSiteWise::Portal", "IoTSiteWise Portal", "IoT", false},
	{"AWS", "AWS::IoTSiteWise::Project", "IoTSiteWise Project", "IoT", false},
	{"AWS", "AWS::IVS::Channel", "Interactive Video Service Channel", "Media", false},
	{"AWS", "AWS::IVS::PlaybackKeyPair", "Interactive Video Service PlaybackKeyPair", "Media", false},
	{"AWS", "AWS::IVS::RecordingConfiguration", "Interactive Video Service RecordingConfiguration", "Media", false},
	{"AWS", "AWS::IVS::StreamKey", "Interactive Video Service StreamKey", "Media", false},
	{"AWS", "AWS::SQS::Queue", "SQS Queue", "Messaging", true},
	{"AWS", "AWS::SQS::QueuePolicy", "SQS QueuePolicy", "Messaging", false},
	{"AWS", "AWS::SNS::Subscription", "SNS Subscription", "Messaging", false},
	{"AWS", "AWS::SNS::Topic", "SNS Topic", "Messaging", false},
	{"AWS", "AWS::SNS::TopicPolicy", "SNS TopicPolicy", "Messaging", false},
	{"AWS", "AWS::SDB::Domain", "SimpleDB Domain", "Messaging", true},
	{"AWS", "AWS::Signer::ProfilePermission", "Signer ProfilePermission", "Messaging", false},
	{"AWS", "AWS::Signer::SigningProfile", "Signer SigningProfile", "Messaging", false},
	{"AWS", "AWS::SES::ConfigurationSet", "SES ConfigurationSet", "Messaging", true},
	{"AWS", "AWS::SES::ConfigurationSetEventDestination", "SES ConfigurationSetEventDestination", "Messaging", false},
	{"AWS", "AWS::SES::ContactList", "SES ContactList", "Messaging", false},
	{"AWS", "AWS::SES::ReceiptFilter", "SES ReceiptFilter", "Messaging", false},
	{"AWS", "AWS::SES::ReceiptRule", "SES ReceiptRule", "Messaging", false},
	{"AWS", "AWS::SES::ReceiptRuleSet", "SES ReceiptRuleSet", "Messaging", false},
	{"AWS", "AWS::SES::Template", "SES Template", "Messaging", false},
	{"AWS", "AWS::SecurityHub::Hub", "Security Hub Hub", "Security", true},
	{"AWS", "AWS::ServiceCatalogAppRegistry::Application", "Service Catalog AppRegistry Application", "Governance", false},
	{"AWS", "AWS::ServiceCatalogAppRegistry::AttributeGroup", "Service Catalog AppRegistry AttributeGroup", "Governance", false},
	{"AWS", "AWS::ServiceCatalogAppRegistry::AttributeGroupAssociation", "Service Catalog AppRegistry AttributeGroupAssociation", "Governance", false},
	{"AWS", "AWS::ServiceCatalogAppRegistry::ResourceAssociation", "Service Catalog AppRegistry ResourceAssociation", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::AcceptedPortfolioShare", "Service Catalog AcceptedPortfolioShare", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::CloudFormationProduct", "Service Catalog CloudFormationProduct", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::CloudFormationProvisionedProduct", "Service Catalog CloudFormationProvisionedProduct", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::LaunchNotificationConstraint", "Service Catalog LaunchNotificationConstraint", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::LaunchRoleConstraint", "Service Catalog LaunchRoleConstraint", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::LaunchTemplateConstraint", "Service Catalog LaunchTemplateConstraint", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::Portfolio", "Service Catalog Portfolio", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::PortfolioPrincipalAssociation", "Service Catalog PortfolioPrincipalAssociation", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::PortfolioProductAssociation", "Service Catalog PortfolioProductAssociation", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::PortfolioShare", "Service Catalog PortfolioShare", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::ResourceUpdateConstraint", "Service Catalog ResourceUpdateConstraint", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::ServiceAction", "Service Catalog ServiceAction", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::ServiceActionAssociation", "Service Catalog ServiceActionAssociation", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::StackSetConstraint", "Service Catalog StackSetConstraint", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::TagOption", "Service Catalog TagOption", "Governance", false},
	{"AWS", "AWS::ServiceCatalog::TagOptionAssociation", "Service Catalog TagOptionAssociation", "Governance", false},
	{"AWS", "AWS::SecretsManager::ResourcePolicy", "Secrets Manager ResourcePolicy", "Security", false},
	{"AWS", "AWS::SecretsManager::RotationSchedule", "Secrets Manager RotationSchedule", "Security", false},
	{"AWS", "AWS::SecretsManager::Secret", "Secrets Manager Secret", "Security", false},
	{"AWS", "AWS::SecretsManager::SecretTargetAttachment", "Secrets Manager SecretTargetAttachment", "Security", false},
	{"AWS", "AWS::SageMaker::App", "SageMaker App", "AI + ML", true},
	{"AWS", "AWS::SageMaker::AppImageConfig", "SageMaker AppImageConfig", "AI + ML", false},
	{"AWS", "AWS::SageMaker::CodeRepository", "SageMaker CodeRepository", "AI + ML", false},
	{"AWS", "AWS::SageMaker::DataQualityJobDefinition", "SageMaker DataQualityJobDefinition", "AI + ML", false},
	{"AWS", "AWS::SageMaker::Device", "SageMaker Device", "AI + ML", false},
	{"AWS", "AWS::SageMaker::DeviceFleet", "SageMaker DeviceFleet", "AI + ML", false},
	{"AWS", "AWS::SageMaker::Domain", "SageMaker Domain", "AI + ML", false},
	{"AWS", "AWS::SageMaker::Endpoint", "SageMaker Endpoint", "AI + ML", false},
	{"AWS", "AWS::SageMaker::EndpointConfig", "SageMaker EndpointConfig", "AI + ML", false},
	{"AWS", "AWS::SageMaker::FeatureGroup", "SageMaker FeatureGroup", "AI + ML", false},
	{"AWS", "AWS::SageMaker::Image", "SageMaker Image", "AI + ML", false},
	{"AWS", "AWS::SageMaker::ImageVersion", "SageMaker ImageVersion", "AI + ML", false},
	{"AWS", "AWS::SageMaker::Model", "SageMaker Model", "AI + ML", false},
	{"AWS", "AWS::SageMaker::ModelBiasJobDefinition", "SageMaker ModelBiasJobDefinition", "AI + ML", false},
	{"AWS", "AWS::SageMaker::ModelExplainabilityJobDefinition", "SageMaker ModelExplainabilityJobDefinition", "AI + ML", false},
	{"AWS", "AWS::SageMaker::ModelPackageGroup", "SageMaker ModelPackageGroup", "AI + ML", false},
	{"AWS", "AWS::SageMaker::ModelQualityJobDefinition", "SageMaker ModelQualityJobDefinition", "AI + ML", false},
	{"AWS", "AWS::SageMaker::MonitoringSchedule", "SageMaker MonitoringSchedule", "AI + ML", false},
	{"AWS", "AWS::SageMaker::NotebookInstance", "SageMaker NotebookInstance", "AI + ML", false},
	{"AWS", "AWS::SageMaker::NotebookInstanceLifecycleConfig", "SageMaker NotebookInstanceLifecycleConfig", "AI + ML", false},
	{"AWS", "AWS::SageMaker::Pipeline", "SageMaker Pipeline", "AI + ML", false},
	{"AWS", "AWS::SageMaker::Project", "SageMaker Project", "AI + ML", false},
	{"AWS", "AWS::SageMaker::UserProfile", "SageMaker UserProfile", "AI + ML", false},
	{"AWS", "AWS::SageMaker::Workteam", "SageMaker Workteam", "AI + ML", false},
	{"AWS", "AWS::S3Outposts::AccessPoint", "S3Outposts AccessPoint", "Storage", false},
	{"AWS", "AWS::S3Outposts::Bucket", "S3Outposts Bucket", "Storage", false},
	{"AWS", "AWS::S3Outposts::BucketPolicy", "S3Outposts BucketPolicy", "Storage", false},
	{"AWS", "AWS::S3Outposts::Endpoint", "S3Outposts Endpoint", "Storage", false},
	{"AWS", "AWS::S3ObjectLambda::AccessPoint", "S3ObjectLambda AccessPoint", "Storage", false},
	{"AWS", "AWS::S3ObjectLambda::AccessPointPolicy", "S3ObjectLambda AccessPointPolicy", "Storage", false},
	{"AWS", "AWS::S3::AccessPoint", "S3 AccessPoint", "Storage", false},
	{"AWS", "AWS::S3::Bucket", "S3 Bucket", "Storage", true},
	{"AWS", "AWS::S3::BucketPolicy", "S3 BucketPolicy", "Storage", false},
	{"AWS", "AWS::S3::MultiRegionAccessPoint", "S3 MultiRegionAccessPoint", "Storage", true},
	{"AWS", "AWS::S3::MultiRegionAccessPointPolicy", "S3 MultiRegionAccessPointPolicy", "Storage", false},
	{"AWS", "AWS::S3::StorageLens", "S3 StorageLens", "Storage", true},
	{"AWS", "AWS::RUM::AppMonitor", "CloudWatch RUM AppMonitor", "Other", true},
	{"AWS", "AWS::Route53Resolver::FirewallDomainList", "Route53 Resolver FirewallDomainList", "Networking", false},
	{"AWS", "AWS::Route53Resolver::FirewallRuleGroup", "Route53 Resolver FirewallRuleGroup", "Networking", false},
	{"AWS", "AWS::Route53Resolver::FirewallRuleGroupAssociation", "Route53 Resolver FirewallRuleGroupAssociation", "Networking", false},
	{"AWS", "AWS::Route53Resolver::ResolverConfig", "Route53 Resolver ResolverConfig", "Networking", false},
	{"AWS", "AWS::Route53Resolver::ResolverDNSSECConfig", "Route53 Resolver ResolverDNSSECConfig", "Networking", false},
	{"AWS", "AWS::Route53Resolver::ResolverEndpoint", "Route53 Resolver ResolverEndpoint", "Networking", false},
	{"AWS", "AWS::Route53Resolver::ResolverQueryLoggingConfig", "Route53 Resolver ResolverQueryLoggingConfig", "Networking", false},
	{"AWS", "AWS::Route53Resolver::ResolverQueryLoggingConfigAssociation", "Route53 Resolver ResolverQueryLoggingConfigAssociation", "Networking", false},
	{"AWS", "AWS::Route53Resolver::ResolverRule", "Route53 Resolver ResolverRule", "Networking", false},
	{"AWS", "AWS::Route53Resolver::ResolverRuleAssociation", "Route53 Resolver ResolverRuleAssociation", "Networking", false},
	{"AWS", "AWS::Route53RecoveryReadiness::Cell", "Route53 Recovery Readiness Cell", "Networking", false},
	{"AWS", "AWS::Route53RecoveryReadiness::ReadinessCheck", "Route53 Recovery Readiness ReadinessCheck", "Networking", false},
	{"AWS", "AWS::Route53RecoveryReadiness::RecoveryGroup", "Route53 Recovery Readiness RecoveryGroup", "Networking", false},
	{"AWS", "AWS::Route53RecoveryReadiness::ResourceSet", "Route53 Recovery Readiness ResourceSet", "Networking", false},
	{"AWS", "AWS::Route53RecoveryControl::Cluster", "Route53 Recovery Control Cluster", "Networking", false},
	{"AWS", "AWS::Route53RecoveryControl::ControlPanel", "Route53 Recovery Control ControlPanel", "Networking", false},
	{"AWS", "AWS::Route53RecoveryControl::RoutingControl", "Route53 Recovery Control RoutingControl", "Networking", false},
	{"AWS", "AWS::Route53RecoveryControl::SafetyRule", "Route53 Recovery Control SafetyRule", "Networking", false},
	{"AWS", "AWS::Route53::DNSSEC", "Route53 DNSSEC", "Networking", false},
	{"AWS", "AWS::Route53::HealthCheck", "Route53 HealthCheck", "Networking", false},
	{"AWS", "AWS::Route53::HostedZone", "Route53 HostedZone", "Networking", true},
	{"AWS", "AWS::Route53::KeySigningKey", "Route53 KeySigningKey", "Networking", false},
	{"AWS", "AWS::Route53::RecordSet", "Route53 RecordSet", "Networking", false},
	{"AWS", "AWS::Route53::RecordSetGroup", "Route53 RecordSetGroup", "Networking", false},
	{"AWS", "AWS::RoboMaker::Fleet", "RoboMaker Fleet", "Other", false},
	{"AWS", "AWS::RoboMaker::Robot", "RoboMaker Robot", "Other", false},
	{"AWS", "AWS::RoboMaker::RobotApplication", "RoboMaker RobotApplication", "Other", false},
	{"AWS", "AWS::RoboMaker::RobotApplicationVersion", "RoboMaker RobotApplicationVersion", "Other", false},
	{"AWS", "AWS::RoboMaker::SimulationApplication", "RoboMaker SimulationApplication", "Other", false},
	{"AWS", "AWS::RoboMaker::SimulationApplicationVersion", "RoboMaker SimulationApplicationVersion", "Other", false},
	{"AWS", "AWS::ResourceGroups::Group", "Resource Groups Group", "Governance", false},
	{"AWS", "AWS::ResilienceHub::App", "Resilience Hub App", "Other", false},
	{"AWS", "AWS::ResilienceHub::ResiliencyPolicy", "Resilience Hub ResiliencyPolicy", "Other", false},
	{"AWS", "AWS::Rekognition::Project", "Rekognition Project", "Other", false},
	{"AWS", "AWS::RefactorSpaces::Application", "Refactor Spaces Application", "Other", false},
	{"AWS", "AWS::RefactorSpaces::Environment", "Refactor Spaces Environment", "Other", false},
	{"AWS", "AWS::RefactorSpaces::Route", "Refactor Spaces Route", "Other", false},
	{"AWS", "AWS::RefactorSpaces::Service", "Refactor Spaces Service", "Other", false},
	{"AWS", "AWS::Redshift::Cluster", "Redshift Cluster", "Database", true},
	{"AWS", "AWS::Redshift::ClusterParameterGroup", "Redshift ClusterParameterGroup", "Database", false},
	{"AWS", "AWS::Redshift::ClusterSecurityGroup", "Redshift ClusterSecurityGroup", "Database", false},
	{"AWS", "AWS::Redshift::ClusterSecurityGroupIngress", "Redshift ClusterSecurityGroupIngress", "Database", false},
	{"AWS", "AWS::Redshift::ClusterSubnetGroup", "Redshift ClusterSubnetGroup", "Database", false},
	{"AWS", "AWS::Redshift::EndpointAccess", "Redshift EndpointAccess", "Database", false},
	{"AWS", "AWS::Redshift::EndpointAuthorization", "Redshift EndpointAuthorization", "Database", false},
	{"AWS", "AWS::Redshift::EventSubscription", "Redshift EventSubscription", "Database", false},
	{"AWS", "AWS::Redshift::ScheduledAction", "Redshift ScheduledAction", "Database", false},
	{"AWS", "AWS::RDS::DBCluster", "RDS DBCluster", "Database", true},
	{"AWS", "AWS::RDS::DBClusterParameterGroup", "RDS DBClusterParameterGroup", "Database", false},
	{"AWS", "AWS::RDS::DBInstance", "RDS DBInstance", "Database", true},
	{"AWS", "AWS::RDS::DBParameterGroup", "RDS DBParameterGroup", "Database", true},
	{"AWS", "AWS::RDS::DBProxy", "RDS DBProxy", "Database", false},
	{"AWS", "AWS::RDS::DBProxyEndpoint", "RDS DBProxyEndpoint", "Database", false},
	{"AWS", "AWS::RDS::DBProxyTargetGroup", "RDS DBProxyTargetGroup", "Database", false},
	{"AWS", "AWS::RDS::DBSecurityGroup", "RDS DBSecurityGroup", "Database", false},
	{"AWS", "AWS::RDS::DBSecurityGroupIngress", "RDS DBSecurityGroupIngress", "Database", false},
	{"AWS", "AWS::RDS::DBSubnetGroup", "RDS DBSubnetGroup", "Database", true},
	{"AWS", "AWS::RDS::EventSubscription", "RDS EventSubscription", "Database", false},
	{"AWS", "AWS::RDS::GlobalCluster", "RDS GlobalCluster", "Database", false},
	{"AWS", "AWS::RDS::OptionGroup", "RDS OptionGroup", "Database", false},
	{"AWS", "AWS::RAM::ResourceShare", "Resource Access Manager (RAM) ResourceShare", "Management", false},
	{"AWS", "AWS::QuickSight::Analysis", "QuickSight Analysis", "Analytics", false},
	{"AWS", "AWS::QuickSight::Dashboard", "QuickSight Dashboard", "Analytics", false},
	{"AWS", "AWS::QuickSight::DataSet", "QuickSight DataSet", "Analytics", false},
	{"AWS", "AWS::QuickSight::DataSource", "QuickSight DataSource", "Analytics", false},
	{"AWS", "AWS::QuickSight::Template", "QuickSight Template", "Analytics", false},
	{"AWS", "AWS::QuickSight::Theme", "QuickSight Theme", "Analytics", false},
	{"AWS", "AWS::QLDB::Ledger", "QLDB Ledger", "Analytics", true},
	{"AWS", "AWS::QLDB::Stream", "QLDB Stream", "Analytics", true},
	{"AWS", "AWS::PinpointEmail::ConfigurationSet", "Pinpoint Email ConfigurationSet", "Other", false},
	{"AWS", "AWS::PinpointEmail::ConfigurationSetEventDestination", "Pinpoint Email ConfigurationSetEventDestination", "Other", false},
	{"AWS", "AWS::PinpointEmail::DedicatedIpPool", "Pinpoint Email DedicatedIpPool", "Other", false},
	{"AWS", "AWS::PinpointEmail::Identity", "Pinpoint Email Identity", "Other", false},
	{"AWS", "AWS::Pinpoint::ADMChannel", "Pinpoint ADMChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::APNSChannel", "Pinpoint APNSChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::APNSSandboxChannel", "Pinpoint APNSSandboxChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::APNSVoipChannel", "Pinpoint APNSVoipChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::APNSVoipSandboxChannel", "Pinpoint APNSVoipSandboxChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::App", "Pinpoint App", "Other", false},
	{"AWS", "AWS::Pinpoint::ApplicationSettings", "Pinpoint ApplicationSettings", "Other", false},
	{"AWS", "AWS::Pinpoint::BaiduChannel", "Pinpoint BaiduChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::Campaign", "Pinpoint Campaign", "Other", false},
	{"AWS", "AWS::Pinpoint::EmailChannel", "Pinpoint EmailChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::EmailTemplate", "Pinpoint EmailTemplate", "Other", false},
	{"AWS", "AWS::Pinpoint::EventStream", "Pinpoint EventStream", "Other", false},
	{"AWS", "AWS::Pinpoint::GCMChannel", "Pinpoint GCMChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::InAppTemplate", "Pinpoint InAppTemplate", "Other", false},
	{"AWS", "AWS::Pinpoint::PushTemplate", "Pinpoint PushTemplate", "Other", false},
	{"AWS", "AWS::Pinpoint::Segment", "Pinpoint Segment", "Other", false},
	{"AWS", "AWS::Pinpoint::SMSChannel", "Pinpoint SMSChannel", "Other", false},
	{"AWS", "AWS::Pinpoint::SmsTemplate", "Pinpoint SmsTemplate", "Other", false},
	{"AWS", "AWS::Pinpoint::VoiceChannel", "Pinpoint VoiceChannel", "Other", false},
	{"AWS", "AWS::Panorama::ApplicationInstance", "Panorama ApplicationInstance", "Other", false},
	{"AWS", "AWS::Panorama::Package", "Panorama Package", "Other", false},
	{"AWS", "AWS::Panorama::PackageVersion", "Panorama PackageVersion", "Other", false},
	{"AWS", "AWS::OpsWorksCM::Server", "OpsWork Configuration Manager Server", "Ops", true},
	{"AWS", "AWS::OpsWorks::App", "OpsWorks App", "Ops", false},
	{"AWS", "AWS::OpsWorks::ElasticLoadBalancerAttachment", "OpsWorks ElasticLoadBalancerAttachment", "Ops", false},
	{"AWS", "AWS::OpsWorks::Instance", "OpsWorks Instance", "Ops", false},
	{"AWS", "AWS::OpsWorks::Layer", "OpsWorks Layer", "Ops", false},
	{"AWS", "AWS::OpsWorks::Stack", "OpsWorks Stack", "Ops", false},
	{"AWS", "AWS::OpsWorks::UserProfile", "OpsWorks UserProfile", "Ops", false},
	{"AWS", "AWS::OpsWorks::Volume", "OpsWorks Volume", "Ops", false},
	{"AWS", "AWS::OpenSearchService::Domain", "OpenSearchService Domain", "Ops", false},
	{"AWS", "AWS::Elasticsearch::Domain", "Elasticsearch Domain", "Database", true},
	{"AWS", "AWS::NimbleStudio::LaunchProfile", "NimbleStudio LaunchProfile", "Management", false},
	{"AWS", "AWS::NimbleStudio::StreamingImage", "NimbleStudio StreamingImage", "Management", false},
	{"AWS", "AWS::NimbleStudio::Studio", "NimbleStudio Studio", "Management", false},
	{"AWS", "AWS::NimbleStudio::StudioComponent", "NimbleStudio StudioComponent", "Management", false},
	{"AWS", "AWS::NetworkManager::CustomerGatewayAssociation", "NetworkManager CustomerGatewayAssociation", "Networking", false},
	{"AWS", "AWS::NetworkManager::Device", "NetworkManager Device", "Networking", false},
	{"AWS", "AWS::NetworkManager::GlobalNetwork", "NetworkManager GlobalNetwork", "Networking", false},
	{"AWS", "AWS::NetworkManager::Link", "NetworkManager Link", "Networking", false},
	{"AWS", "AWS::NetworkManager::LinkAssociation", "NetworkManager LinkAssociation", "Networking", false},
	{"AWS", "AWS::NetworkManager::Site", "NetworkManager Site", "Networking", false},
	{"AWS", "AWS::NetworkManager::TransitGatewayRegistration", "NetworkManager TransitGatewayRegistration", "Networking", false},
	{"AWS", "AWS::NetworkFirewall::Firewall", "NetworkFirewall Firewall", "Security", true},
	{"AWS", "AWS::NetworkFirewall::FirewallPolicy", "NetworkFirewall FirewallPolicy", "Security", false},
	{"AWS", "AWS::NetworkFirewall::LoggingConfiguration", "NetworkFirewall LoggingConfiguration", "Security", false},
	{"AWS", "AWS::NetworkFirewall::RuleGroup", "NetworkFirewall RuleGroup", "Security", false},
	{"AWS", "AWS::Neptune::DBCluster", "Neptune DBCluster", "Database", false},
	{"AWS", "AWS::Neptune::DBClusterParameterGroup", "Neptune DBClusterParameterGroup", "Database", false},
	{"AWS", "AWS::Neptune::DBInstance", "Neptune DBInstance", "Database", true},
	{"AWS", "AWS::Neptune::DBParameterGroup", "Neptune DBParameterGroup", "Database", false},
	{"AWS", "AWS::Neptune::DBSubnetGroup", "Neptune DBSubnetGroup", "Database", false},
	{"AWS", "AWS::MWAA::Environment", "Managed Airflow Environment", "Database", false},
	{"AWS", "AWS::MemoryDB::ACL", "MemoryDB ACL", "Database", false},
	{"AWS", "AWS::MemoryDB::Cluster", "MemoryDB Cluster", "Database", true},
	{"AWS", "AWS::MemoryDB::ParameterGroup", "MemoryDB ParameterGroup", "Database", false},
	{"AWS", "AWS::MemoryDB::SubnetGroup", "MemoryDB SubnetGroup", "Database", false},
	{"AWS", "AWS::MemoryDB::User", "MemoryDB User", "Database", false},
	{"AWS", "AWS::AmazonMQ::Broker", "AmazonMQ Broker", "Messaging", true},
	{"AWS", "AWS::AmazonMQ::Configuration", "AmazonMQ Configuration", "Messaging", false},
	{"AWS", "AWS::AmazonMQ::ConfigurationAssociation", "AmazonMQ ConfigurationAssociation", "Messaging", false},
	{"AWS", "AWS::MediaStore::Container", "MediaStore Container", "Media", false},
	{"AWS", "AWS::MediaPackage::Asset", "Media Package Asset", "Media", false},
	{"AWS", "AWS::MediaPackage::Channel", "Media Package Channel", "Media", false},
	{"AWS", "AWS::MediaPackage::OriginEndpoint", "Media Package OriginEndpoint", "Media", false},
	{"AWS", "AWS::MediaPackage::PackagingConfiguration", "Media Package PackagingConfiguration", "Media", false},
	{"AWS", "AWS::MediaPackage::PackagingGroup", "Media Package PackagingGroup", "Media", false},
	{"AWS", "AWS::MediaLive::Channel", "Media Live Channel", "Media", false},
	{"AWS", "AWS::MediaLive::Input", "Media Live Input", "Media", false},
	{"AWS", "AWS::MediaLive::InputSecurityGroup", "Media Live InputSecurityGroup", "Media", false},
	{"AWS", "AWS::MediaConvert::JobTemplate", "Media Convert JobTemplate", "Media", false},
	{"AWS", "AWS::MediaConvert::Preset", "Media Convert Preset", "Media", false},
	{"AWS", "AWS::MediaConvert::Queue", "Media Convert Queue", "Media", false},
	{"AWS", "AWS::MediaConnect::Flow", "Media Connect Flow", "Media", false},
	{"AWS", "AWS::MediaConnect::FlowEntitlement", "Media Connect FlowEntitlement", "Media", false},
	{"AWS", "AWS::MediaConnect::FlowOutput", "Media Connect FlowOutput", "Media", false},
	{"AWS", "AWS::MediaConnect::FlowSource", "Media Connect FlowSource", "Media", false},
	{"AWS", "AWS::MediaConnect::FlowVpcInterface", "Media Connect FlowVpcInterface", "Media", false},
	{"AWS", "AWS::ManagedBlockchain::Member", "Managed Blockchain Member", "Other", false},
	{"AWS", "AWS::ManagedBlockchain::Node", "Managed Blockchain Node", "Other", false},
	{"AWS", "AWS::Macie::CustomDataIdentifier", "Macie CustomDataIdentifier", "Security", false},
	{"AWS", "AWS::Macie::FindingsFilter", "Macie FindingsFilter", "Security", false},
	{"AWS", "AWS::Macie::Session", "Macie Session", "Security", false},
	{"AWS", "AWS::LookoutVision::Project", "LookoutVision Project", "Other", false},
	{"AWS", "AWS::LookoutMetrics::Alert", "Lookout Metrics Alert", "Other", false},
	{"AWS", "AWS::LookoutMetrics::AnomalyDetector", "Lookout Metrics AnomalyDetector", "Other", false},
	{"AWS", "AWS::LookoutEquipment::InferenceScheduler", "Lookout Equipment InferenceScheduler", "Other", false},
	{"AWS", "AWS::Location::GeofenceCollection", "Location GeofenceCollection", "Other", false},
	{"AWS", "AWS::Location::Map", "Location Map", "Other", false},
	{"AWS", "AWS::Location::PlaceIndex", "Location PlaceIndex", "Other", false},
	{"AWS", "AWS::Location::RouteCalculator", "Location RouteCalculator", "Other", false},
	{"AWS", "AWS::Location::Tracker", "Location Tracker", "Other", false},
	{"AWS", "AWS::Location::TrackerConsumer", "Location TrackerConsumer", "Other", false},
	{"AWS", "AWS::Lightsail::Alarm", "Lightsail Alarm", "Cloud App", false},
	{"AWS", "AWS::Lightsail::Bucket", "Lightsail Bucket", "Cloud App", false},
	{"AWS", "AWS::Lightsail::Certificate", "Lightsail Certificate", "Cloud App", false},
	{"AWS", "AWS::Lightsail::Container", "Lightsail Container", "Cloud App", false},
	{"AWS", "AWS::Lightsail::Database", "Lightsail Database", "Cloud App", false},
	{"AWS", "AWS::Lightsail::Disk", "Lightsail Disk", "Cloud App", false},
	{"AWS", "AWS::Lightsail::Distribution", "Lightsail Distribution", "Cloud App", false},
	{"AWS", "AWS::Lightsail::Instance", "Lightsail Instance", "Cloud App", true},
	{"AWS", "AWS::Lightsail::LoadBalancer", "Lightsail LoadBalancer", "Cloud App", true},
	{"AWS", "AWS::Lightsail::LoadBalancerTlsCertificate", "Lightsail LoadBalancerTlsCertificate", "Cloud App", false},
	{"AWS", "AWS::Lightsail::StaticIp", "Lightsail StaticIp", "Cloud App", false},
	{"AWS", "AWS::LicenseManager::Grant", "License Manager Grant", "Management", false},
	{"AWS", "AWS::LicenseManager::License", "License Manager License", "Management", false},
	{"AWS", "AWS::Lex::Bot", "Lex Bot", "AI + ML", true},
	{"AWS", "AWS::Lex::BotAlias", "Lex BotAlias", "AI + ML", false},
	{"AWS", "AWS::Lex::BotVersion", "Lex BotVersion", "AI + ML", false},
	{"AWS", "AWS::Lex::ResourcePolicy", "Lex ResourcePolicy", "AI + ML", false},
	{"AWS", "AWS::Lambda::Alias", "Lambda Alias", "Serverless", false},
	{"AWS", "AWS::Lambda::CodeSigningConfig", "Lambda CodeSigningConfig", "Serverless", false},
	{"AWS", "AWS::Lambda::EventInvokeConfig", "Lambda EventInvokeConfig", "Serverless", false},
	{"AWS", "AWS::Lambda::EventSourceMapping", "Lambda EventSourceMapping", "Serverless", false},
	{"AWS", "AWS::Lambda::Function", "Lambda Function", "Serverless", true},
	{"AWS", "AWS::Lambda::LayerVersion", "Lambda LayerVersion", "Serverless", false},
	{"AWS", "AWS::Lambda::LayerVersionPermission", "Lambda LayerVersionPermission", "Serverless", false},
	{"AWS", "AWS::Lambda::Permission", "Lambda Permission", "Serverless", false},
	{"AWS", "AWS::Lambda::Version", "Lambda Version", "Serverless", false},
	{"AWS", "AWS::LakeFormation::DataLakeSettings", "LakeFormation DataLakeSettings", "Management", false},
	{"AWS", "AWS::LakeFormation::Permissions", "LakeFormation Permissions", "Management", false},
	{"AWS", "AWS::LakeFormation::Resource", "LakeFormation Resource", "Management", false},
	{"AWS", "AWS::KMS::Alias", "KMS Alias", "Security", false},
	{"AWS", "AWS::KMS::Key", "KMS Key", "Security", true},
	{"AWS", "AWS::KMS::ReplicaKey", "KMS ReplicaKey", "Security", false},
	{"AWS", "AWS::KinesisFirehose::DeliveryStream", "Kinesis Firehose DeliveryStream", "Database", false},
	{"AWS", "AWS::KinesisAnalyticsV2::Application", "Kinesis Analytics (V2) Application", "Database", true},
	{"AWS", "AWS::KinesisAnalyticsV2::ApplicationCloudWatchLoggingOption", "Kinesis Analytics (V2) ApplicationCloudWatchLoggingOption", "Database", false},
	{"AWS", "AWS::KinesisAnalyticsV2::ApplicationOutput", "Kinesis Analytics (V2) ApplicationOutput", "Database", false},
	{"AWS", "AWS::KinesisAnalyticsV2::ApplicationReferenceDataSource", "Kinesis Analytics (V2) ApplicationReferenceDataSource", "Database", false},
	{"AWS", "AWS::Cassandra::Keyspace", "Keyspaces (Cassandra) Keyspace", "Database", true},
	{"AWS", "AWS::Cassandra::Table", "Keyspaces (Cassandra) Table", "Database", true},
	{"AWS", "AWS::Kendra::DataSource", "Kendra DataSource", "Database", false},
	{"AWS", "AWS::Kendra::Faq", "Kendra Faq", "Database", false},
	{"AWS", "AWS::Kendra::Index", "Kendra Index", "Database", false},
	{"AWS", "aws::cloudwatch::", "CloudWatch RUM AppMonitor", "Monitoring", true},
	{"AWS", "aws::drs::", "Elastic Disaster Recovery", "Resiliency", true},
	{"AWS", "aws::kafkaconnect::", "Managed Streaming for Kafka", "Messaging", true},
	{"AWS", "aws::airflow::", "Managed Workflow for Airflow", "Workflow", true},
	{"AWS", "aws::organization::", "Organization", "Management", true},
	{"AWS", "aws::swf::", "Simple Workflow", "Management", true},
	{"AWS", "aws::sqlworkbench::", "SQL Workbench", "Data Services", false},
	{"AWS", "aws::shield::", "Shield", "Security", true},
}

func findRecord(resourceType string) *ResourceType {
	resourceType = strings.ToLower(resourceType)
	for _, v := range mapping {
		if strings.HasPrefix(resourceType, strings.ToLower(v.ResourceTypePrefix)) {
			return &v
		}
	}
	return nil
}

func CategoryByResourceType(resourceType string) string {
	record := findRecord(resourceType)
	if record != nil {
		return record.Category
	}
	return ""
}

func CloudProviderByResourceType(resourceType string) string {
	record := findRecord(resourceType)
	if record != nil {
		return string(record.Provider)
	}
	return ""
}

func ServiceNameByResourceType(resourceType string) string {
	record := findRecord(resourceType)
	if record != nil {
		return record.Service
	}
	return ""
}

func IsCommonByResourceType(resourceType string) bool {
	record := findRecord(resourceType)
	if record != nil {
		return record.Common
	}
	return false
}
