package configs

var TablesToResourceTypes = map[string]string{
	"cloudflare_access_application":    "CloudFlare/Access/Application",
	"cloudflare_access_group":          "CloudFlare/Access/Group",
	"cloudflare_access_policy":         "CloudFlare/Access/Policy",
	"cloudflare_account":               "CloudFlare/Account",
	"cloudflare_account_member":        "CloudFlare/Account/Member",
	"cloudflare_account_role":          "CloudFlare/Account/Role",
	"cloudflare_api_token":             "CloudFlare/ApiToken",
	"cloudflare_dns_record":            "CloudFlare/DNSRecord",
	"cloudflare_firewall_rule":         "CloudFlare/Firewall/Rule",
	"cloudflare_load_balancer":         "CloudFlare/LoadBalancer",
	"cloudflare_load_balancer_monitor": "CloudFlare/LoadBalancer/Monitor",
	"cloudflare_load_balancer_pool":    "CloudFlare/LoadBalancer/Pool",
	"cloudflare_page_rule":             "CloudFlare/PageRule",
	"cloudflare_user":                  "CloudFlare/User",
	"cloudflare_user_audit_log":        "CloudFlare/User/AuditLog",
	"cloudflare_worker_route":          "CloudFlare/WorkerRoute",
	"cloudflare_zone":                  "CloudFlare/Zone",
}

var ResourceTypesList = []string{
	"CloudFlare/Access/Application",
	"CloudFlare/Access/Group",
	"CloudFlare/Access/Policy",
	"CloudFlare/Account",
	"CloudFlare/Account/Member",
	"CloudFlare/Account/Role",
	"CloudFlare/ApiToken",
	"CloudFlare/DNSRecord",
	"CloudFlare/Firewall/Rule",
	"CloudFlare/LoadBalancer",
	"CloudFlare/LoadBalancer/Monitor",
	"CloudFlare/LoadBalancer/Pool",
	"CloudFlare/PageRule",
	"CloudFlare/User",
	"CloudFlare/User/AuditLog",
	"CloudFlare/WorkerRoute",
	"CloudFlare/Zone",
}
