#!/bin/bash

set -x
set -e

SERVICES=$(cat ./services)
if [[ $SERVICES == *"auth-service"* ]]; then
    docker build -f  docker/AuthServiceDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/auth-service:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/auth-service:"$TAG"
fi
if [[ $SERVICES == *"checkup-worker"* ]]; then
    docker build -f  docker/CheckupWorkerDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/checkup-worker:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/checkup-worker:"$TAG"
fi
if [[ $SERVICES == *"compliance-report-worker"* ]]; then
    docker build --no-cache -f  docker/ComplianceReportWorkerDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/compliance-report-worker:"$TAG" --build-arg PLUGIN_REGISTRY="435670955331.dkr.ecr.us-east-2.amazonaws.com"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/compliance-report-worker:"$TAG"
fi
if [[ $SERVICES == *"compliance-service"* ]]; then
    docker build -f  docker/ComplianceServiceDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/compliance-service:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/compliance-service:"$TAG"
fi
if [[ $SERVICES == *"describe-scheduler"* ]]; then
    docker build -f  docker/DescribeSchedulerDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/describe-scheduler:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/describe-scheduler:"$TAG"
fi
if [[ $SERVICES == *"hopper"* ]]; then
    docker build -f  docker/HopperDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/hopper:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/hopper:"$TAG"
fi
if [[ $SERVICES == *"reporter"* ]]; then
    docker build -f  docker/ReporterDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/reporter:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/reporter:"$TAG"
fi
if [[ $SERVICES == *"insight-worker"* ]]; then
    docker build -f  docker/InsightWorkerDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/insight-worker:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/insight-worker:"$TAG"
fi
if [[ $SERVICES == *"inventory-service"* ]]; then
    docker build -f  docker/InventoryServiceDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/inventory-service:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/inventory-service:"$TAG"
fi
if [[ $SERVICES == *"metadata-service"* ]]; then
    docker build -f  docker/MetadataServiceDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/metadata-service:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/metadata-service:"$TAG"
fi
if [[ $SERVICES == *"migrator-worker"* ]]; then
    docker build -f  docker/MigratorDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/migrator:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/migrator:"$TAG"
fi
if [[ $SERVICES == *"onboard-service"* ]]; then
    docker build -f  docker/OnboardServiceDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/onboard-service:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/onboard-service:"$TAG"
fi
if [[ $SERVICES == *"summarizer-worker"* ]]; then
    docker build -f  docker/SummarizerWorkerDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/summarizer-worker:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/summarizer-worker:"$TAG"
fi
if [[ $SERVICES == *"swagger-ui"* ]]; then
    docker build -f  docker/SwaggerUIDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/swagger-ui:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/swagger-ui:"$TAG"
fi
if [[ $SERVICES == *"workspace-service"* ]]; then
    docker build -f  docker/WorkspaceServiceDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/workspace-service:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/workspace-service:"$TAG"
fi
if [[ $SERVICES == *"steampipe"* ]]; then
    docker build --no-cache -f  docker/SteampipeServiceDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/steampipe-service:"$TAG" --build-arg PLUGIN_REGISTRY="435670955331.dkr.ecr.us-east-2.amazonaws.com"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/steampipe-service:"$TAG"
fi

if [[ $SERVICES == *"redoc"* ]]; then
    docker build -f  docker/RedocDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/redoc:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/redoc:"$TAG"
fi

if [[ $SERVICES == *"alerting-service"* ]]; then
    docker build -f  docker/AlertingServiceDockerfile . -t 435670955331.dkr.ecr.us-east-2.amazonaws.com/alerting-service:"$TAG"
    docker push 435670955331.dkr.ecr.us-east-2.amazonaws.com/alerting-service:"$TAG"
fi