@startuml Kaytu_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(admin, "Admin")

System_Ext(slack, "Slack")

System_Boundary(kaytuPlatform, "Kaytu Platform") {
    Container(flux, "Flux", "", "Workspace management")
    Container(certManager, "Cert manager", "Go", "Certificate management")
    Container(contour, "Contour", "Go", "Load balancer")

    Container(jaeger, "Jaeger", "Go", "Monitoring")
    Rel(admin, jaeger, "View performance metrics")

    Container(prometheus, "Prometheus", "Go", "Monitoring")
    Container(alertManager, "Alert manager", "Go", "Alerting")
    Rel(alertManager, prometheus, "")
    Rel(alertManager, slack, "sends alerts to")

    Container(loki, "Loki", "Go", "Log management")
    Container(grafana, "Grafana", "Go", "Monitoring")
    Rel(grafana, loki, "")
    Rel(grafana, prometheus, "")
    Rel(admin, grafana, "View logs & monitoring")

    Container(sealedSecret, "SealedSecret", "Go", "Secret management")
    Container(velero, "Velero", "Go", "Backup")
    
    Container(keda, "KEDA", "Go", "Workspace management")
}

@enduml