package main

import (
	"os"

	swagger "github.com/swaggo/echo-swagger"
	_ "gitlab.com/keibiengine/keibi-engine/pkg/docs" // docs is generated by Swag CLI, you have to import it.
	"gitlab.com/keibiengine/keibi-engine/pkg/inventory"
)

var (
	HttpAddress = os.Getenv("HTTP_ADDRESS")
)

func main() {
	r := inventory.InitializeRouter()
	r.GET("/swagger/*", swagger.WrapHandler)
	r.Logger.Fatal(r.Start(HttpAddress))
}
