package main

import (
	"os"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/labstack/gommon/log"
	swagger "github.com/swaggo/echo-swagger"
	_ "gitlab.com/keibiengine/keibi-engine/pkg/docs" // docs is generated by Swag CLI, you have to import it.
	_ "gorm.io/datatypes"
)

var (
	HttpAddress = os.Getenv("HTTP_ADDRESS")
)

//go:generate ../../scripts/generate_doc.sh

//	@title									Keibi Service API
//	@version								1.0
//	@host									dev-cluster.keibi.io
//	@schemes								https
//	@securityDefinitions.oauth2.application	OAuth2Application
//	@tokenUrl								https://example.com/oauth/token
//	@in										header
//	@name									Authorization
//	@description							Enter the token with the `Bearer` prefix.

func main() {
	e := echo.New()
	e.Logger.SetLevel(log.DEBUG) // TODO: change in prod
	e.Pre(middleware.RemoveTrailingSlash())
	e.Use(middleware.Logger())

	e.GET("/swagger/*", swagger.WrapHandler)
	e.Logger.Fatal(e.Start(HttpAddress))
}
