package main

import (
	"os"

	_ "github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	_ "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/labstack/gommon/log"
	_ "github.com/opengovern/og-util/pkg/api"
	_ "github.com/opengovern/og-util/pkg/es"
	_ "github.com/opengovern/og-util/pkg/opengovernance-es-sdk"
	_ "github.com/opengovern/og-util/pkg/source"
	_ "github.com/opengovern/opengovernance/docs" // docs is generated by Swag CLI, you have to import it.
	swagger "github.com/swaggo/echo-swagger"
	_ "gorm.io/datatypes"
)

var (
	HttpAddress = os.Getenv("HTTP_ADDRESS")
)

//go:generate ../../scripts/generate_doc.sh

//	@title						OpenGovernance Service API
//	@version					1.0
//	@host						api.opengovernance.io
//	@schemes					https
//	@securityDefinitions.apikey	BearerToken
//	@tokenUrl					https://example.com/oauth/token
//	@in							header
//	@name						Authorization
//	@description				Enter the token with the `Bearer` prefix.

func main() {
	e := echo.New()
	e.Logger.SetLevel(log.DEBUG) // TODO: change in prod
	e.Pre(middleware.RemoveTrailingSlash())
	e.Use(middleware.Logger())

	e.GET("/swagger/*", swagger.WrapHandler)
	e.Logger.Fatal(e.Start(HttpAddress))
}
