package source

type AssetDiscoveryMethodType string

const (
	AssetDiscoveryMethodTypeScheduled AssetDiscoveryMethodType = "scheduled"
)

type HealthStatus string

const (
	HealthStatusHealthy          HealthStatus = "healthy"
	HealthStatusUnhealthy        HealthStatus = "unhealthy"
	HealthStatusInitialDiscovery HealthStatus = "initial_discovery"
)

type SourceCreationMethod string

const (
	SourceCreationMethodManual SourceCreationMethod = "manual"
)

type ConnectorDirectionType string

const (
	ConnectorDirectionTypeIngress ConnectorDirectionType = "ingress"
	ConnectorDirectionTypeEgress  ConnectorDirectionType = "egress"
	ConnectorDirectionTypeBoth    ConnectorDirectionType = "both"
)

type ConnectorStatus string

const (
	ConnectorStatusEnabled    ConnectorStatus = "enabled"
	ConnectorStatusDisabled   ConnectorStatus = "disabled"
	ConnectorStatusComingSoon ConnectorStatus = "coming_soon"
)

type CredentialStatus string

const (
	CredentialStatusEnabled  CredentialStatus = "enabled"
	CredentialStatusDisabled CredentialStatus = "disabled"
)

type CredentialType string

const (
	CredentialTypeAutoGenerated CredentialType = "auto-generated"
	CredentialTypeManual        CredentialType = "manual"
)
